### ISSUE TITLE
Move webgoat-container UP one directory

### ISSUE THREAD

**Issue by dougmorato** [WebGoat/WebGoat#100]
Given @nbaars PR99 (https://github.com/WebGoat/WebGoat/pull/99) is merged sucessfully, this effectively eliminates webgoat-classloader.

With this, we can move webgoat-container UP one directory again. It will make a lot easier to maintain and release.

I propose this to be done before release 7.0

**Comment by dougmorato** [comment]
@nbaars @misfir3 : Thoughts on this ?

**Comment by nbaars** [comment]
We could move it up one level. But we also had the idea to split the container and the lesson API. So you don't need to include the whole container jar when you are building lessons only a jar which contains a set of interfaces. This makes the dependency between the container and the lessons more strict. As a lesson developer you don't need access to all the internals of the container. This API would be a new child project I guess.

**Comment by dougmorato** [comment]
Ok, closing for now due to future plans to add additional modules
