### ISSUE TITLE
Docker: org.hsqldb.HsqlException: Network client is not a HSQLDB JDBC

### ISSUE THREAD

**Issue by ivanrome** [WebGoat/WebGoat#1016]
Hello

Using the docker latest container I get the folowing error : _org.hsqldb.HsqlException: Network client is not a HSQLDB JDBC driver_

Full Log: 
> user@linux:~$ docker run -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf
> Starting nginx: nginx.
> Starting WebGoat...
> Starting WebWolf...
> 09:36:59.319 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: --webgoat.build.version=8.2.0,--server.address=0.0.0.0
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                (v2.4.3)
> 
> 2021-07-11 09:37:00.609  INFO 23 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.2.0 using Java 15.0.2 on 23b642c8d02b with PID 23 (/home/webgoat/webgoat.jar started by webgoat in /home/webgoat)
> 2021-07-11 09:37:00.610 DEBUG 23 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v2.4.3, Spring v5.3.4
> 2021-07-11 09:37:00.611  INFO 23 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
> 2021-07-11 09:37:03.201  INFO 23 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
> 2021-07-11 09:37:03.349  INFO 23 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 130 ms. Found 2 JPA repository interfaces.
> 2021-07-11 09:37:04.289  WARN 23 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
> 2021-07-11 09:37:04.308  INFO 23 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
> 2021-07-11 09:37:04.308  INFO 23 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3556 ms
> 2021-07-11 09:37:04.617  INFO 23 --- [           main] org.owasp.webgoat.HSQLDBDatabaseConfig   : Starting internal database on port 9001 ...
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@3e587920]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@3e587920]: [Thread[main,5,main]]: setDatabasePath(0,/home/webgoat/.webgoat-8.2.0//data/webgoat)
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@3e587920]: [Thread[main,5,main]]: setDaemon(true)
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@3e587920]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@3e587920]: [Thread[main,5,main]]: setAddress(0.0.0.0)
> [Server@3e587920]: [Thread[main,5,main]]: setTrace(false)
> [Server@3e587920]: Initiating startup sequence...
> [Server@3e587920]: Server socket opened successfully in 1 ms.
> 2021-07-11 09:37:05.005  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : Checkpoint start
> 2021-07-11 09:37:05.006  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : checkpointClose start
> 2021-07-11 09:37:05.007  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : checkpointClose synched
> 2021-07-11 09:37:05.012  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : checkpointClose script done
> 2021-07-11 09:37:05.023  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : checkpointClose end
> 2021-07-11 09:37:05.024  INFO 23 --- [erver @3e587920] hsqldb.db.HSQLDB7A947F8CDF.ENGINE        : Checkpoint end - txts: 1
> [Server@3e587920]: Database [index=0, id=0, db=file:/home/webgoat/.webgoat-8.2.0//data/webgoat, alias=webgoat] opened successfully in 351 ms.
> [Server@3e587920]: Startup sequence completed in 353 ms.
> [Server@3e587920]: 2021-07-11 07:37:05.031 HSQLDB server 2.5.1 is online on port 9001
> [Server@3e587920]: To close normally, connect and execute SHUTDOWN SQL
> [Server@3e587920]: From command line, use [Ctrl]+[C] to abort abruptly
> 2021-07-11 09:37:05.170  INFO 23 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 7.1.1 by Redgate
> 2021-07-11 09:37:05.342  INFO 23 --- [           main] o.f.c.i.database.base.DatabaseType       : Database: jdbc:hsqldb:hsql://0.0.0.0:9001/webgoat (HSQL Database Engine 2.5)
> 2021-07-11 09:37:05.403  INFO 23 --- [           main] o.f.core.internal.database.base.Schema   : Creating schema "container" ...
> 2021-07-11 09:37:05.411  INFO 23 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "container"."flyway_schema_history" ...
> 2021-07-11 09:37:05.541  INFO 23 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "container": null
> 2021-07-11 09:37:05.558  INFO 23 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "container" to version "1 - init"
> 2021-07-11 09:37:05.597  INFO 23 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "container" to version "2 - version"
> 2021-07-11 09:37:05.632  INFO 23 --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 2 migrations to schema "container" (execution time 00:00.112s)
> 2021-07-11 09:37:05.908  INFO 23 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
> 2021-07-11 09:37:05.997  INFO 23 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.28.Final
> 2021-07-11 09:37:06.191  INFO 23 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
> 2021-07-11 09:37:06.458  INFO 23 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
> 2021-07-11 09:37:07.339  INFO 23 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
> 2021-07-11 09:37:07.350  INFO 23 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
> 2021-07-11 09:37:08.073  WARN 23 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
> 2021-07-11 09:37:08.628  WARN 23 --- [           main] o.o.webgoat.lessons.CourseConfiguration  : Lesson: webgoat.title has no endpoints, is this intentionally?
> Browse to http://localhost to get started
>        main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@2e26173, org.springframework.security.web.context.SecurityContextPersistenceFilter@3134153d, org.springframework.security.web.header.HeaderWriterFilter@4f8d86e4, org.springframework.security.web.authentication.logout.LogoutFilter@235d659c, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@2f74900b, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@5f5effb0, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@463561c5, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@27be17c8, org.springframework.security.web.session.SessionManagementFilter@1697f2b3, org.springframework.security.web.access.ExceptionTranslationFilter@e38f0b7, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3382cf68]
> org.hsqldb.HsqlException: Network client is not a HSQLDB JDBC driver
> 	at org.hsqldb.error.Error.error(Unknown Source)
> 	at org.hsqldb.error.Error.error(Unknown Source)
> 	at org.hsqldb.server.ServerConnection.handshake(Unknown Source)
> 	at org.hsqldb.server.ServerConnection.init(Unknown Source)
> 	at org.hsqldb.server.ServerConnection.run(Unknown Source)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> 2021-07-11 09:37:15.452  INFO 23 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
> 2021-07-11 09:37:16.196  INFO 23 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
> 2021-07-11 09:37:16.276  INFO 23 --- [           main] io.undertow                              : starting server: Undertow - 2.2.4.Final
> 2021-07-11 09:37:16.301  INFO 23 --- [           main] org.xnio                                 : XNIO version 3.8.0.Final
> 2021-07-11 09:37:16.317  INFO 23 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.0.Final
> 2021-07-11 09:37:16.512  INFO 23 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
> 2021-07-11 09:37:16.637  INFO 23 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8080 (http) with context path '/WebGoat'
> 2021-07-11 09:37:16.676  INFO 23 --- [           main] org.owasp.webgoat.StartWebGoat           : Started StartWebGoat in 17.053 seconds (JVM running for 17.932)

Thanks!

**Comment by zubcevic** [comment]
I noticed the message as well. All lessons seem to work fine nevertheless

**Comment by ivanrome** [comment]
> I noticed the message as well. All lessons seem to work fine nevertheless

Yes!
http://localhost:8080/WebGoat

**Comment by nbaars** [comment]
Also interesting to notice the `webgoat.log` file does not contain this message:

`nFilter@7ed7ae, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@4ad896f7]
2021-08-22 18:13:12.653  INFO 25 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applica
tionTaskExecutor'
2021-08-22 18:13:12.815  INFO 25 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base p
ath '/actuator'
2021-08-22 18:13:12.835  INFO 25 --- [           main] io.undertow                              : starting server: Undertow - 2.2.4.Fin
al
2021-08-22 18:13:12.839  INFO 25 --- [           main] org.xnio                                 : XNIO version 3.8.0.Final
2021-08-22 18:13:12.844  INFO 25 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.0
.Final
2021-08-22 18:13:12.877  INFO 25 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2021-08-22 18:13:12.900  INFO 25 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8080 (htt
p) with context path '/WebGoat'
2021-08-22 18:13:12.908  INFO 25 --- [           main] org.owasp.webgoat.StartWebGoat           : Started StartWebGoat in 5.573 seconds
 (JVM running for 5.981)
Browse to http://localhost to get started`

**Comment by nbaars** [comment]
this is due to starting WebWolf
