### ISSUE TITLE
Sql injection(advanced) login as tom

### ISSUE THREAD

**Issue by pemathinleylepcha2000** [WebGoat/WebGoat#1018]
------------------------------------------------------------------------------
It shows the error message (try to login as tom) but the cource gets completed using the the this injection we need to Register as name:"
Tom' AND SUBSTRING(password,1,1)='t(any character but must be same as that of password field)"
 Email :any
Password: t
Confirm password : t

And now login using 
Name:Tom' AND SUBSTRING(password,1,1)='t
Password: t

**Comment by pemathinleylepcha2000** [comment]
--------------------------------------
It shows the error message (try to login as tom) but the cource gets completed using the the this injection we need to Register as name:"
Tom' AND SUBSTRING(password,1,1)='t(any character but must be same as that of password field)"
 Email :any
Password: t
Confirm password : t
---------------------------------------
And now login using 

Name:Tom' AND SUBSTRING(password,1,1)='t
Password: t

**Comment by nbaars** [comment]
@pemathinleylepcha2000 this has been solved with https://github.com/WebGoat/WebGoat/issues/962 and released in version 8.2.0 (new release)
