### ISSUE TITLE
lesson:Your own mailbox

### ISSUE THREAD

**Issue by v1nw1n** [WebGoat/WebGoat#1020]
There was an error while sending the e-mail. Is WebWolf running?
I/O error on POST request for "http://localhost:9090/mail": u62D2u7EDDu8FDEu63A5 (Connection refused); nested exception is java.net.ConnectException: u62D2u7EDDu8FDEu63A5 (Connection refused)

**Comment by nbaars** [comment]
@v1nw1n do you have WebWolf running as well? See: https://github.com/WebGoat/WebGoat#installation-instructions
Let us know if this does not solve your issue by reopening this issue

**Comment by boly38** [comment]
I've got the same issue running docker image on WSL 2 and as the backend (docker image) dont see the (win) hosts resolution, we have to add the resolution on backend side (`/etc/hosts` of WSL2 or else add to `docker run` the following argument `--add-host www.webwolf.local:127.0.0.1`
