### ISSUE TITLE
WebWolf -V8.2.1 - Not working

### ISSUE THREAD

**Issue by SushilRkz** [WebGoat/WebGoat#1023]
Hey guys! Someone help me out with this->
when I run this "java -jar webwolf-8.2.1.jar" in my cmd line I get this 
"It seems the application is startd on a OS with non default UTF-8 encoding:Cp1252
Please add: -Dfile.encoding=UTF-8"
I surfed a lot but I am not able to find any solution to open WebWolf.
WebGoat works fine but webwolf is not opening.
-I'm using windows 10.

**Comment by SushilRkz** [comment]
Found the solution!
Use " java -Dfile.encoding=UTF-8 -jar webwolf-8.2.1.jar".

**Comment by nbaars** [comment]
@SushilRkz thanks, added this property explicitly to the README.md
