### ISSUE TITLE
In PostMapping "xxe/blind" ,CONTENTS.contains not checked for null (Innocuous)

### ISSUE THREAD

**Issue by yanghaoi** [WebGoat/WebGoat#1026]
If my external entity is a “null file”, webgoat will be say me "Nice try, you need to send the file to WebWolf", It's `CONTENTS.contains("") `   => True.
![](https://i.loli.net/2021/08/16/dia6U8Z7z5hyYpX.png)

**Comment by nbaars** [comment]
@yanghaoi I looked into this and if I'm correct you want to read a different file (c:\\null.txt) without contents, the attack might have indeed worked, but the assignment mentions you need to:

> upload the contents of a file secret.txt from the WebGoat server to our WebWolf server

This is the secret on the server side you want to get access to. In this case, you added a file with no contents. We can, of course, check if the file was read instead but that requires us to parse the entities to find for example: `file:///C:\\null.txt` this can be in many forms making it difficult to get right.
At the moment we check for a fixed file with random (per user) content and see if this is part of a comment. 

For now, I would like to keep it as is, if you want to read a different file (random file) in the attack please supply a PR I would be happy to merge it. Closing for now, feel free to open it when supplying a PR.
