### ISSUE TITLE
Move CLA assistant to Github actions

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#1028]
Seems that the remote hosted one is rate limited causing issues while creating MRs resulting in a manual action to recheck 

https://github.com/cla-assistant/github-action

Do not forget to export the json file with the ones who already signed the CLA from https://cla-assistant.io/

----

We can also do this: https://github.com/cla-assistant/cla-assistant/issues/520

> Thank you for the detailed analyse of the issue. It looks like a bug from our side and we are looking into it.
As a workaround, like @winder mentioned, you can retrigger the CLA check with the recheckPR button from the CLA Assistant UI, or you can also retrigger the CLA check for a particular Pull Request using this API https://cla-assistant.io/check/<orgname>/<reponame>?pullRequest=10. @andreasohlund, In your case the recheck API will be https://cla-assistant.io/check/ Particular/NServiceBus?pullRequest=5549

And add it as a bot command which you can type in the MR: `recheckCLA` or something along those line.

**Comment by nbaars** [comment]
Or even simpler add contributing.md with our principles:

- Build pipeline should be green before creating a MR.
- Pull request should be made against develop
- With each commit you agree with https://developercertificate.org/

**Comment by commjoen** [comment]
will take a look at this as the next step, including Contributor Covenant tags

**Comment by commjoen** [comment]
Progress can be followed at https://github.com/WebGoat/WebGoat/pull/1069

**Comment by commjoen** [comment]
So instead of CLA, I will try to move to git sign off, whcih can be validated by means of a plugin. This can simplify it quite a lot.
