### ISSUE TITLE
SQL Injection (intro) 5: Data Control Language (DCL) the wiki's solution is not correct

### ISSUE THREAD

**Issue by rikonaka** [WebGoat/WebGoat#1031]
![图片](https://user-images.githubusercontent.com/13602602/130759997-ba72d0ee-33cb-4e9c-9def-7b8a2620bcbf.png)
So, what's the correct solution for this lession 😂
And I have tried this but it's still not correct
```
GRANT ALTER TABLE ON grant_rights TO unauthorized_user
```

**Comment by nbaars** [comment]
@rikonaka fixed, updated the lesson and the hints etc. Thanks for reporting this issue.

**Comment by purevoc** [comment]
@rikonaka A command that worked for me is:

GRANT all ON grant_rights TO unauthorized_user

I had trouble with this problem and used the exact same command you tried initially, this should work though and I hope it helps!

**Comment by inferno10x1** [comment]
grant all on grant_rights to unauthorized_user;
this query is working.
