### ISSUE TITLE
General > Crypto Basics > Lesson 8

### ISSUE THREAD

**Issue by dave-br** [WebGoat/WebGoat#1041]
The assignment on this lesson has steps that can be circumvented, which brings into question whether it is achieving its intended goal.  The instructions and hints indicate that one needs to sign in as root, and docker cp can be used to illegitimately adjust credentials inside the container to do so.  But one need not sign into or even run the container at all.

If the point of the assignment is to find the secret in the container, "docker container cp" can be used to do that directly.  The instructions indicate what folder the secret resides in, so a surgical "docker container cp" which specifies just that folder is enough to pull the secret file into the host, where it can be easily read.  After that, any Linux shell is capable of running the openssl command to decrypt the message.  No need to run the container at all (much less find a way to sign in as root).

If the goal of the lesson is to teach that docker containers are a bad place to store secrets, I'd recommend you adjust the instructions & hints to be more direct and abandon the idea that one needs to crack root access.  If the goal of the lesson is to motivate learning about how Linux credentials and passwords are stored, I'd recommend you add lesson text describing them in some detail and rewrite the assignment in a way that actually requires credential browsing or modification.

BTW, this is a GREAT resource.  I've been enjoying going through the lessons!

**Comment by zubcevic** [comment]
Thanks for your comments. Yes this last assignment can be solved in many ways. 
Main goal is to point out that secrets should not be stored inside a container, nor used during a build phase as build arguments. 
If you have a container runtime environment that allows you to copy stuff to and from a running image you already have some kind of security issue. You could copy it like you suggest or you could use copy to login as root.

**Comment by dave-br** [comment]
Thanks for the clarification.  In that case, my advice would be to simplify the instructions / hints.  Rather than requiring knowledge of Linux authentication, simply nudge the user toward using docker container cp against the secret file itself.  I think that would be a more direct way to demonstrate the issue.

But, of course, it's your call!  Thank you for working on such a cool project.
