### ISSUE TITLE
JWT Tokens: Error in exercice 7

### ISSUE THREAD

**Issue by erwanvivien** [WebGoat/WebGoat#1049]
> http://localhost:8080/WebGoat/start.mvc#lesson/JWT.lesson/7

This page accepts an unsigned token.
`eyJhbGciOiJIUzI1NiJ9.ew0KICAiRW1haWwiIDogInRvbUB3ZWJnb2F0Lm9yZyIsDQogICJSb2xlIiA6IFsgIk1hbmFnZXIiLCAiUHJvamVjdCBBZG1pbmlzdHJhdG9yIiBdLA0KICAiYXVkIiA6ICJ3ZWJnb2F0Lm9yZyIsDQogICJleHAiIDogMTYzOTUzODk5NSwNCiAgImlhdCIgOiAxNjMxNTM4OTM1LA0KICAiaXNzIiA6ICJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLA0KICAic3ViIiA6ICJ0b21Ad2ViZ29hdC5vcmciLA0KICAidXNlcm5hbWUiIDogIldlYkdvYXQiDQp9.` is a valid answer, no need to compute the signature as said in the 'correction'

I was kinda puzzled when it got accepted, as I didn't feel this was a correct answer

**Comment by nbaars** [comment]
Interesting, the `parse` method does not validate when alg is set to HMAC and you don't have a signature only a `.` at the end.

**Comment by aolle** [comment]
It's a known behavior. The _parseClaimsJws_ method has to be invoked for guarantee the correct security model for parsing signed tokens.

https://github.com/jwtk/jjwt#jws-read

PR sent for fixing this issue.
