### ISSUE TITLE
Instead of waiting fixed amount of time before starting WebWolf let's use actuator endpoints to see if WebGoat is up and running

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#1058]
In the script to start WebGoat/WebWolf in the Docker image, we wait 30 seconds. It's better to use `curl` and check whether the actuator endpoints of Spring Boot report that WebGoat is up-and-running.

**Comment by zubcevic** [comment]
timeout 30 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/localhost/$WEBGOAT_PORT; do sleep 1; done'

**Comment by zubcevic** [comment]
That will do the trick or something similar. I tried it in the container itself and it works there as well

Only 30 is a bit of a random number, but without a timeout it is also not ideal. 
If the port is up it will continue. So maybe 100 in stead of 30?
