### ISSUE TITLE
WebWolf Application started on a OS with non default UTF-8 encoding:Cp1252

### ISSUE THREAD

**Issue by alexNaderMaincare** [WebGoat/WebGoat#1059]
I have an issue when trying to start WebWolf

![image](https://user-images.githubusercontent.com/82366995/133809974-fa6602d6-ad7c-4752-8708-769c5abee67c.png)

Where should I add the -Dfile.encoding=UTF-8 command ?

**Comment by zubcevic** [comment]
see the wiki 
https://github.com/WebGoat/WebGoat/wiki

**Comment by alexNaderMaincare** [comment]
Hi @zubcevic , I still have the issue when I add the option:

![image](https://user-images.githubusercontent.com/82366995/134166343-bc477af7-b587-4bcd-8cac-82168734bf55.png)
