### ISSUE TITLE
Have a lesson on CI/CD?

### ISSUE THREAD

**Issue by commjoen** [WebGoat/WebGoat#1096]
It would be great if we can have a lesson about CI/CD based on a rogue github action and/or some secret used to derive an answer from in the pipeline (aka extract secret by forking the repo and getting it out) :)!

**Comment by nbaars** [comment]
:-) this is probably already covered in WrongSecrets project :-)

**Comment by commjoen** [comment]
yes :D https://wrongsecrets.herokuapp.com/challenge/challenge-13
