### ISSUE TITLE
How to change WebGoat IP Address in Docker container?

### ISSUE THREAD

**Issue by w0lfcat** [WebGoat/WebGoat#1115]
I use docker to run WebGoat 

`docker run -it -p 8888:8888 -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf:v8.2.2`

and notice that it's IP Address has been hardcoded to 127.0.0.1.

```
$ curl -s localhost:8888 | grep -oP '(?<=href=").*(?=" title)'
http://127.0.0.1:8080/WebGoat
http://127.0.0.1:9090/WebWolf
$ 

$ curl -s 172.17.0.2:8888 | grep -oP '(?<=href=").*(?=" title)'
http://127.0.0.1:8080/WebGoat
http://127.0.0.1:9090/WebWolf
$ 
```

Would it be possible to change this to IP reachable in LAN?

I know it has been designed this way for security purpose.

I'm planning to setup isolated LAN lab without internet access with WebGoat installed on Raspberry Pi or VM or any unused old computer so that multiple player with little or no technical background can join and learn it without setting up their own lab.

There's been a few suggestion but I don't think those will work

1.     reverse proxy
2.     iptables to route traffic to 127.0.0.1:8080/WebGoat
3.     docker macvlan

However, if you managed to make it work with any of these methods, please share the details.

The only option left right now is to change the hardcoded IP Address in the container itself.

```
webgoat@ffff:~$ ls -lh
total 144M
-rw-r--r-- 1 webgoat webgoat  797 Sep  5 14:43 start.sh
-rw-r--r-- 1 webgoat webgoat  92M Sep  5 14:44 webgoat.jar
-rw-r--r-- 1 webgoat webgoat 8.2K Oct 19 12:39 webgoat.log
-rw-r--r-- 1 webgoat webgoat  52M Sep  5 14:44 webwolf.jar
-rw-r--r-- 1 webgoat webgoat 5.1K Oct 19 12:39 webwolf.log
webgoat@ffff:~$ 
```

There is nothing much in start.sh script

```
webgoat@ffff:~$ nl start.sh 
     1	#!/bin/bash
       
     2	cd /home/webgoat 
     3	service nginx start
     4	sleep 1
     5	echo "Starting WebGoat..."
       
     6	java \
     7	 -Duser.home=/home/webgoat \
     8	 -Dfile.encoding=UTF-8 \
     9	 --add-opens java.base/java.util=ALL-UNNAMED \
    10	 --add-opens java.base/java.lang.reflect=ALL-UNNAMED \
    11	 --add-opens java.base/java.text=ALL-UNNAMED \
    12	 --add-opens java.desktop/java.awt.font=ALL-UNNAMED \
    13	 --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
    14	 --add-opens java.base/java.io=ALL-UNNAMED \
    15	 -jar webgoat.jar --webgoat.build.version="$1" --server.address=0.0.0.0 > webgoat.log &
       
    16	sleep 10
       
    17	echo "Starting WebWolf..."
    18	java -Duser.home=/home/webgoat -Dfile.encoding=UTF-8 -jar webwolf.jar --webgoat.build.version=$1 --server.address=0.0.0.0 > webwolf.log &
       
    19	echo "Browse to http://localhost to get started" >> webgoat.log
       
    20	tail -300f webgoat.log
webgoat@ffff:~$ 

And apparently there are 240 files in webgoat.jar and I'm not really sure which one should be changed.

webgoat@ffff:~$ jar tvf webgoat.jar | wc -l
240
webgoat@ffff:~$ 
```

Please help

**Comment by akshanshshrivastava** [comment]
Facing the same issue tried the below thing but it says 
`docker: Error response from daemon: driver failed programming external connectivity on endpoint webgoat (7553c775fb85aff6184e114124717e48373f18295af4fca5ff05933c5c148a2b): Error starting userland proxy: listen tcp4 34.131.88.80:9090: bind: cannot assign requested address.
ERRO[0000] error waiting for container: context canceled`

> One possible work-around:
> 
> 1. start webgoat using this: `docker run -it -p <remotewebgoatip>:80:8888 -p <remotewebgoatip>:8080:8080 -p <remotewebgoatip>:9090:9090 -e TZ=Europe/Amsterdam --name webgoat webgoat/goatandwolf:v8.2.2`
> 2. on the machine you want to access the remote webgoat from, do:
>    `ssh -L 8989:<remotewebgoatip>:80 -L 8080:<remotewebgoatip>:8080 -L 9090:<remotewebgoatip>:9090 <user>@<remotewebgoatip>` and keep that window open.
> 
> Now visit `http://<remotewebgoatip>:8989`
