### ISSUE TITLE
[Insecure Deserialization]: "Serialization ID does not match" even when it does

### ISSUE THREAD

**Issue by plibither8** [WebGoat/WebGoat#1129]
This is regarding the 5th assignment of the Lesson "Insecure Deserialization" (http://127.0.0.1:8080/WebGoat/start.mvc#lesson/InsecureDeserialization.lesson/4).

The solution outputs "The serialization id does not match. Probably the version has been updated. Let's try again.", even when the serialization UID does match (`2`), and the objects are valid.

I've created a Repl: https://replit.com/@plibither8/CheeryFirmTelephones#Main.java, to reproduce the issue. All the code for the `VulnerableTaskHolder` and `SerializationHelper` classes have been copied over (with the name change to `Main`), and I've added the `main()` function that performs the demonstration of this issue.

**Comment by nbaars** [comment]
@plibither8/@oshhh in the repl I see you are using JDK-11 is this also the one you are using to run WebGoat?

**Comment by plibither8** [comment]
@nbaars, I am using WebGoat through Docker, so whatever version that's being used in the latest Docker image.

**Comment by nbaars** [comment]
@plibither8 the latest Docker image is using Java 16 the repl is using Java 11 so this explains the mismatch. Can you try to use the same JDK?
