### ISSUE TITLE
Typo: Using Indrect References

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#1130]
The above is misspelled on page: http://localhost:8080/WebGoat/start.mvc#lesson/IDOR.lesson/5.  Might want to take ALL content, dump it into Word (or something) to get a spell check on everything.

**Comment by nbaars** [comment]
Thanks, fixed (also checked other contents in this lesson)

**Comment by nbaars** [comment]
Closing as we released 2023.3
