### ISSUE TITLE
Test failure in XXE  in jdk16.0.2 、win10

### ISSUE THREAD

**Issue by Au9999** [WebGoat/WebGoat#1135]
Guys, I’m not sure if this is my personal problem. I tried to build the latest version with jdk11, but maven directly reported an error with the jdk version, so I used jdk16, but xxe reported an error during the test. This is really bad, I I found that the same problem exists in historical jdk11, so I am not sure who made the mistake now. Below are some of my log messages. It would be great if it can be resolved.

log：

[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.278 s <<< FAILURE! - in org.owasp.webgoat.xxe.ContentTypeAssignmentTest
[ERROR] org.owasp.webgoat.xxe.ContentTypeAssignmentTest.workingAttack  Time elapsed: 0.094 s  <<< FAILURE!
java.lang.AssertionError:
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
        at org.owasp.webgoat.xxe.ContentTypeAssignmentTest.workingAttack(ContentTypeAssignmentTest.java:74)

[INFO] Running org.owasp.webgoat.xxe.SimpleXXETest
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.234 s <<< FAILURE! - in org.owasp.webgoat.xxe.SimpleXXETest
[ERROR] org.owasp.webgoat.xxe.SimpleXXETest.workingAttack  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError:
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
        at org.owasp.webgoat.xxe.SimpleXXETest.workingAttack(SimpleXXETest.java:61)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ContentTypeAssignmentTest.workingAttack:74 JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
[ERROR]   SimpleXXETest.workingAttack:61 JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
[INFO]
[ERROR] Tests run: 13, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WebGoat Parent Pom 8.2.3-SNAPSHOT:
[INFO]
[INFO] WebGoat Parent Pom ................................. SUCCESS [  2.078 s]
[INFO] webgoat-container .................................. SUCCESS [ 28.218 s]
[INFO] webgoat-plugins-parent ............................. SUCCESS [  0.266 s]
[INFO] bypass-restrictions ................................ SUCCESS [ 18.016 s]
[INFO] challenge .......................................... SUCCESS [  7.875 s]
[INFO] client-side-filtering .............................. SUCCESS [ 18.859 s]
[INFO] cross-site-scripting ............................... SUCCESS [  7.156 s]
[INFO] html-tampering ..................................... SUCCESS [  1.344 s]
[INFO] http-basics ........................................ SUCCESS [  1.344 s]
[INFO] cia ................................................ SUCCESS [ 18.234 s]
[INFO] chrome-dev-tools ................................... SUCCESS [ 17.313 s]
[INFO] http-proxies ....................................... SUCCESS [  5.500 s]
[INFO] insecure-login ..................................... SUCCESS [  1.250 s]
[INFO] insecure-deserialization ........................... SUCCESS [ 10.000 s]
[INFO] jwt ................................................ SUCCESS [ 20.172 s]
[INFO] sql-injection ...................................... SUCCESS [ 22.078 s]
[INFO] xxe ................................................ FAILURE [ 19.828 s]
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-introduction ............................... SKIPPED
[INFO] webwolf-introduction ............................... SKIPPED
[INFO] auth-bypass ........................................ SKIPPED
[INFO] missing-function-ac ................................ SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] password-reset ..................................... SKIPPED
[INFO] ssrf ............................................... SKIPPED
[INFO] secure-passwords ................................... SKIPPED
[INFO] webgoat-lesson-template ............................ SKIPPED
[INFO] crypto ............................................. SKIPPED
[INFO] path-traversal ..................................... SKIPPED
[INFO] spoof-cookie ....................................... SKIPPED
[INFO] webgoat-server ..................................... SKIPPED
[INFO] webwolf ............................................ SKIPPED
[INFO] webgoat-integration-tests .......................... SKIPPED
[INFO] webgoat-all-in-one-docker .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:20 min
[INFO] Finished at: 2021-11-01T21:12:34+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project xxe: There are test failures.
[ERROR]
[ERROR] Please refer to D:\code\idea_project\WebGoat_Code\WebGoat-develop\webgoat-lessons\xxe\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :xxe

-------------------------------------------------------------------------------
Test set: org.owasp.webgoat.xxe.BlindSendFileAssignmentTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.957 s - in org.owasp.webgoat.xxe.BlindSendFileAssignmentTest

-------------------------------------------------------------------------------
Test set: org.owasp.webgoat.xxe.ContentTypeAssignmentTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.278 s <<< FAILURE! - in org.owasp.webgoat.xxe.ContentTypeAssignmentTest
org.owasp.webgoat.xxe.ContentTypeAssignmentTest.workingAttack  Time elapsed: 0.094 s  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
	at org.owasp.webgoat.xxe.ContentTypeAssignmentTest.workingAttack(ContentTypeAssignmentTest.java:74)

-------------------------------------------------------------------------------
Test set: org.owasp.webgoat.xxe.SimpleXXETest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.234 s <<< FAILURE! - in org.owasp.webgoat.xxe.SimpleXXETest
org.owasp.webgoat.xxe.SimpleXXETest.workingAttack  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.feedback"
Expected: is "Congratulations. You have successfully completed the assignment."
     but: was "Sorry the solution is not correct, please try again."
	at org.owasp.webgoat.xxe.SimpleXXETest.workingAttack(SimpleXXETest.java:61)

**Comment by nbaars** [comment]
@Au9999 indeed the unit test failed in the past with some path issues. Did you check out the `develop` branch? This branch is on Java 17, but that should not really matter. Are you using Windows/Linux/MacOS?
