### ISSUE TITLE
Secure Passwords Lesson Nits

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#1143]
Stage 3: strength meter info is presented twice. And both Rules and Usability. Should only be presented once.

Stage 4: "are no good choices" should be "are not good choices", and "you to try" should be: "you try"

When you submit a password, it presents info like this twice:

Score: 1/4
Estimated cracking time in seconds: 0 years 1 days 3 hours 46 minutes 40 seconds

And the 'in seconds' part is redundant, should be removed. That info is not included the 1st time that info is presented.

Stage 5: "allow to test if one of your accounts got breached". I don't think 'test' is the right word here. 'Determine' maybe? Search?

"create an then securely store" should be "create and then securely store"

A lot of these are grammar problems. Maybe all text should be run through a grammar checker? e.g., Grab all the lesson content, paste it into Word, and see what it complains about.

Another NIT: I noticed in the Deserialization lesson, it says: "deserializaded", which is a misspelling. Again, please do a spell check on ALL content in EVERY lesson.

**Comment by nbaars** [comment]
@aolle sorry I already made the improvements, can you please review the PR?

**Comment by aolle** [comment]
sure!

**Comment by davewichers** [comment]
Don't forget the Deserialization lesson NIT!
