### ISSUE TITLE
i don't find the lesson Insecure Storage 

### ISSUE THREAD

**Issue by Bassem-bk-1220** [WebGoat/WebGoat#1145]
can someone tell me how to find the lesson insecure storage or how to add it ?

**Comment by nbaars** [comment]
@Bassem-bk-1220 correct we don't have a lesson regarding this topic. Would be great if you can contribute this lesson, we have a template setup here: http://localhost:8080/WebGoat/start.mvc#lesson/LessonTemplate.lesson

**Comment by Bassem-bk-1220** [comment]
i saw that insecure storage it's available in version 5.3 can you put it?

**Comment by nbaars** [comment]
We do have a lesson which covers client-side validation, for example this one resembles the old lesson: http://localhost:8080/WebGoat/start.mvc#lesson/ClientSideFiltering.lesson/2

This lesson touches upon all the important things to know about client side validation etc. The mentioned lesson is a variation on the already existing lessons.

Closing this issue for now, if someone want to add a new assignment around this topic please feel free to do so.
