### ISSUE TITLE
Missing lesson ,,Malicious execution" in WebGoat

### ISSUE THREAD

**Issue by Mariaoana** [WebGoat/WebGoat#1146]
Can you, please tell me where can I find the lesson ,,Malicious exeuction"? I can't find it on version 8.2.2, the latest one.

**Comment by nbaars** [comment]
Hi @Mariaoana no we don't have such a lesson at the moment, did you find a reference somewhere?

**Comment by nbaars** [comment]
With the path traversal lesson we have content which is in the same area. Closing this issue
