### ISSUE TITLE
SQL Injection (mitigation) Stage 4 Example wrong

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#1180]
This example has these two lines of code:

  try (Connection connection = null;
       PreparedStatement statement = connection.prepareStatement(query)) {

This code would cause an obvious null pointer exception. Can you make sure the examples here, and anywhere else all actually compile/work properly?  HOW you create a connection is actually needed to answer part of Stage 5.

**Comment by nbaars** [comment]
Added the connection part

**Comment by davewichers** [comment]
Thanks for fixing the specific issue mentioned. There was a broader comment as well: "Can you make sure the examples here, and anywhere else all actually compile/work properly?" 

Do you know if anyone went through all the examples to make sure they are all also correct?
