### ISSUE TITLE
2022-02-18T20:32:50.697Z [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.

### ISSUE THREAD

**Issue by contraster-steve** [WebGoat/WebGoat#1210]
Build fails when it gets to the webgoat-integration-tests.

[Server@6c519e47]: From command line, use [Ctrl]+[C] to abort abruptly
2022-02-18T20:32:50.697Z [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.15 s <<< FAILURE! - in org.owasp.webgoat.PasswordResetLessonTest
[ERROR] org.owasp.webgoat.PasswordResetLessonTest.testPathTraversal  Time elapsed: 15.147 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
No cookies defined in the response

Maven 3.6.3
JDK17

**Comment by zubcevic** [comment]
You should try with Maven 3.8 or higher.

See https://github.com/WebGoat/WebGoat/wiki/Developer-Getting-Started
