### ISSUE TITLE
How can I start WebGoat in anther port?

### ISSUE THREAD

**Issue by swaafwojo** [WebGoat/WebGoat#1216]
Hi 
I try this and doesn't work

----

`java -jar webgoat-server-8.2.2.jar --server.port=4444 --server.address=localhost    
20:22:45.780 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: --server.port=4444,--server.address=localhost
20:22:45.798 [main] ERROR org.owasp.webgoat.StartWebGoat - Port [ip address]:8080 is already in use
Port [ip address]:8080 is in use. Use environment value WEBGOAT_PORT to set a different  value.`

``

**Comment by aolle** [comment]
Hello, you have it on the log, for example:

`WEBGOAT_PORT=12345 java -jar webgoat-server-8.2.2.jar `

**Comment by swaafwojo** [comment]
okkkkk

**Comment by katherine-hub** [comment]
i am getting this while using webgoat
03:12:23.480 [main] INFO org.owasp.webgoat.StartWebGoat - Starting WebGoat with args: 
03:12:23.509 [main] ERROR org.owasp.webgoat.StartWebGoat - Port 127.0.0.1:8080 is already in use
Port 127.0.0.1:8080 is in use. Use environment value WEBGOAT_PORT to set a different value.
--server.port is not working and when i am using WEBGOAT_PORT it is showing command not found

**Comment by katherine-hub** [comment]
How do i come to know which port is open because i tried so many and everytime it is showing this port is in use
