### ISSUE TITLE
Analyze (java) build fail due to invalid pom.file 

### ISSUE THREAD

**Issue by jhasslof** [WebGoat/WebGoat#1219]
When running Code Scanning Analyze(java) at commit 2332bf22a7534eab97066b7c6970814c85f79635 I get the following build error. 

`Error: 3-15 19:16:46] [autobuild] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project webgoat-container: Fatal error compiling: error: invalid target release: 15 -> [Help 1]
  [2022-03-15 19:16:46] [autobuild] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project webgoat-container: Fatal error compiling`

This is due to `maven-compiler-plugin.version` java version set here 
https://github.com/WebGoat/WebGoat/blob/984548ae8866512d5d098e48b3e40097756140f3/pom.xml#L195
and JAVA Version set here
https://github.com/WebGoat/WebGoat/blob/984548ae8866512d5d098e48b3e40097756140f3/pom.xml#L134
and <maven.compiler.source> here
https://github.com/WebGoat/WebGoat/blob/984548ae8866512d5d098e48b3e40097756140f3/pom.xml#L118
Does not match.

But I cant the right combination for the build to work

**Comment by zubcevic** [comment]
In the latest develop version this has been fixed
