### ISSUE TITLE
The lesson '(A1) Injection - Path traversal' seems to contain wrong description

### ISSUE THREAD

**Issue by gintooooonic** [WebGoat/WebGoat#1233]
Hi, I'm using WebGoat v8.2.2 and I'm having trouble with the description in the lesson `(A1) Injection - Path traversal`.

Here's a copy from https://github.com/WebGoat/WebGoat/blob/v8.2.2/webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload.adoc

```
=== Path traversal while uploading files

In this assignment the goal is to overwrite a specific file on the file system. Of course WebGoat cares about the users
so you need to upload your file to the following location which is outside the normal upload location.

|===
|OS |Location

|`operatingSystem:os[]`
|`webGoatTempDir:temppath[]PathTraversal/username:user[]`

|===
```

Since the file needs to be uploaded to `~/.webgoat-8.2.2/PathTraversal/` to solve the lesson,
I think 'Location' should be `webGoatTempDir:temppath[]PathTraversal/`.

**Comment by aolle** [comment]
Hello,

I have been checking the issue and effectively the file has to be uploaded into the upper directory to solve the lesson.

I will fix it and add more details to make it clearer.
