### ISSUE TITLE
SEVERE: The web application [/WebGoat] appears to have started a thread named [pool-7-thread-5] but has failed to stop it. This is very likely to create a memory leak

### ISSUE THREAD

**Issue by dougmorato** [WebGoat/WebGoat#124]
Upon running the tomcat shutdown goal, I receive the following errors multiple times:
```SEVERE: The web application [/WebGoat] appears to have started a thread named [pool-7-thread-5] but has failed to stop it. This is very likely to create a memory leak```

After some investigation, I believe this is due to creating some threads and not releasing them after job completion: 

The only sensible place i could find where newFixedThreadPool was: 
https://github.com/WebGoat/WebGoat/blob/master/webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginsLoader.java#L112

@nbaars : Would it be possible to do a try/catch/finally, where we call ```executorService.shutdown()``` in the catch/finally, something like ?:
```java
private List<Plugin> processPlugins(List<URL> jars) throws Exception {
try {
    final List<Plugin> plugins = Lists.newArrayList();
    final ExecutorService executorService = Executors.newFixedThreadPool(10);
    final CompletionService<Plugin> completionService = new ExecutorCompletionService<>(executorService);
    final List<Callable<Plugin>> callables = extractJars(jars);

    for (Callable<Plugin> s : callables) {
        completionService.submit(s);
    }
    int n = callables.size();
    for (int i = 0; i < n; i++) {
        Plugin plugin = completionService.take().get();
        if (plugin.getLesson().isPresent()) {
            plugins.add(plugin);
        }
    }
    LabelProvider.updatePluginResources(pluginTarget.resolve("plugin/i18n/WebGoatLabels.properties"));
} catch catch (IOException ex) {
   executorService.shutdown();
} finally {
    executorService.shutdown(); 
}
return plugins;
}
``` 

If not, maybe we could use ```@Transactional``` on the processPlugins method?

**Comment by nbaars** [comment]
Finally part is enough, pull request is available.

**Comment by dougmorato** [comment]
Merged and works :100: %

Thanks
