### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by tokiidokii** [WebGoat/WebGoat#1245]
Hi, I've struggling a bit trying to run WebGoat. I managed to install it successfully, but when I spring-boot I get this error. 

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/WebGoat/src/test/java/org/owasp/webgoat/lessons/hijacksession/cas/HijackSessionAuthenticationProviderTest.java:[39,66] cannot find symbol
  symbol:   class AuthenticationBuilder
  location: class org.owasp.webgoat.lessons.hijacksession.cas.Authentication
[INFO] 1 error

**Comment by zubcevic** [comment]
how do you compile? Do you use the mvn clean install from the Readme? What is your output of mvn -version

**Comment by sushmakummari** [comment]
I have checked the code, it has no syntax errors, I have just cloned and ran the command  **mvn clean install** .it is showing the below compilation errors even though ; (colons) are in place. How do I fix them.

-------------------------------------------------------------
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[3,8] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[5,10] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[7,3] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[10,10] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[12,3] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,51] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,52] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,63] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[105,14] unclosed string literal
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,22] : expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,36] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,54] illegal start of expression
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,32] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,33] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,39] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,26] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,31] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[109,18] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[110,19] unclosed string literal
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[110,17] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,87] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,88] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,92] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,34] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,35] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,47] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/users/WebGoatUser.java:[84,38] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/users/WebGoatUser.java:[84,51] not a statement
[INFO] 31 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.138 s
[INFO] Finished at: 2023-09-06T15:21:43+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project webgoat: Compilation failure: Compilation failure: 
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[3,8] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[5,10] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[7,3] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[10,10] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java:[12,3] class, interface, or enum expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,51] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,52] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/asciidoc/UsernameMacro.java:[23,63] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[105,14] unclosed string literal
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,22] : expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,36] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[106,54] illegal start of expression
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,32] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,33] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[107,39] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,18] illegal start of type
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,26] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[108,31] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[109,18] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[110,19] unclosed string literal
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/lessons/xxe/SimpleXXE.java:[110,17] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,87] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,88] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/lessons/LessonConnectionInvocationHandler.java:[25,92] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,34] ')' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,35] not a statement
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/assignments/LessonTrackerInterceptor.java:[62,47] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/users/WebGoatUser.java:[84,38] ';' expected
[ERROR] /home/sushma/Desktop/webgoat/WebGoat/src/main/java/org/owasp/webgoat/container/users/WebGoatUser.java:[84,51] not a statement
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
