### ISSUE TITLE
Error: Unable to access jarfile

### ISSUE THREAD

**Issue by tokiidokii** [WebGoat/WebGoat#1246]
Hi,

Having a difficult time running WebGoat
Tried using both
`java -jar webgoat-server-8.1.0.jar [--server.port=8080] [--server.address=localhost]`
 `java -Dfile.encoding=UTF-8 -jar webgoat-8.2.3.jar `

Error
`Error: Unable to access jarfile webgoat-server-8.1.0.jar
`

Solutions tried:

- Setting JDK Environment variable, PATH, and JAVA_HOME
- Putting the .jars in different folders, a different drive (and folder)
- Running CMD
- Running the CMD from the explorer window
- Running CMD as Admin

Windows 11
**Java version**
java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)

I have my JAVA_HOME set in the right place, have the latest version of Java, JDK, but somehow I can't seem to run it. What am I doing wrong?

**Comment by zubcevic** [comment]
Did you build the jar yourself following the steps in the Readme? Or did you download an specific older release?

**Comment by tokiidokii** [comment]
> 

I used the Readme, copy pasted it directly. I found out the issue. The Readme lists 
`java -Dfile.encoding=UTF-8 -jar webgoat-8.2.3.jar`
latest release is 8.2.2.

Works with
`java -Dfile.encoding=UTF-8 -jar webgoat-server-8.2.2.jar`

Should have read it more carefully to correct the command, my bad.

**Comment by zubcevic** [comment]
Ok great that this is clear now
