### ISSUE TITLE
Rewrite the WebWolf Introduction Lesson with the new changes

### ISSUE THREAD

**Issue by aolle** [WebGoat/WebGoat#1248]
After the last refactoring, the WebWolf introduction lesson should be rewritten, as we are not going to provide a standalone WebWolf jar anymore, right? 

http://127.0.0.1:8080/WebGoat/start.mvc#lesson/WebWolfIntroduction.lesson

**Comment by zubcevic** [comment]
As far as the text is concerned there are probably some areas that need to be re-written. But it still acts as a separate web site and can be configured on different host names as well. The default URL's for the browser are also still the same

**Comment by nbaars** [comment]
Updated the text, the icon will guide users to WebWolf

**Comment by nbaars** [comment]
Closing as we released 2023.3
