### ISSUE TITLE
It seems that the required database is not running. Please start WebGoat with the integrated or standalone database first.

### ISSUE THREAD

**Issue by ajeshashokan** [WebGoat/WebGoat#1261]
Hi,
I am trying to run WebWolf on the same Windows Server where WebGoat is running. I am trying "java -jar webwolf-8.2.2.jar --server.port=9090 --server.address=192.168.xxx.xxx" and getting the message "It seems that the required database is not running. Please start WebGoat with the integrated or standalone database first."

WebGoat is running fine and I can log in.

**Comment by zubcevic** [comment]
In the latest develop branch there is no separate jars for web goat and web wolf. It is all in one. See the README
