### ISSUE TITLE
 Issues in Running from the sources

### ISSUE THREAD

**Issue by shahad7z** [WebGoat/WebGoat#1262]
I have cloned the Webgoat in my terminal: https://github.com/WebGoat/WebGoat.git

then I entered:

cd WebGoat

./mvnw clean install 

./mvnw spring-boot:run

Then I Open it in my IDE it's  Open perfectly and I can run the application. then I click the link for WebWoilf and it's open in port 9090 and I can sign in with the same username in WebGoat.

But the problem is I can't receive any email in WebWoilf and Incoming requests from Webgoat, why? did I miss something?

**Comment by zubcevic** [comment]
I do not see any issues with this. Are you using: http://127.0.0.1:8080/WebGoat/
and are sending emails from WebGoat to webwolf using yourusername@webgoat.org ?
