### ISSUE TITLE
unable to access webgoat from remote ip address sometimes, it woks sometime but does not work for the next try

### ISSUE THREAD

**Issue by bhtriffler** [WebGoat/WebGoat#1263]
java -jar webgoat-server-8.0.0.M26.jar –server.address=0.0.0.0
this is the command i have used and it worked first time when navigated to http://my ip addresss:8080/WebGoat
now this is not working and webgoat is listening on localhost
can anybody suggest a solution??
i'm using webgoat for learning purpose and this issue is hindering the flow, pls help

**Comment by aolle** [comment]
Hi, please elaborate; what do you mean that it is not working? Can you share with us the bootstrapping log traces?

**Comment by zubcevic** [comment]
Please follow the instructions from the more recent develop branch or the wiki.
