### ISSUE TITLE
The system cannot find the path specified. Error Message, need help.

### ISSUE THREAD

**Issue by HannahAboh** [WebGoat/WebGoat#1267]

**Comment by aolle** [comment]
Please, follow the instructions from the README and elaborate.

**Comment by HannahAboh** [comment]
> Please, follow the instructions from the README and elaborate.

Okay I am trying to link Java and WebGoat but on cmb I keep getting this error message 
C:\>cd WebGoat
The system cannot find the path specified.

**Comment by aolle** [comment]
Well, this is not an error related to WebGoat, be sure that location exist.
