### ISSUE TITLE
Error when installing from sources on Windows 10

### ISSUE THREAD

**Issue by DenverDaveH** [WebGoat/WebGoat#1281]
>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\me\Downloads\apache-maven-3.6.3-bin\apache-maven-3.6.3\bin\..
Java version: 17.0.2, vendor: Eclipse Adoptium, runtime: C:\SAClient\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows

git checkout v8.2.2

running:
mvnw.cmd clean install

Throws this error: 
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc (output-html) on project cross-site-scripting: Execution output-html of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.3:process-asciidoc failed: (LoadError) load error: jruby/java/java_ext/java.lang -- java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @34e2c98d -> [Help 1]

Please let me know what I need to do to resolve this?
Thanks
Dave

**Comment by zubcevic** [comment]
As you can see from the README and the https://github.com/WebGoat/WebGoat/wiki/Developer-Getting-Started guide and the maven-wrapper.properties you need Maven 3.8+

**Comment by micwoj92** [comment]
I'm getting almost the same error using maven 3.8.6.
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/maven
Java version: 18.0.2, vendor: N/A, runtime: /usr/lib/jvm/java-18-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.18.16-arch1-1", arch: "amd64", family: "unix"
```

**Comment by Rebick** [comment]
Solved installing maven
