### ISSUE TITLE
Web Wolf on a separate VM

### ISSUE THREAD

**Issue by Gobo42** [WebGoat/WebGoat#1319]
Hi. I'm running Webgoat and WebWolf on separate VMs in order to run some tests on a WAF and other network security devices. I'm running the latest java jars as standalone images. I got WebGoat running on one server successfully, but when I try to run webwolf I continually get the error: `It seems that the required database is not running. Please start WebGoat with the integrated or standalone database first.`

I have tried searching though various options and documentaton and tried a number of different commands to initiate WebWolf. From what I gathered the latest I have tried is:
`java -Djava.security.egd=file:/dev/random -jar webwolf-8.2.2.jar --spring.datasource.url=jdbc:hsqldb:hsql://192.168.122.129:9001/webgoat --server.address=0.0.0.0 --server.port=9090 --webgoat.start.hsqldb=false`
as well as various different versions of this. Is there a command line option to indicate that the DB server is running correctly on a different server? Is there a way I can point webgoat and webwolf to an external hsql server on a 3rd server?

**Comment by zubcevic** [comment]
It is not really designed to run on multiple vm’s. It is possible to use different hostnames etc. The latest develop version is now a single jar that contains webgoat and webwolf in one.

**Comment by zubcevic** [comment]
This repo shows a setup in openshift with seperate host names for webgoat and webwolf and an entry point for webgoat behind a waf
