### ISSUE TITLE
(A1) Hijack a session has a bug!

### ISSUE THREAD

**Issue by wanan-love** [WebGoat/WebGoat#1327]
A vulnerability in which code is expected to fail to complete the course.

![图片](https://wanan-1310031509.cos.ap-beijing.myqcloud.com/187027802-204dace2-69a7-4eec-8b0b-7bcbf64b3600.png)

![image-20220827191840133](https://wanan-1310031509.cos.ap-beijing.myqcloud.com/image-20220827191840133.png)

I guess "Authenticated" expectation here should return true,but false is returned.

![image-20220827192311013](https://wanan-1310031509.cos.ap-beijing.myqcloud.com/image-20220827192311013.png)

I changed the code to return true

**Comment by aolle** [comment]
Hello,

thank you for submitting the issue and the debugger screenshots.

Unfortunately, it's not enough to confirm that there is a bug. Please, elaborate the issue, share with us a concrete scenario and flow that is not working on your side.

Please, note that the authentication provider of this lesson **simulates** that there are other users logging in.

I saw in your changes that you're using Authentication object as an output argument and returned at same time but not cached. I would like to avoid modifying the status of the scoped object in an autologin method.

Regards.

**Comment by wanan-love** [comment]
Thank you for your reply, I may not have fully understood the procedure
