### ISSUE TITLE
Insecure Direct Object References(5). The prompt does not match the code.

### ISSUE THREAD

**Issue by wanan0red** [WebGoat/WebGoat#1329]
![图片](https://user-images.githubusercontent.com/94047894/187705043-a7833a89-a2c1-4fdd-93d7-394a24b737f3.png)
I see that the prompt here is failure, but the code is correct. Is this normal?

**Comment by wanan-love** [comment]
![图片](https://user-images.githubusercontent.com/94047894/187718176-8102d348-9a44-4e32-9fb1-9e03cacc31e7.png)
There's another problem if I pass in JSON data "userId":   null ,  In the following "else if" will appear "java.lang.NullPointerException". Is there any way to pass SUCCESS below

**Comment by aolle** [comment]
Found more issues in this lesson, like:

jakarta.servlet.ServletException: Request processing failed: org.springframework.context.NoSuchMessageException: No message found under code 'an error occurred with your request' for locale 'en_US'.

**Comment by aolle** [comment]
Fixed in #1527
