### ISSUE TITLE
hints are not refreshed when switching lessons

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#133]
Pick a random lesson, click the hints button then choose another lesson from the menu. The hints from the previous lesson stay visible.

<img width="477" alt="capture1" src="https://cloud.githubusercontent.com/assets/493861/10743858/10bceca2-7c36-11e5-80b2-6366f834f0b5.PNG">
<img width="489" alt="capture2" src="https://cloud.githubusercontent.com/assets/493861/10743859/111a32cc-7c36-11e5-959f-a46bf152cae9.PNG">

**Comment by misfir3** [comment]
pull request in to fix this ... close once verified.

**Comment by nbaars** [comment]
Tested and works, closing the issue
