### ISSUE TITLE
g.owasp.webgoat.sql_injection.introduction.SqlInjectionLesson5 : unexpected token: TABLE required: TO Your query was: GRANT ALTER TABLE TO unauthorized_user

### ISSUE THREAD

**Issue by vimal942** [WebGoat/WebGoat#1346]

**Comment by vimal942** [comment]
g.owasp.webgoat.sql_injection.introduction.SqlInjectionLesson5 : unexpected token: TABLE required: TO Your query was: GRANT ALTER TABLE TO unauthorized_user

**Comment by aolle** [comment]
Please, elaborate the issue.
