### ISSUE TITLE
I can't start WebGoat in windows 11

### ISSUE THREAD

**Issue by biyvutcyrxge** [WebGoat/WebGoat#1351]
I can not install webgoat on my windows 11 ( 21h2 ). I have java 16.0.2 on it. Every time I run the start commands, it just tells is can't access the java file.
![image](https://user-images.githubusercontent.com/116472791/197370577-92c5ac08-bc85-445a-882f-53402c2688e5.png)

**Comment by aolle** [comment]
You are trying to execute the webgoat-8.2.3.jar file, but I am seeing that the jar file that you have is the webgoat-server-8.2.2.jar.
Try starting it specifying that jar filename.
