### ISSUE TITLE
Lessons are missing with latest Docker image on OSX

### ISSUE THREAD

**Issue by rasliche** [WebGoat/WebGoat#1356]
Really not sure what details might be relevant here, this seemed to happen in our school computer lab. I'm not a Java developer so I'm not sure what warnings or errors I should be looking for. I'm trying to do an assignment for the Authentication Flaws -> Multi Level Login 2 challenge.

My Webgoat instance only shows A1, A2, A3, A6-A10. Where are 4 and 5?

Can I manually open them somehow?

![Screenshot 2022-11-12 at 3 54 19 PM](https://user-images.githubusercontent.com/143391/201494160-0ebbb02f-246d-4187-b414-470998039c93.png)

**Comment by nbaars** [comment]
At the moment we don't have any lessons specific for this category. That is the reason why they are not displayed.
The lessons `Multi Level Login 2 challenge.` is part of WebGoat 7, we did not port this lesson to WebGoat 8. We do have some other lessons regarding authentication below category A7.
