### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by dougmorato** [WebGoat/WebGoat#139]
Upon loading start.mvc, there are errors reported for these 2 locations:

1. http://localhost:8080/WebGoat/js/libs/jquery-1.10.2.min.map
2. http://localhost:8080/WebGoat/js/libs/underscore-min.map

I am assuming those are not necessary and could be removed?

**Comment by misfir3** [comment]
Seef this here:
http://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found
I'd vote to remove the line with:
//@ sourceMappingURL

**Comment by misfir3** [comment]
Not sure when, but the commenting was implemented ... closing.
