### ISSUE TITLE
Broken access control - (Missing Function Level Access Control lab), keeps returning error for user hash

### ISSUE THREAD

**Issue by jimmyFlash** [WebGoat/WebGoat#1395]
On **v 2023.3**
Lab 4 ( Missing Function Level Access Control lab )
i managed to pull the users/hashes list by changing the GET request for `/WebGoat/access-control/users`  adding `Content-Type: application/json`
Got the list of users (Jerry, Tom .... ) with hashes including mine, yet when i input my logged in user hash, i keep getting error that i should try again, i even tried all the hashes in the list and was still getting error

> Keep trying, this one may take several attempts & steps to achieve. See the hints for help.

Am i missing something, because there a lot of solutions online following the same method and it's even mentioned in the hints for the lesson.
I downloaded WebGoat image from docker hub

**Comment by ObviouslyAk** [comment]
hello, just copy this code and run it to generate the new hash. 
https://pastebin.ubuntu.com/p/QkTryMDCqs/

**Comment by jimmyFlash** [comment]
> hello, just copy this code and run it to generate the new hash. https://pastebin.ubuntu.com/p/QkTryMDCqs/

Just to iterate:
You're saying copy the code it into any java IDE and compile it, copy the output hash and use it solve the challenge?

**Comment by aolle** [comment]
I have tested the lesson several times, and it works correctly. Please note that the hash to be entered is that of the user requesting the statement.
I'm closing the issue.
