### ISSUE TITLE
how to up webgoat to netbeans on mac os x.

### ISSUE THREAD

**Issue by freetest** [WebGoat/WebGoat#14]
hello~
i want to use netbeans IDE built webgoat on mac os x .  how can i do it?

➜  ~  brew install maven
==> Downloading http://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.2.3/bi
==> Best Mirror http://mirror.bit.edu.cn/apache/maven/maven-3/3.2.3/binaries/apa

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "maven"
Download failed: http://mirror.bit.edu.cn/apache/maven/maven-3/3.2.3/binaries/apache-maven-3.2.3-bin.tar.gz

**Comment by nbaars** [comment]
Can you try `brew update` first before you do a `brew install maven`?

--Nanne
