### ISSUE TITLE
ChallengeIntegrationTest fails some times

### ISSUE THREAD

**Issue by aolle** [WebGoat/WebGoat#1407]
The ChallengeIntegrationTest is failing some times.

**Comment by nbaars** [comment]
I ran into the same issue, think I fixed it locally but not sure because it sometimes happens

**Comment by aolle** [comment]
Hi @nbaars , is the #1416 related to this issue ?

**Comment by nbaars** [comment]
Yes, I think so. Seems solved now 🙏

**Comment by nbaars** [comment]
And it fails :-)

**Comment by nbaars** [comment]
It does not fail anymore, I think due to a change to explicitly pass the lesson name and flag to the backend
