### ISSUE TITLE
Stored XSS Lesson does not render message and attack does not fire

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#141]
The message is created, but clicking on the message does not render the content. The attack can't fire without the content being rendered.  The Message should show below the message list with a line separator.

 This is from Firefox, Chrome, and Safari

![screen shot 2015-10-29 at 8 46 50 am](https://cloud.githubusercontent.com/assets/3689202/10818662/c60342d4-7e19-11e5-946b-9b77b4dfb775.png)

**Comment by nbaars** [comment]
Seems to be the same with Cross Site Request Forgery (CSRF) lesson

**Comment by misfir3** [comment]
Verified fixed ...
![alertstoredxss1](https://cloud.githubusercontent.com/assets/5103241/11541250/36ce7ff6-98ff-11e5-8daa-931f64d8c98d.png)

![storedxss2](https://cloud.githubusercontent.com/assets/5103241/11541255/3db97474-98ff-11e5-8368-0e67439aa349.png)

**Comment by nbaars** [comment]
Tested indeed I see the alert but the lesson does not show that the lesson has been successfully completed.

**Comment by misfir3** [comment]
'success' criteria in java file was not 'loose' enough.  Plenty of successful ways may still not get picked up, but at least you can now succeed using the inputs from the hints. Merge request in.
