### ISSUE TITLE
webgoat-2023.4.jar can not run 

### ISSUE THREAD

**Issue by gjm-anban** [WebGoat/WebGoat#1434]
I download webgoat-2023.4.jar in release and run the following command
java -Dfile.encoding=UTF-8 -Dwebgoat.port=8080 -Dwebwolf.port=9090 -jar webgoat-2023.4.jar

it can't run and report error 
![image](https://user-images.githubusercontent.com/73465248/220839331-edccd7a3-b8d0-4660-8b36-c602edcae5dd.png)

**Comment by gjm-anban** [comment]
> @gjm-anban that's interesting. Can you see if the directory is actually created on the filesystem? `/root/.webgoat-2023.4`

directory is exist, file not exist
![image](https://user-images.githubusercontent.com/73465248/221555754-ed05c64b-9752-4964-bc6f-9a4db7e0df10.png)

**Comment by aolle** [comment]
the directory is not the same as appearing in the log. Please, note that's a hidden dir, share the output of `ls -a` instead.

**Comment by gjm-anban** [comment]
> the directory is not the same as appearing in the log. Please, note that's a hidden dir, share the output of `ls -a` instead.

![image](https://user-images.githubusercontent.com/73465248/221729863-e6b216fd-070c-4f57-b6ee-0d8c33dc264d.png)
