### ISSUE TITLE
File upload does not work for lesson Malicious File Execution 

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#144]
The upload button does not seem to work.

Environment: Windows
Browser: Firefox

**Comment by nbaars** [comment]
@misfir3 this lesson needs to upload a file. It uses multipart content to check this, this method does not return `true` unless you use a `POST` method however in `LessonContentView.js` there is a function:

```
 makeFormsAjax: function () {
            var options = {
                success:this.reLoadView.bind(this),
                url: this.model.urlRoot,
                type:'GET'
                // $.ajax options can be used here too, for example: 
                //timeout:   3000 
            };
            //hook forms //TODO: clarify form selectors later
            $("form").ajaxForm(options);
        },
```

which seems to turn everything into a GET, however the file upload lesson needs a POST. I changed this to a POST lessons still seem to work and also this lesson works again. 
Can we change this `type: GET` to `POST` instead? For the server part is does not matter.

**Comment by misfir3** [comment]
Good find.  I have an idea to fix this that will provide us some flexibility in the future and not jeapordize breaking other existing lessons. Will put this on the top of the pile.

**Comment by misfir3** [comment]
@nbaars  my idea is to have a property set (optionally) in the plugin to determine the method and then provide a method in AbstractLesson to fetch it. I started to use the existing WebGoatLabels.properties/labelManager as an easy starter. So I created a ...
plugin/i18n/WebGoatLabels.properties in that lesson and added
```
submitMethod=POST
```
The idea is I'll pull it via the LessonInfoService and propagate through the client.

Issues is I'm getting
```
submitMethod:POSTErrorGenerating=ErrorGenerating
```
Going to look at it a little more later, but welcome your input/help on it (extending or creating a new general-purpose properties utility in the plugins)

**Comment by nbaars** [comment]
@misfir3 the `ErrorGenerating=ErrorGenerating` is probably part of another `i18n/WebGoatLabels.properties` all the separate files are loaded and passed to a Spring resource loader, maybe just a guess can it have something to do with a missing newline?

**Comment by misfir3** [comment]
@nbaars  Appears it was initially a missing newline. haven't had time to go back and finish the solution now.  Once done, lesson auhtors will be able to alter the method for a given lesson by filling in submitMethod=_METHOD_ in the WebGoatLabels.properties file.  Maybe we should change that to WebGoatLesson.properies in the long run.

**Comment by misfir3** [comment]
have the override working locally for this lesson. Going to update the hints first, then push it all up.

**Comment by misfir3** [comment]
@nbaars we can close this, right?

**Comment by vdbaan** [comment]
It appears that start.mvc does not forward the request to the lesson, which results in that this lesson does not receive the file at all. Even when you change the form to a post.

**Comment by felipedeboni** [comment]
This is how I fixed:

![image](https://cloud.githubusercontent.com/assets/735836/14662340/80be48c2-068b-11e6-9295-ae828e3b2f94.png)

**Comment by nbaars** [comment]
Applied the fix above provided by @felipedeboni
