### ISSUE TITLE
WebGoat does not start in Docker Linux desktop

### ISSUE THREAD

**Issue by TobiasAsk** [WebGoat/WebGoat#1455]
I ran 
```
docker run -p 127.0.0.1:3000:3000 webgoat/webgoat-desktop
```
and navigated to http://localhost:3000/ in my local browser to access the machine. When I run the ~/start_webgoat.sh script it fails to start the app and exits with the following error:
![image](https://user-images.githubusercontent.com/10739403/225429160-a432c0bc-0c8f-4594-89fd-b4095f7be0c8.png)

**Comment by zubcevic** [comment]
I am using podman on a macbook with Intel processor and get another message:
cannot execute binary file exec format error
