### ISSUE TITLE
Nightly build doesn't run

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#150]
When download loading the snapshot build, WebGoat doesn't start.

java -jar webgoat-container-7.0-SNAPSHOT-war-exec.jar
Nov 24, 2015 4:46:22 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Nov 24, 2015 4:46:22 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Nov 24, 2015 4:46:22 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.59
Nov 24, 2015 4:46:23 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]

404 - when browsing to WebGoat

**Comment by ilatypov** [comment]
Wasn't this "container" only a pre-requisite to be installed into a local Maven cache and used when running WebGoat-Lessons?

**Comment by mayhew64** [comment]
Probably need to dig into this a bit deeper but changing the scope of maven-jar-plugin back to the compile phase fixed the creation of the war-exec.jar
