### ISSUE TITLE
Add gradle files

### ISSUE THREAD

**Issue by doughoke** [WebGoat/WebGoat#1516]
Would anyone object to me adding gradle files along with pom files (maven)?  I ask because I leverage webgoat to test out SCA tools from time to time. Of course I can fork this wonderful project and keep my own version however I would like to see what others think.

**Comment by zubcevic** [comment]
I think it might cause some additional work to keep both gradle and maven in sync and completely the same. As for the build and release process through GitHub Actions one of the two will be used.
You could also leverage those tools through maven, right?

**Comment by nbaars** [comment]
I agree with @zubcevic, both have their pros and cons. We do have some extensive setups in Maven for the integration tests. It works and the build time is around 54 seconds which I'm quite happy with. I'm not against migrating to Gradle but it should in the end do exactly the same and we should go for a full migration to Gradle, and not support both that would be a maintenance problem.

**Comment by aolle** [comment]
@nbaars @zubcevic I think we can close this issue, do you agree?
