### ISSUE TITLE
Cannot invoke "javax.tools.JavaCompiler.getStandardFileManager ..." because "compiler" is null

### ISSUE THREAD

**Issue by jimmyFlash** [WebGoat/WebGoat#1544]
**WebGoat version :  2023.3 ( Docker image )**
**Lab 6 - SQL Injection (mitigation)** 

While working on this lab i had written the code below:

```
String query = "SELECT first_name, last_name FROM users WHERE first_name = ?";
String name = "Kratos";
String data = null;


try {
    Connection conn = DriverManager.getConnection(DBURL, DBUSER, DBPW);
    PreparedStatement statement = conn.prepareStatement(query);
    statement.setString(1, name);
    
    ResultSet results = statement.executeQuery();
    if (results != null) {
        
        data = "Success";
    }
    
} catch (Exception e) {
    System.out.println("Oops. Something went wrong!");
}

return data;
```

When submitting the above code to solve the lab i get the error below:

```
Cannot invoke "javax.tools.JavaCompiler.getStandardFileManager(javax.tools.DiagnosticListener, java.util.Locale, java.nio.charset.Charset)" because "compiler" is null
```

I don't think this is related to the code I've written but appreciate if someone can point out why i'm seeing this although the code is similar to code samples from previous labs.

**Comment by jimmyFlash** [comment]
Hello @aolle 

As i mentioned this issue occurred with the Docker image, i didn't face such issue when i cloned and earlier version of WebGoat straight from GitHub. This is my 1st time using WebGoat docker image from DockerHub

I will remove the return statement form my code as you did and test,  not sure this is the cause but hope it work.

I'll attach screens of the error  message if I'm still getting the same error.

**Comment by jordithijsman** [comment]
This is a legit issue. It is reproducible by running the Docker image.

I suspect the cause is the usage of the `docker.io/eclipse-temurin:19-jre-focal` base image for the container is to blame. This exercise tries to use JDK functionality which is not included in the JRE. While this is good practice for a secure application since it limits the attack surface, the JDK appears to be a necessity for this exercise.

I tried building the image using `docker.io/eclipse-temurin:19-jdk-focal` and this appears to fix the issue.

**Comment by jimmyFlash** [comment]
> This is a legit issue. It is reproducible by running the Docker image.
> 
> I suspect the cause is the usage of the `docker.io/eclipse-temurin:19-jre-focal` base image for the container is to blame. This exercise tries to use JDK functionality which is not included in the JRE. While this is good practice for a secure application since it limits the attack surface, the JDK appears to be a necessity for this exercise.
> 
> I tried building the image using `docker.io/eclipse-temurin:19-jdk-focal` and this appears to fix the issue.

Thank you so much @jordithijsman. The script was simple enough i tried in sample app with with JDK11 and SQLite db and it was working, had a feeling it was docker image but couldn't figure out what exactly should i look for.

**Comment by James-Lu-none** [comment]
i replaced the image with docker.io/eclipse-temurin:19-jdk-focal but it still shows "compiler" is null when i was trying to submit the anwser, do i have to replace something other than the FROM statement in the docker file?

**Comment by James-Lu-none** [comment]
oh you are right, i am new to docker and i thought it will build the image for me when i do docker run.
