### ISSUE TITLE
icon image is not upto date.

### ISSUE THREAD

**Issue by vishwas-babar** [WebGoat/WebGoat#1557]
before "WebGoat Loag" there is image but this image not looking due to changes in image remote position.
![issue](https://github.com/WebGoat/WebGoat/assets/116264015/b03082cd-2fcb-4fb6-a956-7b3653f803cb)

so please someone remove it or add icon there.
![issue1](https://github.com/WebGoat/WebGoat/assets/116264015/326a1df2-338b-458e-ba56-faa354f17431)

**Comment by nbaars** [comment]
Fixed, the `develop` branch no longer exists updated the link

**Comment by vishwas-babar** [comment]
i finded this issue for myself but you already solved it. should you tell me how you find this icon code in this codebase ?

when i searched it in vscode whole files it showing no changes found.
