### ISSUE TITLE
Command Injection Issue WebGoat 7

### ISSUE THREAD

**Issue by UnChallengeD** [WebGoat/WebGoat#156]
Hi there,
I'm running WebGoat 7 on Ubuntu(VMware) with this command
java -jar webgoat-container-7.0-SNAPSHOT-war-exec.jar
on command injection page i cannot change to any other help file
you can see in the picture.
i just want to make sure this is not a bug? is it?

![webgoatx](https://cloud.githubusercontent.com/assets/6654061/11698129/0828c55e-9edf-11e5-8aca-c1f10041506f.jpg)
thanks..

**Comment by ilatypov** [comment]
Indeed, plugin_extracted/plugin/CommandInjection will contain only lessonPlans and lessonSolutions.  The directory "resources" added to the path in CommandInjection.java appears out of sync with some later change.  "BasicAuthentication.help" shows up as a default value of the absent parameter.

**Comment by nbaars** [comment]
Issue found build step for copying the html files occurred too late

**Comment by nbaars** [comment]
Available as a pull request, can you review and merge the pull request to master?
