### ISSUE TITLE
Update OWASP Wiki WebGoat page

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#159]
Page at https://www.owasp.org/index.php/Category:OWASP_WebGoat_Project needs some more updating. Namely ...
- add Nanne and Jason as project leads with Bruce 
- Update getting started section (still points to 5.4 docs), should point to github.io/WebGoat
- Something about the plug-in architecture
- Something general about current plans/activity

**Comment by misfir3** [comment]
@nbaars - I listed you as a project lead, but didn't attach an email to it. Let me know if you want an email address on there (and if so, what you want there)

**Comment by nbaars** [comment]
@misfir3 as my e-mail address you can use nanneb@gmail.com
I looked at the page but my lastname is not correct, can you change my last name to Baars instead Bars? 

Thanks,
--Nanne

**Comment by misfir3** [comment]
@nbaars Wow ... can't believe I botched that, sorry! Will update it a bit later.

**Comment by misfir3** [comment]
finally updated Nanne's info ... only a month later, sheesh!
