### ISSUE TITLE
Provide Async error handling

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#160]
Right now, async response error handling is virtually nil. Need to handle responses for common errors ..
- 404
- 403
- 500
- ... others?

**Comment by misfir3** [comment]
May be a good issue for new devs coming on to try their hand at

**Comment by zupzup** [comment]
I'd like to take this if that's ok

**Comment by misfir3** [comment]
Sure ... some more specifics
* If an existing page calls in and gets the response for not authenticated, we want to redirect _top to the main login page.
* For the others, provide an appropriate message.  I'd prefer a 'toaster' type message over an alert/dialog, but dialog on first pass is OK.
