### ISSUE TITLE
Doesn't run with tomcat8

### ISSUE THREAD

**Issue by fanofun** [WebGoat/WebGoat#161]
I depolyed WebGoat to tomcat8 but when I tried to log in, it says "invalid Session". I found the problem is in WebGoat/WebGoat/webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginsLoader.java.
Tomcat 8 doesn't support setAntiJARLocking() and addRepository() anymore. But I don't know how to fix it.

**Comment by nbaars** [comment]
See #233 it will by default run on Tomcat 8.

**Comment by nbaars** [comment]
webgoat-container does not exist anymore so with the next 7.1 release this issue is no longer present. Will need to test the Tomcat 8 workings

**Comment by nbaars** [comment]
Also in version 7.1 (fix release) we do not use this API anymore. So it should run on Tomcat 8. (see branch feature/portnumber)
