### ISSUE TITLE
Insecure deserialization time zone issue

### ISSUE THREAD

**Issue by jordithijsman** [WebGoat/WebGoat#1674]
This issue is present in the Docker version of WebGoat.

On [line 53](https://github.com/WebGoat/WebGoat/blob/d6c4e8e454d1072825d00bf1dddb6615fc3bd0c2/src/main/java/org/dummy/insecure/framework/VulnerableTaskHolder.java#L53) the VulnurableTaskHolder checks the freshness of the serialized object versus the system clock. When creating a Docker image, the default timezone is set to UTC. Users in different timezones might not be aware of this causing the TaskHolder to falsely flag the answer as an old one.

Possible solutions:
- Mention the server time (UTC) somewhere so the user can adjust his requestedExecutionTime variable accordingly.
- Encourage the user (in the readme) to set the timezone using the TZ environment variable when running the container.

**Comment by zubcevic** [comment]
It is described on the accompanying wiki pages, but I guess it is good to highlight it more in the documentation

**Comment by zubcevic** [comment]
it is now mentioned on the  main README
