### ISSUE TITLE
CSRF lessons work but feedback to user about successfully completing the lesson can be improved

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#169]
Both lesson CSRF and prompt by pass work but the feedback to the user can be improved. As a user you will not immediately notice the comment in red stating: "Congratulation etc."
But the green checkbox in the menu will appear.

Prompt-by-pass shows the remark in the preview but unfortunately not in red.

**Comment by span** [comment]
This was more tricky then I thought at a first glance. I think the goal really should be to get the red text displayed as soon as the lesson finishes. I'm not sure on how to do this at the moment and I will dig some more into it. 

I suppose it would be nice if all three CSRF lessons could decide on success in the same or at least a similar way.

Some ideas:
* Return a script/message that loads the contents for the lesson through the javascript controller
* Check contents of the submitted message before returning it and display the red success text in it
* Something else...

**Comment by nbaars** [comment]
Indeed was looking into this one as well. Clicking the link triggers the page to be reloaded (first time you enter the lesson) then the image gets loaded (which also hits the lesson) and marks it as completed. However lesson content in the JavaScript is already reloaded and the div for the "Congratulation" message is not there because the lesson is not marked as completed when the first call happened. The JavaScript processes the results of the first call.

The menu is triggered again after the image link has been loaded so that's why the menu does get updated.

**Comment by nbaars** [comment]
Working on separating the "Congratulation" message into a separate call (makes it more conform the SPA working of WebGoat)

**Comment by span** [comment]
Yes, either a separate call or to include a check in the first request that fetches the Message from the database. Making it part of the initial request would simplify the flow although it might cause issues with validating the exact command.

**Comment by nbaars** [comment]
Fixed, waiting for pull request to get merged.
