### ISSUE TITLE
Move to Java 21

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#1694]
Since this release is now out, we should update. This includes:

- pom.xml
- add enforcer rules
- update all Github actions
- update Dockerfile

**Comment by zubcevic** [comment]
Hi the Docker base image was already set to Java 21. I see you changed it to the temurin JRE version. But that will prevent solving the solution where your code gets compiled. See https://github.com/WebGoat/WebGoat/pull/1677 comments

**Comment by nbaars** [comment]
The release failed, due to missing ARM image not sure if that really was the issue though. Will fix it

**Comment by zubcevic** [comment]
I updated the pom GitHub flows and docker images. So they should be ok now for all scenario's
