### ISSUE TITLE
Session Fixation link in stage 2 does not work

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#170]
The link points to http://localhost:8080/webgoat/#attack/71/1800&SID=WHATEVER which shows a blank page when you click it.

**Comment by misfir3** [comment]
I'll take a look, the router is incorrectly catching (or not catching it) it would appear ... should be able to get it to handle/parse the & in the parameters

**Comment by nbaars** [comment]
Was looking into the issue but if I put the url in the location bar (instead of clicking the link) I'm able to proceed to the next stage

**Comment by misfir3** [comment]
it's generating a 404 from the link ... will see why the router can't parse it and find a way to make it work

**Comment by misfir3** [comment]
In SessionFixation.java ... we have
```"data:<br><br><center><a href=/webgoat/"```
That explains the 404. Will fix that and see where it goes from there

**Comment by misfir3** [comment]
believe this is stale ... closing
