### ISSUE TITLE
Redirect localhost:8080 to localhost:8080/WebGoat

### ISSUE THREAD

**Issue by kidmose** [WebGoat/WebGoat#173]
I spent a while figuring why nothing happened when I pointed my browser to localhost:8080, before realizing that webgoat runs on localhost:8080/WebGoat and not on the root. 

I propose changing this such that getting started with WebGoat is easier.

    dkegokid@dkegokid-VirtualBox ~ $ uname -a
    Linux dkegokid-VirtualBox 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    dkegokid@dkegokid-VirtualBox ~ $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	LinuxMint
    Description:	Linux Mint 17.2 Rafaela
    Release:	17.2
    Codename:	rafaela
    dkegokid@dkegokid-VirtualBox ~ $

**Comment by nbaars** [comment]
Everything links toward /WebGoat, so I've added the link from the documentation as well to the console output. So starting of the exec.jar will show the url to open at the bottom when starting.
