### ISSUE TITLE
Backdoor lesson breaks menu CSS

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#175]
The backdoor lesson seems to break the menu margins for the LI-items. The lesson includes som inline CSS that targets `LI: margin-top: 10pt`. This causes the LI's in the menu on the left to get an extra margin of 10pt.

<img width="1371" alt="screen shot 2016-01-29 at 13 06 28" src="https://cloud.githubusercontent.com/assets/502136/12675252/2f21e0ce-c689-11e5-8322-b1452c873526.png">

Tested in Chrome on OS X.

**Comment by span** [comment]
Merged in webgoat/webgoat-lessons#50.

**Comment by jlauire** [comment]
I need help
Im trying to follow video to reset email password i dont have access to the backups
