### ISSUE TITLE
Dockerfile failed to build

### ISSUE THREAD

**Issue by nikgreg99** [WebGoat/WebGoat#1761]
I have tried to buil the dockerfile on own  and I obtain this error:

 => [2/4] RUN   useradd -ms /bin/bash webgoat &&   chgrp -R 0 /home/webgoat &&   chmod -R g=u /home/webgoat        0.9s
 => ERROR [3/4] COPY --chown=webgoat target/webgoat-*.jar /home/webgoat/webgoat.jar                                0.0s
------
 > [3/4] COPY --chown=webgoat target/webgoat-*.jar /home/webgoat/webgoat.jar:
------
Dockerfile:12
--------------------
  10 |     USER webgoat
  11 |
  12 | >>> COPY --chown=webgoat target/webgoat-*.jar /home/webgoat/webgoat.jar
  13 |
  14 |     EXPOSE 8080
--------------------
ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount1803861932/target: no such file or directory

I am using a Win 11 machine

**Comment by zubcevic** [comment]
Did you do a mvn clean install before the docker build?
