### ISSUE TITLE
How to create a Legacy Lesson - instruction edit

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#177]
Existing text:

Lesson are simple to create and very little coding is required.   In fact, most lessons can be created by following the easy to use instructions in the **WebGoat User Guide**.  If you would prefer, send your lesson ideas to **webgoat@owasp.org**

Changes Needed: 

- Change the WebGoat User Guide" to point to the wiki
- Change the webgoat@owasp.org to the group mailing list
- Add some test to file an enhancement issue with the idea

**Comment by b1rd0fb3auty14** [comment]
I can work on this.

**Comment by b1rd0fb3auty14** [comment]
Hello @mayhew64 what is the group mailing list? Also, is this documentation inside the code, and if so, where? Thanks!

**Comment by b1rd0fb3auty14** [comment]
Hey @mayhew64 - can you please answer the questions above? Thanks.

**Comment by mayhew64** [comment]
Thanks for the shout.  Seriously. 

The list is: owasp-webgoat@lists.owasp.org it requires registration so we may want to add some words about that. Registration is at: https://lists.owasp.org/mailman/listinfo/owasp-webgoat

The how to create a lesson is loaded from the lesson plans (I'm going from memory) so it should be in the lesson plans folder for that lesson.   

We also might want to add the OWASP WebGoat slack channel.  To register: https://owasp.slack.com/

**Comment by mayhew64** [comment]
And thanks for the help!

**Comment by b1rd0fb3auty14** [comment]
You're welcome! I have one more question @mayhew64 -  what is the address of the wiki?

**Comment by mayhew64** [comment]
https://github.com/WebGoat/WebGoat/wiki

**Comment by b1rd0fb3auty14** [comment]
Hey @mayhew64 - I have made the changes in the following files: LessonAdapter.java to change the verbiage and WebgoatContext.java to change the feedbackAddressHTML. I want to test to make sure everything is working, can you guide me on how I can do this? Or point me to the document that will tell me this?

**Comment by b1rd0fb3auty14** [comment]
Sorry - I was confused about this: **Add some test to file an enhancement issue with the idea** - what do I need to do with this? @mayhew64

**Comment by mayhew64** [comment]
@nbaars Can you elaborate on test expectations

**Comment by b1rd0fb3auty14** [comment]
@mayhew64 @nbaars - I created a pull request for this issue. Please review when able. Thanks!

**Comment by b1rd0fb3auty14** [comment]
@mayhew64 @nbaars @span I have created the following pull request --> https://github.com/b1rd0fb3auty14/WebGoat/pull/1

Please review when able. Thanks!

**Comment by span** [comment]
Commit looks ok to me at a glance. Nice work!

@b1rd0fb3auty14 I think you accidently created a PR at your own repo instead of at the webgoat repo. Could you submit a new PR aimed at the WebGoat repo? (See https://github.com/WebGoat/WebGoat/issues/231#issuecomment-228190202 for details)

**Comment by b1rd0fb3auty14** [comment]
Hey @span - sorry for the late response. I've had an eventful week.

Below is the pull request link: https://github.com/WebGoat/WebGoat/pull/245

Let me know if there are any questions and/or concerns. Thanks!
