### ISSUE TITLE
How to run WebWolf on different port ?

### ISSUE THREAD

**Issue by harmin-parra** [WebGoat/WebGoat#1788]
WebGoat fails to start because my computer is already using port 9090

how to set a different port for WebWolf ?

**Comment by siblount** [comment]
For the jar file, try passing in the arg `--webgoat.port=[YOUR_PORT]`. You can see the other available args [here](https://github.com/WebGoat/WebGoat/blob/e308d7cde7f3c6f50016a7548f078fe481d5de8e/src/main/resources/application-webgoat.properties#L8C1-L8C13).
