### ISSUE TITLE
Injection Flaws -> Limit Command Injection success to a set of commands and clarify this to the user

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#179]
It seems the command injection lesson is too strict and does only get marked as "complete" when the command has been executed with exit status 0. 

On OS X for example the injection `" ; whoami #` returns 0 and completes the lesson with the command:

> ExecResults for '[/bin/sh, -c, cat "/Users/daniel-op/security/WebGoat/webgoat-container/target/webgoat-container-7.0-SNAPSHOT/plugin_extracted/plugin/CommandInjection/resources/ChallengeScreen.html" ; whoami #"]'

The command `" ; whoami ; "` returns exit code 127 and does not complete the lesson although the injection works and prints the system user name.

> ExecResults for '[/bin/sh, -c, cat "/Users/daniel-op/security/WebGoat/webgoat-container/target/webgoat-container-7.0-SNAPSHOT/plugin_extracted/plugin/CommandInjection/resources/CSRF.html" ; whoami ; ""]'

It gives this error at the bottom:

```
Returncode: 127
Bad return code (expected 0)
```

Also note that on OS X I had to either add a comment or a double quote to get rid of the last `"` that is added to the filename. This is not mentioned in the solution so perhaps it could be noted.

**Comment by nbaars** [comment]
Correct the Linux/Unix/OS X commands are restricted to:

- netstat -a
- dir 
- ifconfig
- etc.

We can add more commands, but looks like a safety thing only for Linux like platforms?
We can also make the lesson more explicit to for example state: "Try to execute the netstat command?"

**Comment by nbaars** [comment]
@mayhew64 see above, should we change the lesson and only accept the `netstat` command or any of the predefined commands?

**Comment by span** [comment]
I agree. If we cannot accept and work with any command from the user it would be nice to limit it to some specific commands like the ones you suggested. We could then show a message saying something like _"That is a good command but you really should try one of ..."_ if a non-predefined command is executed.

**Comment by mayhew64** [comment]
@span @nbaars I'm good with limiting the commands and providing information on the acceptable commands.  Sorry for the delayed reply.

**Comment by span** [comment]
I'm looking at one of the if statements in `CommandInjection.createContent`.

```
if (
    (osName.indexOf("Windows") != -1 
        && (helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("netstat -a")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("dir")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ls")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ifconfig") 
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ipconfig")
        )
    )
    || (helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("netstat -a #")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("dir #")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ls #")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ls -l #")
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ifconfig #") 
            || helpFile.substring(index, helpFileLen).trim().toLowerCase().equals("ipconfig #")
    )
  )
{
    illegalCommand = false;
}
``` 

So if the user is running Windows, all the commands are valid. Even commands like `ifconfig #` and `ls -l #`.

If the user is _not_ running Windows, the `dir #` command and `ipconfig #` are still valid although they are Windows commands. Is there some historic reason to why these commands are valid on other OS's?

Perhaps the easiest way forward would be to allow a mix of these commands no matter what OS the user is using. However, I think it would be more interesting for the user to actually see the output of their command so then they would have to be OS specific.

**Comment by nbaars** [comment]
Cleanup the lesson, if you use a ";" or a "&" with whoami or some other command the message will appear about the valid commands you can use. Also did some work on the layout so there is a more distinction between the lesson and the output of the command

**Comment by nbaars** [comment]
@span Can you test this lesson after the pull request has been merged?

**Comment by span** [comment]
I think this might need some more work.

I tried injecting the command `" ; whoami #` and I got the message about "being on the right track" but I also got a message saying I completed the lesson and it was marked green in the menu.

```
* It appears that you are on the right track. Commands that may compromise the operating system have been disabled. The following commands are allowed: netstat -a, dir, ls, ifconfig, and ipconfig.
* Congratulations. You have successfully completed this lesson.
```

Injecting `" ; whoami ; "` fails to complete (as it should) and displays the new message.

Without digging deeper I suspect it might have to do with the first command having a return code `0` and the second code is `127` as mentioned in previous comment. I suppose with this new restriction the first command really should fail with the new message although it returns 0.

**Comment by nbaars** [comment]
@span fixed the issue, the second if loop which does some checking marked the lesson as completed. Should be fixed, can you verify once more? Thanks.

**Comment by span** [comment]
@nbaars Hmm, I got the changes, cleaned a couple of times and rebuilt but my first command still succeeds. I got a busy week ahead unfortunately so I wont have time to look into it until next month.

**Comment by nbaars** [comment]
Will have a look

**Comment by Jaime02** [comment]
What happens if the user does not have ifconfig and netstat commands installed?? It is my case, I have been trying to complete it but I always got error code 127 before installing `sudo apt install net-tools`
