### ISSUE TITLE
Challenge - Show* buttons show on initial lesson load

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#180]
The show source and other show* buttons show upon initial lesson load. this alows the user to grab the source code without hacking the access control on the source servlet.

**Comment by misfir3** [comment]
@mayhew64 once PR is merged, this should be resolved. Can close after verifying.

**Comment by nbaars** [comment]
It now looks like:

![image](https://cloud.githubusercontent.com/assets/493861/13727972/1f19482e-e908-11e5-816e-f84e997921f2.png)

After switching between a normal lesson and the challenge

**Comment by nbaars** [comment]
Tested this issue again, looks like some caching issue. Issue is indeed fixed buttons are not shown in the challenge.
