### ISSUE TITLE
hints don't appear to work on labs

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#183]
First hint shows - no others.

**Comment by span** [comment]
I cannot reproduce the issue where only the first hint shows. I tested on the latest `develop` lesson server with the latest `master` lessons and I see *all* hints on the labs.

So for example on the Cross-Site Scripting Lab I can click through hints for stages 1 to 5 although I am viewing Stage 1. If I go to another Stage, the hints will be reset and shown from Stage 1. This might be the intended behaviour and it is fine with me.

**Comment by misfir3** [comment]
The hints are designed to work at a 'lesson' level.  If we want them to work at a stage level (and do we plan on supporting 'stages' in the future or just discrete/different lessons of varying levels?), we should create a separate issue (or set of issues) for that.

**Comment by nbaars** [comment]
@mayhew64 can you verify and close the issue?

**Comment by jl2035** [comment]
@span but the issue is out of the box. Only the first hint shows, others not.

I cannot complete "Edit Other Profiile" lesson without hints. There's not enough info on what is expected in request body. I've just spent 6 hours on the first 3 lessons.. what a waste of time. :(

**Comment by misfir3** [comment]
@jl2035 you're right ... the hints have not been completed on that lesson. Something we need to add. Reopening as the lesson isn't truly complete.

**Comment by misfir3** [comment]
actually re-opening wrong ticket here, will update IDOR lesson ticket (#304)

**Comment by jl2035** [comment]
@span but the issue is out of the box. Only the first hint shows, others not.

I cannot complete "Edit Other Profiile" lesson without hints. There's not enough info on what is expected in request body. I've just spent 6 hours on the first 3 lessons.. what a waste of time :(

**Comment by jl2035** [comment]
can you point me to the relevant piece of code, so i can see what the hints are? maybe that could help me to finish this lesson..

**Comment by misfir3** [comment]
IDOREditOtherProfiile.java in ...
 {WEBGOAT_ROOT}/webgoat-lessons/idor/src/main/java/org/owasp/webgoat/plugin/IDOREditOtherProfiile.java
... it's more of a simulated vuln. than an actual one. 

Sorry for the delay in getting back to you. Day-job and life have kept me rather busy lately
