### ISSUE TITLE
WebWolf lesson loads instead of every lesson 

### ISSUE THREAD

**Issue by earthling1984** [WebGoat/WebGoat#1857]
Hello,

I am using the Webgoat jar v2023.8 on Windows 11.

I was trying to load the SQL injection lesson, but beyond the landing page for the lesson, the WebWolf lesson is loading instead. The same seems to be happening for every lesson - everything is pointing to the WebWolf lesson after the landing page. The lessons were loading all ok a couple of weeks back.

Request assistance in working through this, and knowing the best approach to fix this.

Thanks!

**Comment by nbaars** [comment]
@earthling1984 interesting bug, not sure what is happening. Do you see a stack trace in the console?

You could try to delete the ./webgoat folder in the users home directory and restart WebGoat.

**Comment by earthling1984** [comment]
I missed the reply as I was relying on an email notification, not sure what happened there - thanks for your time with getting back! I wasn't able to reproduce it again since that occurrence, but I will keep an eye out and revert if it occurs again - will try using your tip. Thanks again!
