### ISSUE TITLE
Access Control Flaws, LAB stage 3: Remove the FindProfile screen

### ISSUE THREAD

**Issue by dhatanian** [WebGoat/WebGoat#186]
In stage 3, we try to read another employee's profile by changing the employee id in this URL:

```
/attack?Screen=322&menu=200&stage=3&employee_id=105&action=ViewProfile
```

However, the application already allows a user to view a profile using the `Search Staff` feature, which will legally display a an employee's profile. So basically the user is asked to find a hack to access a feature that he can already access through the normal application's behavior :-)

Since the `Search Staff` feature is not needed at this stage, it might be worth disabling/removing it to avoid confusion.

**Comment by dhatanian** [comment]
Sorry, I should have filed this under the `WebGoat-Lessons` repo. Closing this one, [made a copy in the lessons repo](https://github.com/WebGoat/WebGoat-Lessons/issues/51).

**Comment by misfir3** [comment]
@dhatanian We actually talked about this Friday and decided we want to keep the issues here. There is a way to link/reference fixes in other repo's. For now, leave this where you created it though.  Thx!

**Comment by span** [comment]
So it seems the search was not used in any stage for the lab so I removed the references to the find profile and search action in the commit.

**Comment by nbaars** [comment]
@span can you create a pull request of your branch towards WebGoat/WebGoat-Lessons?

**Comment by span** [comment]
There is one at webgoat/webgoat-lessons#64, should have made the description more clear I suppose.
