### ISSUE TITLE
Hi! Added menu support and translated all lectures from English to Russian, Serbian, Chinese (zh), Hindi, and Spanish languages.

### ISSUE THREAD

**Issue by BoyarD1** [WebGoat/WebGoat#1881]
Добавил поддержку в меню и перевел все лекции с английского на русский, сербский, китайский (zh), индийский (hindi), испанский языки
Added menu support and translated all lectures from English to Russian, Serbian, Chinese (zh), Hindi, and Spanish languages.

[main_new _copy.txt](https://github.com/user-attachments/files/16682986/main_new._copy.txt)

I can provide the source files with translations of the lectures into the aforementioned languages, with each translation also containing the original text in English.

Launch: 
1. docker pull boyarvaryag1/webgoat:8.0-ru-sr-cn-in-es 
2. docker run -p 8080:8080 boyarvaryag1/webgoat:8.0-ru-sr-cn-in-es 
3. http://localhost:8080/WebGoat/login⁠

**Comment by aolle** [comment]
Hello,
thank you for your colleb to localize the project. In the PR section, you'll find one that is a work in progress for the Spanish localization. Please feel free to contribute anything you think is necessary—your input is very welcome!
