### ISSUE TITLE
Confusing Phrasing of Reflected XSS Text

### ISSUE THREAD

**Issue by xn4224nx** [WebGoat/WebGoat#1915]
Hi, 
I am a Cyber Security student using your great content and I noticed a somewhat confusingly phrased sentence in the XSS lesson text. Namely in the file:

[src/main/resources/lessons/xss/documentation/CrossSiteScripting_content4.adoc ](https://github.com/WebGoat/WebGoat/blob/main/src/main/resources/lessons/xss/documentation/CrossSiteScripting_content4.adoc)

In the section about Reflected XSS one of the bullet points reads:

* Malicious content is written into the page after from server response

I am totally new to this concept but would it be better phrased as:

* Malicious content is written into the page after **the** server response

I have created a pull request  #1914 fix: xss lesson typo to make this change but I am new to collaborative github development so forgive me for any faux pas.

**Comment by aolle** [comment]
thanks
