### ISSUE TITLE
Navigation and links are not the same after reboot

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#194]
We (Me, Bruce, Misfir3) had some brief discussion on Slack where it was noted that the links are not the same on purpose. The reason for this was:

>  ... that is on purpose.  Was originally put in to make sure “testing tools” were not hardcoding test signatures on WebGoat.

I'm not sure what this really means but it seems strange not being able to share links with other users. Perhaps it could be possible to add a build flag that would allow the "testing tools" to behave properly and a regular build would enable the links to be the same.

**Comment by span** [comment]
Been pondering this for a while now. Since the screen id's are generated "randomly" when the plugins are loaded, the id's would either have to be predefined or calculated from the plugin name if we would like them to stay consistent after reboots and across builds.

Instead of messing with the id's it could be possible to create some mapping between the plugin name and its screen id. Plugin names like `db-sql-injection`, `command-injection` and `cross-site-scripting` are easy to read and understand and would create readable URL's while keeping the id structure intact.

I have not dug deeper into this, I'm sure it has its pro's and cons, so I would love to hear other thoughts and ideas.

**Comment by misfir3** [comment]
+1 on stable links. Been on my mind for a while to bring this up too (thanks for doing it @span). Need some more insight/discussion on the current status and some thought on implementation (assuming we move it forward).  However, I prefer this concept from a general web/product standpoint.

Also, I generally think the stable links allow for better integration with other OWASP products (e.g. ZAP scanning or Zest example scripts to be used with WebGoat) and for creating lessons/workshops around WebGoat.

**Comment by span** [comment]
One issue with this that I had not thought of earlier is that it seems many lessons depend on the numeric id's. So adding user-friendly URL's might break some things in an naive approach and would add a lot of complexity with a more sophisticated approach. It would also make some hints and solutions outdated.

Simply loading the plugins in a single-threaded manner would not fix this either since adding new plugins would change the id for any plugin loaded after it.

Perhaps it would be enough to have stable links for each release and that links might change between releases (if new plugins are added). It would be a bit annoying though. Another solution could be for each plugin to hardcode an id.

What are your thoughts?

**Comment by span** [comment]
While watching a presentation of the Lagom Java EE microservices framework they said that they were calculating port numbers based on the hash of the service name to enable autodeploy and autodiscovery. Perhaps this is not a bad option.

When compiling for deterministic id's we could calculate a hash that would generate an int in the range we want based on the plugin name. To me it seems like an easy, testable and flexible fix that should not require any other updates to existing functionality.

So if you agree on this approach, which do you want as default? I would argue that deterministic id's would be the default. Most likely because I don't understand the need for them to be random.

**Comment by nbaars** [comment]
Fixed for the 7 release. The screenIds are now always the same. 
Making it work with the names of the lessons required too many changes. The way we address a lesson will significantly change in release 8. 

For now this will make sure we can write some tests and it allows testing tools to have a go at WebGoat.

Available on the develop branch.
