### ISSUE TITLE
Missing mvn package of webgoat-container in README.MD

### ISSUE THREAD

**Issue by diegochavezcarro** [WebGoat/WebGoat#200]
In Option #2 to run the project it should be:
cd WebGoat/webgoat-container
mvn package
cd /target
java -jar webgoat-container-7.1-SNAPSHOT-war-exec.jar http://localhost:8080/WebGoat

**Comment by span** [comment]
Thank you for the report. For me it is enough to run `mvn package` from the `WebGoat` folder. I have cleaned and emptied the maven repo cache. It would be nice if you could confirm that you have to run mvn package inside `WebGoat/webgoat-container`. 

The run command needs to be updated to 7.1 though. As does the links to the 7.0 packages since the stable version is 7.0.1.

**Comment by diegochavezcarro** [comment]
Yes, I tried two times and needed to run mvn package inside WebGoat/webgoat-container. I have maven 3.3.9, Windows 7 32 bits.

**Comment by span** [comment]
Interesting, I'm on the same maven version but on OS X. Do you get an some error message when simply running the `mvn package` from the `WebGoat` folder?

**Comment by diegochavezcarro** [comment]
Following the steps of README, "The Manual Way: Developer Edition!", after cd WebGoat-Lessons when running mvn package, this is the error:
[ERROR] Failed to execute goal on project common: Could not resolve dependencies
 for project org.owasp.webgoat.lesson:common:jar:1.0: Could not find artifact or
g.owasp.webgoat:webgoat-container:jar:7.0-SNAPSHOT -> [Help 1]

**Comment by span** [comment]
Looks like it could be related to #145 where the reference in one of the pom files has not been updated which causes a common lib to fail the build. 

Would you mind cleaning both `WebGoat` and `WebGoat-Lessons`, apply the fix from webgoat/webgoat-lessons#60 to the pom.xml and then running through the steps from the `mvn clean compile install` step again?

**Comment by diegochavezcarro** [comment]
It works! I forgot I already changed the pom, but that time I just went on without doing mvn clean compile install. This time I did it and it worked well

**Comment by span** [comment]
Great!

**Comment by span** [comment]
Package references now merged, voting to close.

**Comment by mayhew64** [comment]
+1
