### ISSUE TITLE
Labs: Remnant files and solved stages

### ISSUE THREAD

**Issue by krvw** [WebGoat/WebGoat#208]
OK, I hope I'm being clear enough. Apologies if I'm not. First off, I'm building from the master branch. Building from command line, so no IDE involved, FWIW.

While preparing for an upcoming coding lab session, I worked through all the XSS and SQLi labs. In doing that, I found several of the java class files seemed to have copies in two places:

WebGoat-Lessons/goat-hills-financial
and
WebGoat-Lessons/cross-site-scripting (and similar for sql-injection)

In particular, for the XSS lab Stage 1, there is an UpdateProfile.java in both locations.

Checking the WebGoat-Lessons/cross-site-scripting/.../CrossSiteScripting.java file, I see the one that is actually being imported is the one in goat-hills-financial.

HOWEVER, that version of UpdateProfile.java uses the parser class to read in the employee's profile, so it contains no XSS problem.

If I import the version of UpdateProfile.java in cross-site-scripting, then the vulnerability is indeed there. BUT this is not how the lab is distributed.

FWIW, looking at the instructor code in the WebGoat-Legacy tree, it's clear that the instructor version was built upon the version of UpdateProfile.java located in the cross-site-scripting directory, NOT the one that is in goat-hills-financial.

Seems there's an easy fix for this one, and that is to copy the UpdateProfile.java from cross-site-scripting to goat-hills-financial, but I wouldn't want to undo something that is being worked on in the goat-hills-financial version.

I have not yet exhaustively checked all the files in goat-hills-financial as well as cross-site-scripting, sql-injection, and role-based-access-control, but that's the next step. My gut feel is that what I'm seeing is a bunch of remnants from older version, but I don't know which is which.

Can anyone please shed some light on this for me?

Thanks.

Ken van Wyk

**Comment by krvw** [comment]
Example snippet from UpdateProfile.java in cross-site-scripting (the one that is NOT being used in the lab, currently):

        HttpServletRequest request = s.getRequest();
        String firstName = request.getParameter(CrossSiteScripting.FIRST_NAME);
        String lastName = request.getParameter(CrossSiteScripting.LAST_NAME);
        String ssn = request.getParameter(CrossSiteScripting.SSN);
        String title = request.getParameter(CrossSiteScripting.TITLE);
        String phone = request.getParameter(CrossSiteScripting.PHONE_NUMBER);
        String address1 = request.getParameter(CrossSiteScripting.ADDRESS1);
        String address2 = request.getParameter(CrossSiteScripting.ADDRESS2);

Compare that with the UpdateProfile.java in the goat-hills-financial directory:

            String firstName = s.getParser().getStringParameter(GoatHillsFinancial.FIRST_NAME);
            String lastName = s.getParser().getStringParameter(GoatHillsFinancial.LAST_NAME);
            String ssn = s.getParser().getStringParameter(GoatHillsFinancial.SSN);
            String title = s.getParser().getStringParameter(GoatHillsFinancial.TITLE);
            String phone = s.getParser().getStringParameter(GoatHillsFinancial.PHONE_NUMBER);
            String address1 = s.getParser().getStringParameter(GoatHillsFinancial.ADDRESS1);

This one is already using the parser class, which already converts "<" to "." and such, on input. So, there's no XSS vulnerability -- or at least not the one associated with this lab -- in the UpdateProfile.java that is being built in the master branch.

Cheers,

Ken van Wyk

**Comment by krvw** [comment]
From the WebGoat-Legacy tree, the instructor version of UpdateProfile.java is clearly based on the file in cross-site-scripting:

       HttpServletRequest request = s.getRequest();
        String firstName = request.getParameter(CrossSiteScripting.FIRST_NAME);
        String lastName = request.getParameter(CrossSiteScripting.LAST_NAME);
        String ssn = request.getParameter(CrossSiteScripting.SSN);
        String title = request.getParameter(CrossSiteScripting.TITLE);
        String phone = request.getParameter(CrossSiteScripting.PHONE_NUMBER);

        // Validate this parameter against a regular expression pattern designed for street
        // addresses.

        // STAGE 2 - FIX
        final Pattern PATTERN_ADDRESS1 = Pattern.compile("[a-zA-Z0-9,\\.\\- ]{0,80}");
        String address1 = validate(request.getParameter(CrossSiteScripting.ADDRESS1), PATTERN_ADDRESS1);

**Comment by krvw** [comment]
I've found a simpler solution, but I'm not sure if it breaks the design intent here, so please holler if it does.

In the CrossSiteScripting.java file located in WebGoat-Lessons/cross-site-scripting... simply comment out the import line for UpdateProfile (and, presumably, any other class files that are in the cross-site-scripting directory). That'll cause the appropriate java class to be used from the cross-site-scripting package directory and NOT the one in goat-hills-financial.

It works, I just tested it.

It still begs the question of how these things were intended to be appropriately organized. I'm pretty rigid when it comes to ensuring things are properly organized in my own world, so perhaps someone here can point me to the _right_ way to do it here, please?

Thanks.

**Comment by nbaars** [comment]
@krvw you are right the import is from the wrong package. It was on the list to go through all the GoatHills lessons to see were the newly defined class was different. Think if there is a difference we are better of renaming the class so it is not that easy to mix the classes.

**Comment by krvw** [comment]
That’s a relief, thanks! I thought I was going crazy.

Now, just to clarify, which is the correct set of (flawed) LAB classes to use, the ones in cross-site-scripting or the ones in goat-hills-financial? And is this consistent in the other labs (sql-injection, role-based-access-control)?

I’m happy to help with the organizing on this. Just need to know what the design intention was.

Thanks.

Ken

**Comment by nbaars** [comment]
Pull request available in WebGoat/WebGoat-Lessons

**Comment by krvw** [comment]
Thanks! I just grabbed the latest and that cleaned up the SQLi and XSS labs for me. Most appreciated!

**Comment by nbaars** [comment]
Great! Closing this issue
