### ISSUE TITLE
How to use a different IP for VM?

### ISSUE THREAD

**Issue by IWriteThings** [WebGoat/WebGoat#215]
I want to install the WebGoat application inside a VM. I need it to not point to 127.0.0.1 but instead go to the internal IP of the device.

How do I change the IP from 127 when running the application? I can change ports but not the IP.

**Comment by mayhew64** [comment]
How are you running WebGoat?  You will either need to change the IP in the server.xml file or you may be able to change the host as a parameter to the build and generate a new standalone jar.

**Comment by IWriteThings** [comment]
I am using the standalone file. The one linked in the read me.

**Comment by mayhew64** [comment]
You will need to rebuild the war-exec.  The instructions on how to build WebGoat are in the README located: https://github.com/WebGoat/WebGoat  

The instructions for changing the tomcat plugin settings are: http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/usage.html

Once you have done this would you mind supplying the steps so we can put it in our FAQ.

**Comment by IWriteThings** [comment]
Rebuild WebGoat To Use A Different IP For VM
- [ ] Rebuild the war-exec
- [ ] Change the Tomcat settings
- [ ] Create the FAQ Instructions For Doing So
- [ ] Request Change To Compiled System To Accept Different IP in arguments

Example
```
java - jar webgoat.exec.jar --port 1234 --bound-ip 10.0.1.15
```

I will get this done this weekend. Please leave this issue open in the meantime as I get this done. Thanks!

**Comment by nbaars** [comment]
See, #233 with Spring Boot you can directly specify the port. (not sure about the bound-ip) though

**Comment by nbaars** [comment]
For the 7.1 release you can use the following command with the executable war:

```
java -jar .\webgoat-container-7.1-SNAPSHOT-war-exec.jar -httpPort=8081
```

(use the 7.1 executable jar in the above command if applicable)

This will start WebGoat on port 8081.

**Comment by nbaars** [comment]
During AppSec EU there was a discussing we should not use the 8080 port as a default because it is a well-known port which might interfere with other apps (like Burp, ZAP etc).

**Comment by misfir3** [comment]
... as noted by Nanne, we discussed this. We are leaning toward port 6047 (closest number to spelling 'goat' that should not conflict with anything) :)

**Comment by IWriteThings** [comment]
Changing the port is fine but the big issue is the IP. Being able to specify a different IP is much more important for those of us using WebGoat in an educational setting.

Thank you for continuing to work on these issues!

**Comment by nbaars** [comment]
WebGoat now starts running on an embedded Tomcat server which will give the opportunity to change the server address and the port number.
 
Solved, see feature/portnumber (almost done)

**Comment by nbaars** [comment]
Merged to develop, see README.md of webgoat-standalone project

**Comment by mattrussell33** [comment]
Hi All,

It is still not clear on the actions needed to set an IP rather than using localhost. Using webgoat-container-7.1-exec which runs on the embedded tomcat server, but I do not see any options to change the server address or config to do so.
Anybody able to shed some light on this?
Cheers :)

**Comment by Dviros** [comment]
Hi, Need help as well in binding to 0.0.0.0 or specific IP.
Thanks

**Comment by mattrussell33** [comment]
Hi Dviros, A quick workaround I found is to use iptables to route traffic from your desired interface to the localhost and port.
 
Below is an example if you have interface ens192 configured  with IP 10.1.0.1 listening on port 8181
 
iptables -t nat -I PREROUTING -p tcp -d 10.1.0.1/24 --dport 8181 -j DNAT --to-destination 127.0.0.1:8080

sysctl -w net.ipv4.conf.ens192.route_localnet=1

Hope this helps :)

**Comment by Dviros** [comment]
Hey Mat,
Thanks for your quick reply. I'm using a Windows machine :(
Any other idea?

**Comment by mattrussell33** [comment]
Hmmm, I'm don't use windows much TBH.
Deploying webgoat on a linux virtual machine using VirtualBox would be an option. A bit of a pain just to use WebGoat but will give you the flexibility to modify the IP.
Sorry I couldn't be much more help than that!
