### ISSUE TITLE
Menu is not auto expanding when reloading

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#217]
To reproduce:
1. Log in
2. Go to any menu option that requires the menu to expand
3. Reload the page (F5, CTRL+R, CMD+R)
4. The page reloads but the menu is not expanded to show the currently selected page

**Comment by nbaars** [comment]
Correct, controller needs to reload menu I guess.

**Comment by nbaars** [comment]
@misfir3 can you have a look?

**Comment by misfir3** [comment]
Will do ... Seems you have found some internet access during your holiday, eh? ;-)

**Comment by nbaars** [comment]
Old issue, closing
