### ISSUE TITLE
Navigation to start page is broken after login

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#218]
After logging in the intro page loads fine. When clicking the logo in the top left corner which loads `start.mvc` I am not redirected to the `Introduction: How to work with WebGoat` page nor any other page. I simply get a blank screen in the lesson area. The menu loads fine but the cookies/parameters view is not loading.

This is also the case if navigating to "home" by the top left logo from any lesson.

<img width="600" alt="screen shot 2016-03-23 at 20 36 45" src="https://cloud.githubusercontent.com/assets/502136/13998345/01988b16-f137-11e5-804b-5a21dd319b42.png">

**Comment by span** [comment]
So it seems `start.mvc` is not really "the start". `start.mvc` gets sent the navigation link from `Hammerhead`. `Hammerhead` looks for the parameter `start=true` to load the orrect link. Without the link the page will not be initialised properly since Backbone will not know which screen to load.

So: we can either link to `welcome.mvc` from the logo, or we can link to `/WebGoat/?start=true` so that `Hammerhead` redirects us.

**Comment by nbaars** [comment]
I agree `/welcome.mvc` looks like a cleaner solution.
