### ISSUE TITLE
AXIS class not found error in  Web Services / WSDL Scanning 

### ISSUE THREAD

**Issue by samstep** [WebGoat/WebGoat#222]
WebScarab v7.0.1

Go to: Web Services / WSDL Scanning - click on the WebGoat WSDL link:

**AXIS error

Sorry, something seems to have gone wrong... here are the details:

Fault - ; nested exception is: 
	org.apache.axis.ConfigurationException: Could not find class for the service named: org.owasp.webgoat.lessons.WSDLScanning
**Hint: you may need to copy your class files/tree into the right location (which depends on the servlet system you are using).; nested exception is: 
	java.lang.ClassNotFoundException: org.owasp.webgoat.lessons.WSDLScanning
AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.generalException
 faultSubcode: 
 faultString: Could not find class for the service named: org.owasp.webgoat.lessons.WSDLScanning

**Comment by nbaars** [comment]
Same a #221 fixed.

@samstep can you also test this lesson with the develop version of WebGoat, thanks in advance.
