### ISSUE TITLE
Refresh in Insecure Login malfunctions

### ISSUE THREAD

**Issue by vdbaan** [WebGoat/WebGoat#225]
The Refresh button in the Insecure Login lesson loads the main page inside the lesson-content-wrapper, instead of just refreshing the entire page.

**Comment by span** [comment]
I'm looking at Insecure Communications -> Insecure Login and I can't see any button with a `Refresh` action here. Is it missing in 7.1?

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
