### ISSUE TITLE
Restart lesson button isn't working

### ISSUE THREAD

**Issue by krvw** [WebGoat/WebGoat#226]
Unless I'm doing something wrong, the Restart Lesson link is no longer restarting any of the lessons. In some cases, this doesn't matter, but in others, that leaves you in a state you can't get out of.

Thanks.

Ken van Wyk

**Comment by mayhew64** [comment]
Which lesson(s)?

**Comment by krvw** [comment]
I tried it in a few, and I didn't see it working in any. However, String SQL Injection is a good example. After you succeed with an attack (e.g., ' or '1'='1), the servlet starts using PreparedStatement to protect itself. When I press restart to go back to the unprotected state, nothing happens.

**Comment by span** [comment]
This has been an issue on and off. Are you using the latest snapshot build from the develop branch @krvw?

**Comment by krvw** [comment]
Last updated mine about 2 weeks ago, but I'll refresh and verify. Thanks.

**Comment by krvw** [comment]
Yup, you were right. After a refresh, the problem (at least in the string SQL injection) exercise is now fixed. Thanks!

**Comment by nbaars** [comment]
Seems to be working, closing for now (we can always open the issue again)
