### ISSUE TITLE
Session Fixation lesson problem with passing parameter

### ISSUE THREAD

**Issue by krvw** [WebGoat/WebGoat#227]
When I try the Session Fixation lesson, if I add the SID parameter to the href link using "?SID=12345", stage 2 fails. However, if I use "&SID=12345", all is well.

Using the former, stage 2 ends up in a bad way, as I cannot restart the lesson either, and logging out doesn't restart it. I have to recompile and redeploy WebGoat to extricate the session from this state.

Perhaps there's an easier way to do this, but...

Now, shouldn't the _first_ parameter in a GET be preceded with a "?" and not a "&"? Isn't the "?SID=..." syntax the correct one? If that's the case, then this is definitely a bug, IMHO.

Cheers,

Ken van Wyk

**Comment by b1rd0fb3auty14** [comment]
Hello @krvw - I think adding the ampersand to the query string is correct. The issue seems the ampersand is not being encoded properly. Instead of passing the "&" - it should be "&amp;"
See website: https://perishablepress.com/how-to-write-valid-url-query-string-parameters/

@mayhew64 - Please give your feedback. Thanks!

**Comment by misfir3** [comment]
I'll look at it, but in short ... 
* yes, `?var=foo` is correct for first parameter
* AND  `&var2=bar` is correct for following parameters 
... on a GET request

With some other under the hood changes in WebGoat that happened a little while back, there are ajax calls being made that you are essentially appending to.  Likely we need to update the text/hints on it.

Filing as bug is correct. I'll assign this to myself and look at it.

**Comment by nbaars** [comment]
Checked the lesson and the stage 2 can be completed by clicking the link. Think we can close this one.
