### ISSUE TITLE
Bypass client side javascript validation not working?

### ISSUE THREAD

**Issue by krvw** [WebGoat/WebGoat#230]
Might well be pilot error, but I'm no longer able to get this exercise to work. Is there a bug? I intercept the request, change a couple fields, and the screen merely refreshes with the original (pre-validated) data in place. No mention of any fields bypassed.

This one was working for me up until very recently. I just grabbed fresh code from Github, and confirmed the problem still exists for me. Anyone else?

Thanks.

Ken van Wyk

**Comment by span** [comment]
Nice catch @krvw. 

I am also having issues with this lesson. It seems the form submission is reloading the whole page plus some extras.

After clearing the network tab in the developer tools and then submitting the form I can see all the core javascript files reloading together with the css and logo. I then also see the lessoninfo and cookies (among the others) load twice.

I'm attaching a HAR file which can be unzipped and 
[bypass-client-side-post.har.zip](https://github.com/WebGoat/WebGoat/files/324399/bypass-client-side-post.har.zip)
explored here: https://toolbox.googleapps.com/apps/har_analyzer/

It seems to me the ajax handler that should post this form is broken.

**Comment by misfir3** [comment]
Another one related to the move to SPA ... have to think some more about better ways to support ones like this.

**Comment by nbaars** [comment]
Added testcase, lessons works.
