### ISSUE TITLE
Lesson Ajax Security "LAB: Client Side Filtering" - can't validate stage 2

### ISSUE THREAD

**Issue by splanard** [WebGoat/WebGoat#231]
I'm running webgoat 7.0.1 on XAMPP tomcat server.
In the stage 2 of the lesson mentionned in the title, it is asked to modify the jsp file to add filter in the XPath expression upon the manager ID, which I did. 
But I just can't validate this step. 

I even duplicated a part of the java source code in a small java application on Eclipse to debug this matter :

```
public static void main(String[] args) throws Exception {
    String file = "C:/dev/xampp/tomcat/webapps/webgoat-7.0.1/plugin_extracted/plugin/ClientSideFiltering/jsp/clientSideFiltering.jsp";
    String content = getFileContent(file);

    if (content.indexOf("[Managers/Manager/text()") != -1)
    {
        System.out.println( "TRUE" );
    }
    else
    {
        System.out.println( "FALSE" );
    }
}

private static String getFileContent(String content)
{
    BufferedReader is = null;
    StringBuffer sb = new StringBuffer();

    try
    {
        is = new BufferedReader(new FileReader(new File(content)));
        String s = null;

        while ((s = is.readLine()) != null)
        {
            sb.append(s);
        }
    } catch (Exception e)
    {
        e.printStackTrace();
    } finally
    {
        if (is != null)
        {
            try
            {
                is.close();
            } catch (IOException ioe)
            {

            }
        }
    }

    return sb.toString();
}
```

This prints "TRUE" when running.
But still, the stage 2 won't validate : the submit button keeps reloading the same page ever again.

**Comment by DarkHunterer** [comment]
There is a slash missing in the "webapps/WebGoat/plugin_extracted/plugin/ClientSideFilteringjsp/clientSideFiltering.jsp" string.

You can work it around by adding it before "jsp" so it should look like: 

webapps/WebGoat/plugin_extracted/plugin/ClientSideFiltering/jsp/clientSideFiltering.jsp

**Comment by splanard** [comment]
I don't understand what you're talking about...

**Comment by splanard** [comment]
Ok, I finally understand what you mean now I looked more into webgoat classes.
The initial code of the method `ClientSideFiltering.doStage2()` contains the following line : 
```
String file = LessonUtil.getLessonDirectory(s, this) + "jsp/clientSideFiltering.jsp";
```
And here is the content of `LessonUtil.getLesson()` : 
```
public static File getLessonDirectory(WebSession w, AbstractLesson lesson) {
    return new File(w.getContext().getRealPath("/plugin_extracted/plugin/" + lesson.getLessonName() + "/"));
}
```
The implicit call of `toString()` on the lesson directory removes the trailing slash. So the JSP path can't be correct : the result is what DarkHunterer posted.

**Comment by b1rd0fb3auty14** [comment]
@DarkHunterer @splanard Has anyone fixed this? If not - I can do it. Please respond. Thanks!

**Comment by splanard** [comment]
I really have no idea. I'm still using the same version of WebGoat (the one from which I reported this issue).

**Comment by DarkHunterer** [comment]
I fixed it locally but lost it long time ago. There are some more similiar issues in several places that I didn't have time to report.

**Comment by mayhew64** [comment]
@b1rd0fb3auty14 Feel free to submit a pull request.  It would be greatly appreciated

**Comment by b1rd0fb3auty14** [comment]
Hello @mayhew64, @DarkHunterer, @nbaars - I have fixed the issue. The pull request is here: https://github.com/b1rd0fb3auty14/WebGoat-Lessons/pull/2/

Please let me know if I have put the fix in the wrong repo.

Thanks

**Comment by span** [comment]
@b1rd0fb3auty14 Fix looks fine to me. Nice job! 

You seem to have created the PR in your repo rather then in the Webgoat/Webgoat repo though. Please create a PR here as well 👍

**Comment by b1rd0fb3auty14** [comment]
Thanks @span - I have the following link --> https://github.com/WebGoat/WebGoat-Lessons/pull/69

I think I did this wrong, but I don't know how to change it.

**Comment by span** [comment]
@b1rd0fb3auty14 The PR looks ok now. You can see the difference in where the PR is created.

The first one you created was created in your own fork: b1rd0fb3auty14/WebGoat-Lessons#2

This other one was for this repo: WebGoat/WebGoat-Lessons#69

If you look at the second PR you created you can also see where the merge is coming from and where it is going `b1rd0fb3auty14 wants to merge 2 commits into WebGoat:master from b1rd0fb3auty14:jasmine_develop`
