### ISSUE TITLE
Could not initialize class org.owasp.webgoat.session.UserTracker

### ISSUE THREAD

**Issue by SpyrosMArtel** [WebGoat/WebGoat#235]
Hello,
After compiling WebGoat 7 and copying the war file to _$tomcat_root/webapps_ (Virtual Machine) and logging in with both default accounts (From host), the following exception occurs (Screen : "How to work with WebGoat"):

```
Error Message: Could not initialize class org.owasp.webgoat.session.UserTracker
java.lang.NoClassDefFoundError: Could not initialize class org.owasp.webgoat.session.UserTracker
at org.owasp.webgoat.session.Screen.getLessonTracker(Screen.java:117)
at org.owasp.webgoat.lessons.LessonAdapter.makeSuccess(LessonAdapter.java:251)
at org.owasp.webgoat.plugin.HowToWork.createContent(HowToWork.java:53)
at org.owasp.webgoat.lessons.AbstractLesson.handleRequest(AbstractLesson.java:868)
at org.owasp.webgoat.HammerHead.makeScreen(HammerHead.java:332)
at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:148)
at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:104)
```

Further a loading spinner is visible on the left, where the lessons should have been.
I will try to explain all the steps involved in an effort to ease the replication:
- Ubuntu server 14.04.4 LTS installed on VirtualBox with OpenSSL and Tomcat[7.x] packages selected. OpenJDK 7 comes as default.
- In /opt/ directory, I run the following:

```
sudo git clone https://github.com/WebGoat/WebGoat.git
sudo git clone https://github.com/WebGoat/WebGoat-Lessons.git
sudo chown myusername:myusername WebGoat -R
sudo chown myusername:myusername WebGoat-Lessons -R
```
- The documentation was a bit off here and lacking some info, the steps that worked for me are:

```
cd WebGoat-Lessons
mvn package
```

However, the above command result in an Maven error: **Error copying artifact from _/opt/WebGoat-Lessons/pom.xml to /opt/target/plugins/pom.xml: /opt/target/plugins/pom.xml (no such file or directory)_**. To fix this problem, I had to create a target directory in /opt/:

```
cd ..
sudo mkdir target
sudo chown myusername:myusername target/ -R
```

Now the following works just fine:

```
cd WebGoat-Lessons
mvn package
cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/
cd ..
```

and the WebGoat project, along with the lessons can now be built:

```
cd WebGoat
mvn clean compile install
```

Running the project with the embedded server seems to work flawlessly:
`mvn -pl webgoat-container/ tomcat7:run-war`
The issue occurs with the following:

```
mvn package
cp webgoat-container/target/webgoat-container-7.1-SNAPSHOT.war /var/lib/tomcat7/webapps/WebGoat.war
```

Tomcat explodes the war as it should and the server can be accessed remotelly like so _http://server.ip.address/WebGoat_. The login screen with the default accounts is displayed, and after logging in, BOOM! UserTracker exception.

I have tried to figure out where the issue might be, by debugging the project. However, I had no success.
Debugging locally, on a Windows machine with Tomcat everything runs fine and no exceptions.
Debugging on the remote server the UserTracker class seems to be non resolvable (Ctrl+LeftMouseClick does not work) and always throws the exception, despite the fact that the "UserTracker.class" is present in the WEB-INF/classes.

**Comment by nbaars** [comment]
The NoClassDef  exception is not the root cause. There is some static piece of code in this class which will try to init the database. This probably fails and therefore the class cannot be loaded. Think this has something to do with the h2 db initialization. 

@SpyrosMArtel can you try to put a breakpoint in the UserDatabase class in the open() method?

**Comment by SpyrosMArtel** [comment]
Hello @nbaars,
I set a breakpoint in the `open()` method [`UserDatabase` class] on the remote server but the debugger is not hitting it (like the code is never executed).

**Comment by ggggtttt** [comment]
Hi Gents,

any idea how to fix this issue?

**Comment by IceGiant** [comment]
Hitting this same issue running in a Windows 10 environment running from the 7.0.1 binary

**Comment by nbaars** [comment]
Old issue, rewritten in version 8.0. Not reported in 7.1 as well

**Comment by SupaYoshi** [comment]
Hi, still experiencing this issue right now with WebGoat 7.1 and Tomcat8! Been looking for hours for a solution, IRC is not helpful, I've placed all the files in the directory, I keep getting this error. PLEASE HELP.

http://prntscr.com/e337af

**Comment by nbaars** [comment]
@SupaYoshi indeed this combination does not work, see https://github.com/WebGoat/WebGoat/wiki/FAQ#tomcat 

You can use our Docker based WebGoat-7 version, please see: https://hub.docker.com/r/webgoat/webgoat-7.1/
