### ISSUE TITLE
developer bootstrap says git is missing when it is installed

### ISSUE THREAD

**Issue by sowdust** [WebGoat/WebGoat#236]
After launching webgoat_developer_bootstrap.sh it returns the error `ERROR: Missing git'! Make sure it exists and try again` althought git is properly installed. In fact, installing "the manual way" clones the repositories just fine

**Comment by mayhew64** [comment]
@dougmorato Can you look into this

**Comment by dilshanraja** [comment]
Encountered the same issue - the return codes in ftest() were mixed up.

I've created a pull request for it - https://github.com/WebGoat/WebGoat/pull/238

**Comment by nbaars** [comment]
Closing the issue because #239 has been merged
