### ISSUE TITLE
Wrong Answer Section: Authentication Flaws Challenge: Password Strength

### ISSUE THREAD

**Issue by eschonberger** [WebGoat/WebGoat#237]
The solution claims to be:

Password = 123456: 0 seconds
Password = abzfezd: 2 seconds
Password = a9z1ezd: 19 seconds
Password = aB8fEzDq: 15 hours
Password = z8!E?7: 20 days
Password = My1stPassword!:Redd: 364 quintillion years

however when you use: https://howsecureismypassword.net **the results differ:**

Password = 123456: 0 seconds
Password = abzfezd: 0.2 seconds
Password = a9z1ezd: 2 seconds
Password = aB8fEzDq: 2 hours
Password = z8!E?7: 2 days
Password = My1stPassword!:Redd: 36 quintillion years

Would you be so kind to correct the results for the next version?

Greetings :-)

**Comment by span** [comment]
I think it would be worth noting that different "password testers" will yield different results. The GRC haystack for example gets the following results for `My1stPassword!:Redd`

> Online Attack Scenario:
> (Assuming one thousand guesses per second)	12.13 trillion trillion centuries
> Offline Fast Attack Scenario:
> (Assuming one hundred billion guesses per second)	1.21 hundred thousand trillion centuries
> Massive Cracking Array Scenario:
> (Assuming one hundred trillion guesses per second)	1.21 hundred trillion centuries

This should be made clear in the updated answer and I'm thinking perhaps it should also note that dictionaries are very efficient against the `My1stPassword!:Redd` type passwords.

**Comment by nbaars** [comment]
Pull request available, see WebGoat-Lessons. @WebGoat/admins can somebody merge review and merge the pull request.

**Comment by misfir3** [comment]
Not seeing any pull requests in WebGoat-Lessons ... got tired of waiting for me? ;-)

**Comment by nbaars** [comment]
@WebGoat/admins sorry forgot to create the pull request in Github is available now

**Comment by Mungoid** [comment]
Would something like this be better if it were a little more generalized? Like possibly radio buttons for each with a range of answers kind of like: "Less than a second", "Less than a minute", "Less than a day", "Many Days", "Many Years", etc? 

Im sure that password security site doesnt update its calculations often, but I would imagine this exercise will have to be changed every time it does.

**Comment by mayhew64** [comment]
I think this is a good suggestion.

**Comment by latinengineer** [comment]
Hi, I am new to WebGoat! 
I am still seeing this issue on my side. I am using Mozilla and I see Version: 7.1, Build: build.
