### ISSUE TITLE
WebGoat // Lesson Plan and Solution are note available

### ISSUE THREAD

**Issue by ysalimi** [WebGoat/WebGoat#242]
Hello Team,

I'm requesting you because I encounter some issues with WebGoat installed on my local machine.
The machine is KaliLinux2
I've installed the last version from : http://webgoat-war.s3-website-us-east-1.amazonaws.com/

On the java launched on my machines I'm able to connect to the WebGoat but the problem is that i have the message bellow when I click on "Lesson Plan" and "Solution" on each exercise.

Have you already encountered this problem?

Thank's
Yasser

**Comment by nbaars** [comment]
@ysalimi can you please paste the message? Are you logging in as adminstrator or as guest?

Thanks
--Nanne

**Comment by ysalimi** [comment]
Hello @nbaars ,

Thank's for your quick reply.
The message is : Solution is not available. Contact webgoat@owasp.org

--
Best regards,
Yasser

**Comment by mayhew64** [comment]
@ysalimi are you getting this for every lesson or just some of them?

**Comment by ysalimi** [comment]
Hi @mayhew64 

I'm getting this error for every lesson.

--
Kind regards,
Yasser

**Comment by nbaars** [comment]
@ysalimi which version did you download from http://webgoat-war.s3-website-us-east-1.amazonaws.com/ ?

**Comment by ysalimi** [comment]
Hello @nbaars,

I've tested : 

- webgoat-container-7.1-SNAPSHOT-war-exec.jar
- webgoat-container-7.1-SNAPSHOT.jar

--
Best regards,
Yasser

**Comment by misfir3** [comment]
This appears to be related to 'stages' and it also appears to be happening at load time.
@nbaars - I think when we looked before, we spot-clicked and didn't hit any lab stages in the process.  

So, I tinkered with some debug statements in Course.java#loadLessonFromPlugin around 
`if (plugin.getLessonSolution("en").isPresent()) {
                    lesson.setLessonSolutionFileName(plugin.getLessonSolution("en").get().toString());
                }
`
It seems that the lesson solution is not present. Still looking some at it, but you might be quicker on it at this point.

**Comment by nbaars** [comment]
Tested this with the SQL injection lesson which has stages, but in my opinion it works. Only the lesson plan is available for this lesson so there is no lesson solution to show. The messages is indeed correct. 
Btw all the GoatHills derived lesson do not have a solution.

Closing this one, we can always reopen this issue.
