### ISSUE TITLE
Compilation Error:

### ISSUE THREAD

**Issue by big-owl** [WebGoat/WebGoat#247]
Following the instructions for compiling the lessons (The Manual Way) -

Compiling the WebGoat Lessons server works just fine, but I'm having problems when compiling the lessons.

C:\Security>cd WebGoat-Lessons
C:\Security\WebGoat-Lessons>git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'
C:\Security\WebGoat-Lessons>mvn package
...
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Security/WebGoat-Lessons/path-based-access-control/src/main/java/org
/owasp/webgoat/plugin/PathBasedAccessControl.java:[111,65] cannot find symbol
symbol: method isDefuseOSCommands()
location: class org.owasp.webgoat.session.WebgoatContext
[ERROR] /C:/Security/WebGoat-Lessons/path-based-access-control/src/main/java/org
/owasp/webgoat/plugin/PathBasedAccessControl.java:[112,44] cannot find symbol
symbol: method isDefuseOSCommands()
location: class org.owasp.webgoat.session.WebgoatContext
...

Any help would be appreciated.

**Comment by b1rd0fb3auty14** [comment]
@big-owl  - The method is not defined and/or deleted. I'll take a look. @mayhew64 @misfir3 @span

**Comment by big-owl** [comment]
It appears that nbaars removed the 'defuseOSCommands' logic from WebgoatContext.java on Mar 19 (commit 181549468124bc45cf3bda78409a7390cc6ffe69), as being no longer necessary due to a change in the lesson.  

Unfortunately, this method is still called from the createContent method of the PathBasedAccessControl java file.

**Comment by misfir3** [comment]
@big-owl, thanks for looking into it. @nbaars is likely incommunicado for the next week. I will see if I can patch it, but also feel free to contribute a patch reverting it and I can merge the pull request (for develop).

**Comment by b1rd0fb3auty14** [comment]
Thanks @misfir3 for the update. Let me know if you need help, I am available!

**Comment by nbaars** [comment]
@b1rd0fb3auty14, @misfir3 I've deleted the method because we limited the commands which can be executed from within WebGoat(command injection lesson). I seem to have forgot this lesson it can be removed here as well. Think we should take the same approach here.

@big-owl for compilation can you comment out this lesson in the parent pom?

@b1rd0fb3auty14 are you interested in rewriting the lesson? Same as we did for command injection.

**Comment by b1rd0fb3auty14** [comment]
Hey @nbaars - Yes, I am interested in rewriting the lesson. I will take a look at the command injection code and if I have questions - I will ask you. Thanks!

**Comment by b1rd0fb3auty14** [comment]
Hey @nbaars - Should the PathBasedAccessControl be similar to this lesson: https://github.com/WebGoat/WebGoat/issues/179?

**Comment by nbaars** [comment]
@b1rd0fb3auty14 Should the PathBasedAccessControl be similar to this lesson: #179?
Indeed that lesson used the same command and was rewritten.

**Comment by b1rd0fb3auty14** [comment]
@nbaars I am a bit confused. With commit #179 the different commands were in the file. In the PathBasedAccessControl.java file I do not see the commands listed in the file. Are these commands stored in an outside document? 

Also, to ALL this might sound dumb, but I have the WebGoat and WebGoat lessons project installed in NetBeans. I want to know how I can verify that my local changes were properly applied before I commit them.

Please respond when able.

**Comment by nbaars** [comment]
Solved, lesson also needed some adjustment level limit was too low

**Comment by b1rd0fb3auty14** [comment]
@nbaars - can you provide the commit link for this? I had a proposed solution and wanted to see if I was on the right path. Thanks!

**Comment by RubieV** [comment]
When the patch is applied, please merge the dev branch to the two outstanding PRs #256 and #257 that cleanup parts of the code base for better readability and testability. 

I believe that when WebGoat commits to clean code, the community will be more active and boast new development!

Keep up the great work of improving code! Happy to help alongside with Stefan Michielse to work on a couple of integration tests once this framework is set up.

**Comment by RubieV** [comment]
About NetBeans: running the Maven tests will test your local code for compilation errors and will run the unit tests. The integrated version control can be used to commit parts of code changes and push them.

**Comment by RubieV** [comment]
@StefanMichielse adding you in!

**Comment by nbaars** [comment]
Fixed, Travis build script was using the master branch of WebGoat-Lessons instead of develop.

@RubieV thanks for the help, for some integration tests you can take a look at WebGoatIT.java

**Comment by span** [comment]
When working on the vagrant setup process I was attempting to use the `master` branch instead of develop since these would be more stable. I then noticed that the master branch of WebGoat-Lessons was throwing this error even when building towards the `master` branch of WebGoat (the lesson server).

Surely, the branches should be matching. Did you have a previous commit that solved this @nbaars? Would it be possible to merge it to `master` for this lesson?

**Comment by span** [comment]
I am still having this issue in the master branch.

```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.331 s
[INFO] Finished at: 2016-11-21T18:20:57+01:00
[INFO] Final Memory: 67M/704M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project path-based-access-control: Compilation failure: Compilation failure:
[ERROR] /Users/daniel-op/security/WebGoat-Lessons/path-based-access-control/src/main/java/org/owasp/webgoat/plugin/PathBasedAccessControl.java:[111,65] cannot find symbol
[ERROR] symbol:   method isDefuseOSCommands()
[ERROR] location: class org.owasp.webgoat.session.WebgoatContext
[ERROR] /Users/daniel-op/security/WebGoat-Lessons/path-based-access-control/src/main/java/org/owasp/webgoat/plugin/PathBasedAccessControl.java:[112,44] cannot find symbol
[ERROR] symbol:   method isDefuseOSCommands()
[ERROR] location: class org.owasp.webgoat.session.WebgoatContext
```
