### ISSUE TITLE
Create tutorials / movies for WebGoat 7

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#249]
We should think about adding some movies/tutorials for WebGoat:
- Installing / running it
- Walkthrough of the options
- Basic proxy setup with Burp / ZAP
- .....

There are some on YouTube but most of them are on the old version.

**Comment by b1rd0fb3auty14** [comment]
@nbaars I can help with this. What do I need to do?

**Comment by jetweelim** [comment]
i have a playlist on this. hope it helps.

https://www.youtube.com/playlist?list=PLrHVSJmDPvlonRjsBirl5Ch5ejTGRNWBd

best regards,

**Comment by b1rd0fb3auty14** [comment]
Thank you for the response @jetweelim.
@nbaars - If you want something similar to what @jetweelim has posted then I can do that with:
1. Installing WebGoat
2. Using Zap Proxy
3. Walkthrough of options

Let me know. Thanks!

**Comment by nbaars** [comment]
@b1rd0fb3auty14 great! the ones you propose would be perfect for people to get started with WebGoat.

**Comment by b1rd0fb3auty14** [comment]
thanks @nbaars for the response! I am getting a weird error when I try to download the easy jar: https://s3.amazonaws.com/webgoat-war/webgoat-standalone-7.0.1-exec.jar

I am getting the following error:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>webgoat-standalone-7.0.1-exec.jar</Key>
<RequestId>55B2E188F31B58A4</RequestId>
<HostId>
voEm2+pmqwbw1pAufy3jx3e/a3/s9J/MWhahTQCrybopkCMGRTycTi8XfGiGm6jsG0QdSt8i6Hw=
</HostId>
</Error>

**Comment by b1rd0fb3auty14** [comment]
"<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>webgoat-standalone-7.0.1-exec.jar</Key>
<RequestId>55B2E188F31B58A4</RequestId>
<HostId>
voEm2+pmqwbw1pAufy3jx3e/a3/s9J/MWhahTQCrybopkCMGRTycTi8XfGiGm6jsG0QdSt8i6Hw=
</HostId>
</Error>
"

**Comment by b1rd0fb3auty14** [comment]
<Error>
<Code>NoSuchKey
<Message>The specified key does not exist.</Message>
<Key>webgoat-standalone-7.0.1-exec.jar</Key>
<RequestId>55B2E188F31B58A4</RequestId>
<HostId>
voEm2+pmqwbw1pAufy3jx3e/a3/s9J/MWhahTQCrybopkCMGRTycTi8XfGiGm6jsG0QdSt8i6Hw=
</Error>

**Comment by dougmorato** [comment]
Also found some interesting link: http://webappsecmovies.sourceforge.net/webgoat/

**Comment by dougmorato** [comment]
@nbaars @mayhew64 @misfir3 We should discuss if this should be included in "lesson solution" under the UI

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
