### ISSUE TITLE
User Info/Logout Links 

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#25]
See the Webgoat 6.0.1 release for how it should behave, how it was set up. The 'user' icon should show the 'current user' (usually just 'guest' still) and the log out link. Image included below.

![image](https://cloud.githubusercontent.com/assets/5103241/9370590/77860724-469f-11e5-947c-0ad42291e781.png)

**Comment by nbaars** [comment]
Added bootstrap/jquery dependencies to `main_new.jsp` and added element in div for toggle data. Works again.
