### ISSUE TITLE
Executable jar crashes if empty .extract folder exist

### ISSUE THREAD

**Issue by kjarnet** [WebGoat/WebGoat#251]
If an empty/faulty .extract folder exist where you execute the jar (e.g. from a previous failed attempt), you get a FileNotFoundException looking for .extract/webapps/WebGoat.war. This caused me a lot of headache finding out, and would be nice if it could be documented or fixed.

**Comment by nbaars** [comment]
@kjarnet Added this to the FAQ, see https://github.com/WebGoat/WebGoat/wiki/FAQ#exec-war
Thanks for the input!
