### ISSUE TITLE
Copy lessons into plugin_lessons

### ISSUE THREAD

**Issue by remrobem** [WebGoat/WebGoat#254]
On the https://github.com/WebGoat/WebGoat page,

I am trying to install on Windows 10,
cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/
does not work.
This seemed to work:
xcopy "target\plugins\*.jar" "C:\WebGoat\webgoat-container\src\main\webapp\plugin_lessons\"

**Comment by mayhew64** [comment]
Yes. cp is a UNIX command. Thanks, I'll update for Windows. We're there any other gotchas?

**Comment by remrobem** [comment]
I don't think so. I didn't have much time to get into it. But I did notice
the solution was missing on one lesson I looked at. I was expecting it to
show the code change to fix it but my expectations might be wrong. I still
need to read up on it this weekend and play around with it. Thanks for all
your efforts on this.

Rob

**Comment by nbaars** [comment]
Updated the documentation for Windows.
