### ISSUE TITLE
LAB: Role Based Access Control

### ISSUE THREAD

**Issue by nnh100** [WebGoat/WebGoat#255]
Hi, 

I have installed the Developer version (using webgoat_developer_bootstrap.sh) and can get to most lessons fine but when I try to open the Access Control Flaws -> LAB: Role Based Access Control I get the following error:

Error Message: javax.servlet.ServletException: File "/plugin_extracted/plugin/RoleBasedAccessControl_i/jsp/RoleBasedAccessControl_i.jsp" not found

I have tried cloning the lessons and copying the lessons over that way but I still get the same message.

Any idea where I'm going wrong?

thanks

**Comment by nbaars** [comment]
I think this is due to the fact that the _i.class files are also packaged in the jar. Those might be picked up as well. Fixed this by excluding the *_i.java in the compiler plugin.

**Comment by nbaars** [comment]
Fixed, on develop branch

**Comment by nnh100** [comment]
Hi @nbaars, sorry I didn't get round to testing the fix but thanks for looking into it.
