### ISSUE TITLE
Code does not compile on dev branch

### ISSUE THREAD

**Issue by RubieV** [WebGoat/WebGoat#258]
During testing of unit testing of the CI server, Maven fails at:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project path-based-access-control: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/WebGoat/WebGoat/WebGoat-Lessons/path-based-access-control/src/main/java/org/owasp/webgoat/plugin/PathBasedAccessControl.java:[111,65] cannot find symbol
[ERROR] symbol:   method isDefuseOSCommands()
[ERROR] location: class org.owasp.webgoat.session.WebgoatContext
[ERROR] /home/travis/build/WebGoat/WebGoat/WebGoat-Lessons/path-based-access-control/src/main/java/org/owasp/webgoat/plugin/PathBasedAccessControl.java:[112,44] cannot find symbol
[ERROR] symbol:   method isDefuseOSCommands()
[ERROR] location: class org.owasp.webgoat.session.WebgoatContext

**Comment by b1rd0fb3auty14** [comment]
https://github.com/WebGoat/WebGoat/issues/247

refer to the link above

**Comment by RubieV** [comment]
Closed in favor of #247

**Comment by nbaars** [comment]
Fixed, Travis build script was using the master branch of WebGoat-Lessons instead of develop.
