### ISSUE TITLE
Amazon S3 downloadable JAR is missing

### ISSUE THREAD

**Issue by lokori** [WebGoat/WebGoat#259]
The executable JAR is not available at the S3 Bucket as advertised: https://s3.amazonaws.com/webgoat-war/webgoat-standalone-7.0.1-exec.jar is missing.

**Comment by b1rd0fb3auty14** [comment]
Was progress made on this issue? I have another issue that I am working on - creating tutorial videos for OWASP and I wanted to use the standalone jar. @nbaars @mayhew64 @misfir3

**Comment by nbaars** [comment]
webgoat-standalone*-exec.jar is part of the 7.1 release and is at the moment only available in the develop branch. The S3 bucket only contains the master releases. We will release a new release so this file will appear when develop is merged to master.

For 7.0 you can use: webgoat-container-7.0-SNAPSHOT-war-exec.jar 

If you want to run the new standalone jar you need to checkout the develop branch.

**Comment by b1rd0fb3auty14** [comment]
Thanks for the prompt response, @nbaars!
