### ISSUE TITLE
Re-enable/update WebGoat Info link

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#26]
This should be updated and re-enabled with the changes in Backbone. Should be pretty straightforward to re-enable. See image below

![image](https://cloud.githubusercontent.com/assets/5103241/9370644/c8ad4b3a-469f-11e5-8b6d-b8619a96f1f7.png)

**Comment by nbaars** [comment]
Fixed, enabled again (available in pull request)
