### ISSUE TITLE
Developer edition build isn't working in its entirety

### ISSUE THREAD

**Issue by krvw** [WebGoat/WebGoat#260]
Greetings WebGoat team,

Hey, I use WebGoat 7.1 (latest) a lot. In the past, I've followed the instructions on the main page for cloning the two git trees and building the system. Today, I see that things compile and build, but I'm only seeing a small subset of the lessons show up in my jar file. Many of the lessons are missing (e.g., sql-injection, stored-xss...).

Did something major change and I'm not aware?

FWIW my download and build script looks like the following:

git clone https://github.com/WebGoat/WebGoat.git
git clone https://github.com/WebGoat/WebGoat-Lessons.git

cd WebGoat
mvn clean compile install
cd ../WebGoat-Lessons
mvn package
cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/
cd ..

cd WebGoat
mvn -pl webgoat-container tomcat7:run-war

I'm running this on an Ubuntu LTS 14.01 system at this point.

Any tips on what I'm doing wrong? Thanks!

Cheers,

Ken van Wyk

**Comment by misfir3** [comment]
what do you see when you
$git branch
... in each directory? And ...
$ git status

**Comment by krvw** [comment]
OK, so I've gone back now and cleanly rebuilt my entire WebGoat env. It built fine, and all exercises are present, so this was probably pilot error on my part.

What still baffles me, though, is what went wrong. I ran the same script I always do, but when I run the build commands (per the instruction page), all worked.

So, it's no doubt my fault. Sorry for the false alarm.

Cheers,

Ken

**Comment by misfir3** [comment]
Personally, I'd blame maven. But that's just me ... :)
