### ISSUE TITLE
Add new lesson for XXE

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#263]
A new lesson for XXE should be added to WebGoat.

**Comment by nbaars** [comment]
Lesson is now available, see xxe

**Comment by misfir3** [comment]
Pulled it. Noted the double-call and some other conflicting issues with the SPA set-up.  Looking to modify the the Ajaxification (w/o breaking everything else 😄 ) ... to make it more flexible to support lessons  like this (which will be important in 8+) and make this one work better for 7.1.

**Comment by misfir3** [comment]
For this next 'maintenance' release, should make the return content, an html fragment like the other lessons to avoid extra work on the client to accommodate the json return type.

**Comment by nbaars** [comment]
Part of 8.0
