### ISSUE TITLE
Provide Server-side service to support UI localization

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#265]
Implement a simple map/service to provide localizations for UI labels

**Comment by nbaars** [comment]
- UI is implementend see #289 

We still need:
- adoc translation (so loading the correct adoc based on the language)
- html for the attacks processed by Thymeleaf

**Comment by nbaars** [comment]
Fixed the html part. Thymeleaf now works with i18n

**Comment by nbaars** [comment]
Closing, done
