### ISSUE TITLE
Update LessonMenuService to provide proper status

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#269]
Looked into the UI update issue. It is reading the lesson's returned status as completed in the JSON response. This triggers a refresh on the MenuView appropriately.

The LessonMenuService is showing the lesson complete status as false. That service is still wired up to the 'WebSession', which may be why.

@nbaars, let's discuss how we want to move this forward.

**Comment by nbaars** [comment]
solved there was a typo in the js file (lessonComplete whereas the json passed lessonCompleted). The UI now gets automatically updated after you solve the lesson completely

**Comment by misfir3** [comment]
had changed that locally as well, but didn't get/see the updates ... will check in a little later.

**Comment by misfir3** [comment]
See screenshot. The initial response indicates the lesson is completed, but the lessonMenuService when it responds indicates that lesson is not complete.
![image](https://cloud.githubusercontent.com/assets/5103241/20331735/54a0d356-ab75-11e6-9ee3-98f7cd14b68e.png)
 
As an aside ... even when I do only the first assignment in the HttpBasics Lesson, the JSON response indicates `lessonCompleted:true`

Where is a user's lesson completion status (state) maintained now?

**Comment by nbaars** [comment]
Implemented, closing the issue
