### ISSUE TITLE
Category click should load a static category page.

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#274]
In addition to opening the lesson menu the category click should load a page defining the category of problem.  We could do something simple like have a pass through to another site or custom content.  For example for injection flaws:

++++
<p>
Content in a passthrough block is passed to the output unprocessed.
That means you can include raw HTML, like this top ten page:
</p>

<script src="https://www.owasp.org/index.php/Top_10_2013-A1-Injection">
</script>
++++

**Comment by span** [comment]
I have had a brief glance at this and perhaps we can add a template/html-file to each `Category`. Will dig around a bit and see if any better ideas come up.

**Comment by misfir3** [comment]
At a basic level, we should add a route for it and have that click handle/navigate to the route

**Comment by span** [comment]
Oh absolutely. I just feel weird to hardcode templates into the front-end since we are defining categories in the back-end. However, if you have no issue with keeping the back-end out of it for now I don't mind (_although it itches_ :P)

**Comment by span** [comment]
Hmm, not sure I understand the scope of this any more :P

I've added href's to the categories based on their ID and ending with `.category` to keep consistency with the lessons.

I've added a route that handles these clicks with a new `CategoryController` that is passed a `CategoryView` and instantiates a `CategoryModel` (the same flow as for the lessons).

Now, I was hoping to be able to store `.adoc` files with the other templates to fetch the content from and then render that content into the `CategoryView`.

Is this what you had in mind? If so, how would you configure the backend to get the content of the `.adoc` files and map it to the `.category` contents?

I've had a look at the `MvcConfiguration` class but can't really figure this last bit out.

**Comment by misfir3** [comment]
Sounds like a good approach overall on it and extends the existing pattern.  Will have to look into this later, maybe pick @nbaars  brain some

**Comment by nbaars** [comment]
Old issue, no longer relevant
