### ISSUE TITLE
Automatic lesson summary page

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#276]
At the end of each lesson on the final pagination a summary view should load.

You have completed SQL Injection
attack 1 - success
attack 2 - failed
attack 3 - success

Where the attack name should be taken from the attack endpoint.

**Comment by misfir3** [comment]
let's chat (after this next week) about how we want to implement this ... a fixed (summary) endpoint for each lesson? Level of detail? ... ???

**Comment by nbaars** [comment]
It can be one endpoint. In the lesson tracker we know exactly the list of assignments and if they were successful or not. The overview can be generated from this page. 

Extra feature: the overview should link to the new mechanism of getting to a specific screen. So http://localhost/WebGoat/SqlInjection.lesson/4 
so users can easily jump to the attack they did not yet complete.

**Comment by nbaars** [comment]
Navigation is also working

**Comment by nbaars** [comment]
Now available as button next to 'Hints' we can easily move it to the last page if necessary.
