### ISSUE TITLE
WebGoat-standalone-7.1.jar = Invalid Session

### ISSUE THREAD

**Issue by jitsoftdeveloper** [WebGoat/WebGoat#280]
I have downloaded "webgoat-standalone-7.1-SNAPSHOT-exec.jar" [https://s3.amazonaws.com/webgoat-war/webgoat-standalone-7.1-SNAPSHOT-exec.jar](url) in kali linux virtual machine, everything setup correct but when i try to login in browser after entering username & password it says "invalid sessions". How can i correct this error ? please tell me

**Comment by jitsoftdeveloper** [comment]
Can't anyone help me ?

**Comment by misfir3** [comment]
Same error message has happened before (see https://github.com/WebGoat/WebGoat/issues/44). Can you provide the url you are seeing when this happens?

**Comment by nbaars** [comment]
@jitsoftdeveloper please download the official released version from the this location: https://github.com/WebGoat/WebGoat/releases/download/7.0.1/webgoat-container-7.0.1-war-exec.jar

**Comment by jitsoftdeveloper** [comment]
Thank you so much, new version is working perfectly fine

**Comment by jitsoftdeveloper** [comment]
Thank you so much, latest version is working perfectly fine
