### ISSUE TITLE
Master branch mismatch

### ISSUE THREAD

**Issue by span** [WebGoat/WebGoat#281]
The pom.xml in WebGoat-Lessons `master` still points to the snapshot build for 7.1. There is also #247 which prevents a clean build of both `WebGoat` and `WebGoat-Lessons` using the `master` branch.

**Comment by dougmorato** [comment]
All pre-conditions met for closing the issue. 

Master branches now point to stable WebGoat 7.1

**Comment by span** [comment]
Actually the merge is still missing in #247 so this is still not working all the way. I am not sure why @nbaars closed it.
