### ISSUE TITLE
Update DEVELOP branch README

### ISSUE THREAD

**Issue by dougmorato** [WebGoat/WebGoat#284]
Given the new release, we need to update instructions and links on the DEVELOP branch

**Comment by vdbaan** [comment]
Current instructions break webgoat, I would relabel it from enhancement to something more critical as no new developers can build this environment.

**Comment by misfir3** [comment]
I did a quick update of this, but had to include -DskipTests temporarily (and noted as much). @nbaars is going to look at the breakage (w/o skipping tests) later.

Apologies and thanks @vdbaan

**Comment by misfir3** [comment]
Did some more patch updates, but we need to differentiate (and check) 7.x and 8.x links and notes.

**Comment by domflannery** [comment]
In the README for the develop branch, the instructions for Easy are a bit confusing. Under step 1 for setting up Docker, it then says go to step 3. There are currently two step 3's, one to run the jar and the other to go to the url. I'm assuming that if you are using a Docker container, that you wouldn't also need to manually run the jar.

**Comment by nbaars** [comment]
Updated the README of the development branch removed duplicate information we already host on the Wiki. The README now only gives information on how to start WebGoat 8.0. No longer a mix of content.
