### ISSUE TITLE
Remove really old docs from OWASP Wiki

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#290]
At least this one ... pretty old! Should do it by WebGoat 8 release.

https://www.owasp.org/index.php/WebGoat_User_and_Install_Guide_Table_of_Contents
https://www.owasp.org/index.php/WebGoat_Installation

**Comment by b1rd0fb3auty14** [comment]
Hey @misfir3 - I can work on this! Is the WebGoat 8 release ready to develop?

**Comment by misfir3** [comment]
Yes, needs to update for WebGoat 8. develop branch is now 8.0-SNAPSHOT

**Comment by b1rd0fb3auty14** [comment]
Hey @misfir3 - I have scanned the code base (master and develop) and I do not see the pages listed in the current 8.0 SNAPSHOT.

I did a scan on WebGoat_Installation, WebGoat_User_and_Install_Guide_Table_of_Contents, and index.php.

Can you provide some assistance?

Thanks!

**Comment by misfir3** [comment]
haven't you essentially done this @nbaars ?

**Comment by Elphnek** [comment]
Hey guys, I've been trying to install the WebGoat since yesterday - like literally didn't got any sleep on this.
I've tried to install on Kali Linux os, with no luck at all. 
please please please - update the instructions. please.

**Comment by nbaars** [comment]
OWASP moved to new page so this documentation is now up-to-date
