### ISSUE TITLE
mvn package Output not going to target/plugins

### ISSUE THREAD

**Issue by honk3x** [WebGoat/WebGoat#292]
I'm pretty new to opensource tools/JAVA. However, I pulled down the project through git about a month ago and was able run the project on tomcat without a ton of issues. I deleted everything and wanted to start fresh, now every time I get to the step below on the "Developer's Way" instructions: 

**(linux)   cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/**

Nothing happens and when I try to run on tomcat I get plugin errors. When I go to the physical location of target/plugins there are no jars. So for whatever reason the mvn package command is not placing them in this directory. 

What am I doing wrong here?

**Comment by klebertiko** [comment]
Hi @honk3x 

I just did like this:

git clone https://github.com/WebGoat/WebGoat.git
git checkout develop
git checkout -b 7.1
git checkout tags/7.1
cd WebGoat
mvn clean compile install

git clone https://github.com/WebGoat/WebGoat-Lessons.git
cd WebGoat-Lessons
git checkout develop
mvn package
cp target/plugins/*.jar ../WebGoat/webgoat-container/src/main/webapp/plugin_lessons/

URL: http://localhost:8080/WebGoat

cd WebGoat
mvn -pl webgoat-container tomcat7:run-war


I hope it helps o/

**Comment by misfir3** [comment]
Those instructions will work for the 7.x build/releases.

We have moved the develop branch now to the 8.0-SNAPSHOT, but were slow updating the README (and it still needs some more work ... apologies!)

@honk3x  - 8.0 is still in major transition/work. 7.x is more stable. What's your goal with WebGoat?

**Comment by nbaars** [comment]
The README.md has been updated the copy steps are no longer part of it therefore closing this issue
