### ISSUE TITLE
Create IDOR lesson

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#304]
working on this already, but creating ticket to track and link commits

**Comment by misfir3** [comment]
@nbaars do you mind trying this lesson out and seeing if you can tell why the 400 when I do the IDOR/profile/{userId} via PUT method. I still plan to refine the lesson some, but going to work some other minor issues first and then come back to it.

**Comment by nbaars** [comment]
@misfir3 Should work now, the put mapping was using @RequestParam instead of @RequestBody which needs to be used when posting JSON.

**Comment by misfir3** [comment]
Gahhhh!  Why I need to either spend more time doing Java work or be completely disbarred from doing it! ;-)  Thanks!

**Comment by nbaars** [comment]
Lesson is available, closing this one.

**Comment by misfir3** [comment]
Need to complete hints on this lesson (cc @jl2035). Reopening

**Comment by misfir3** [comment]
Hints working aside from the general issue noted in #352

**Comment by freetest** [comment]
@misfir3  

hello , when i use IDOR.lesson/4

submit View Profile button

the url is http://127.0.0.1:8080/WebGoat/IDOR/profile/**%7BuserId%7D**

not use my userid  just a string "{userid}"  how can i fix it?

@AssignmentPath("IDOR/profile/{userId}")

    @RequestMapping(produces = {"application/json"}, method = RequestMethod.GET)
    @ResponseBody
    public AttackResult completed(@PathVariable("userId") String userId, HttpServletResponse resp)

**Comment by misfir3** [comment]
It is intended for you to use the proxy to modify the request. This is the one where you are supposed to find the other user's profile, correct? If so, you'll want to fuzz ... manually or using the proxy's fuzzing capability.

**Comment by freetest** [comment]
thanks .  if . i want the {userId} use the current login user userid . 

how can i code the assignmentpath?
