### ISSUE TITLE
can't login to webgoat

### ISSUE THREAD

**Issue by krzysztof-balas** [WebGoat/WebGoat#307]
when I try to log in with developer version there's an error:
```
Servlet.service() for servlet [dispatcherServlet] in context with path [/WebGoat] threw exception
 [Request processing failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
'scopedTarget.userTracker' defined in org.owasp.webgoat.WebGoat: Bean instantiation via factory 
method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to 
instantiate [org.owasp.webgoat.session.UserTracker]: Factory method 'userTracker' threw 
exception; nested exception is java.lang.IllegalArgumentException: Failed to deserialize object] with 
root cause

java.io.InvalidClassException: org.owasp.webgoat.lessons.Assignment; local class incompatible:
stream classdesc serialVersionUID = 7331152777633956996, local class serialVersionUID = 
5783932191279419790
```

**Comment by misfir3** [comment]
what version is this with ... 7.1?

**Comment by krzysztof-balas** [comment]
v 8.0.
I followed steps from "The Manual Way: Developer Edition!" section.

**Comment by misfir3** [comment]
So, you are doing ... ?
`cd WebGoat`
`git checkout develop`
`mvn clean package`
`mvn -pl webgoat-container spring-boot:run`
... right?

(if not, git pull and try that again)

Otherwise, can you provide anymore stackTrace and/or details about your environment?

**Comment by nbaars** [comment]
Can you remove the ~/.webgoat/guest.progress file? (it is in you home directory in the .webgoat directory)

**Comment by nbaars** [comment]
Changed the code to generate new lesson tracker if we are unable to read the previous one. During development this might happen if we refactor some classes

@krzysztof-balas can you update and try again? And open the issue if the problem is still present? Thanks.

**Comment by krzysztof-balas** [comment]
Works fine now. Thanks. :)
Cheers.
