### ISSUE TITLE
Enable i18n client side

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#312]
For the json part we can introduce an interceptor which will try to translate labels (you can recognize them through values which look like `a.b.c.d` and which have a match in the `WebGoatLabel.properties` file.

This way we do not have to extend all endpoints to do this explicitly.

**Comment by zupzup** [comment]
The way the **LabelService** was implemented in https://github.com/WebGoat/WebGoat/pull/289, endpoints wouldn't have to be extended - the UI would fetch the whole set of relevant labels and then do the replacement on the client.

**Comment by nbaars** [comment]
Great, will take a look to incorporate #289 for the hints per assignment

**Comment by nbaars** [comment]
Changed title as with #289 we receive the labels client side we need to implement the translation client side.

**Comment by nbaars** [comment]
For now introduced polygot.js which seems to do the job, you can use polyglot.t(....) to translate keys to text. See HintView and MenuView for examples.

**Comment by nbaars** [comment]
Closing as we can now use i18n client side
