### ISSUE TITLE
Copyright header not correct

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#321]
Following issues:

- Copyright contains link to http://webgoat.github.io/ which no longer exists.
- Not all source files contain a copyright
- The location in the source file is not consistent
- Year is not correct, it contains:  **20014**
- Add a complete license file (COPYING) at the top level directory
- Authors tag contains reference to old webgoat repository, we should delete the link

Proposal would be to move the copyright before the package level and level the @author and @created at class level. At the moment the complete copyright text at class level clutters the class level comments.

The following text should be used across source files before the package statement:

```
/**
 * This file is part of WebGoat, an Open Web Application Security Project
 * utility. For details, please see http://www.owasp.org/
 *
 * Copyright (c) 2002 - 2017 WebGoat Development Team
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place - Suite 330, Boston, MA 02111-1307, USA.
*/
```

And create a NOTICE file with:

```
COPYRIGHT

OWASP WebGoat

The software package is:

Copyright © 2010-2017 WebGoat Development Team
Individual contributions, components, and libraries are copyright of their respective authors.
```

**Comment by maximmasiutin** [comment]
I have created a pull request https://github.com/WebGoat/WebGoat/pull/935 aimed to fix the copyright year and the webgoat.github.io link.
