### ISSUE TITLE
Error after login to webgoat multiple versions

### ISSUE THREAD

**Issue by sierratango68** [WebGoat/WebGoat#327]
I am getting a java error after logging into Webgoat.

Using Windows 10 Pro
Firefox browser ver 32.0.3, 41.x.x, 51.0.1
Chrome 56.0.2924.87

Webgoat versions: WebGoat-6.0.1-war-exec, webgoat-container-7.0.1-war-exec, webgoat-container-7.1-exec
Command line: C:\>java -jar .\webgoat-6.0.1-war-exec.jar -httpPort=8081

I navigate to: http://localhost:8081/WebGoat
I get the login page and login as either guest or admin.
Then I get a progress spinner in the left hand side of the page and a java error (copied from cmd, also in webpage)

2017-02-12 23:59:39,599 DEBUG - Loading source file: C:\.extract\webapps\WebGoat\plugin_extracted\org\owasp\webgoat\plugin\HowToWork.java
2017-02-12 23:59:39,572 DEBUG - Leaving doPost:
Feb 12, 2017 11:59:39 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [mvc-dispatcher] in context with path [/WebGoat] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.owasp.webgoat.session.UserTracker]

**Comment by sierratango68** [comment]
FYI:  using tomcat 7.0.37 (this is what is packaged with the webgoat downloads.

**Comment by sierratango68** [comment]
Ok more info on which tomcat is being used.
WebGoat-6.0.1-war-exec, = tomcat 7.0.37
webgoat-container-7.0.1-war-exec = tomcat 7.0.59
webgoat-container-7.1-exec = 7.0.59

**Comment by sierratango68** [comment]
checked https://github.com/WebGoat/WebGoat/wiki/FAQ#tomcat
does not apply as I am using versions in the 7.x.x range

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
