### ISSUE TITLE
Lesson Interdependency

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#33]
This is more of a placeholder for something I think I noted last night and I need to play with some more.  Some lessons, even though they are in separate *.jar's, have (I believe) legacy inter-dependencies.  Don't know if we can/want to introspect a lesson *.jar when unpacking and determine that, but we may want to as I was getting the 'invalid session' last night which came back to a NoClassDefFound error (related to CSRF lessons).  I didn't grab the details at the moment, but some info may still be in my terminal scrollback. Will update once I can verify more about this.

**Comment by nbaars** [comment]
Yes this was an issue for the Goathills challenges in which the classes were in the same package and with the same name. I added an extra package might be necessary between other lessons as well.

Will write a test to see if this is the case somewhere else.

**Comment by nbaars** [comment]
Fixed for the CSRF lesson some lessons share code but this should work with the classloading.
In this case both lessons extended the wrong superclass

**Comment by misfir3** [comment]
Stale ... closing
