### ISSUE TITLE
How to launch all kinds attacks in one script?

### ISSUE THREAD

**Issue by bali2016** [WebGoat/WebGoat#336]
Hi All,

I'm trying to test a WAF app capabilies, and I'm using WebGoat as the backend server. I want a script that can launch all kinds attacks in the lesson to the webgoat, so we want to know is there any exisiting tools or scripts can do this? 
If not, then I need to retirve all the WebGoat REST APIs that can be attacked in the lesson, so is there someone can tell me how to retrive all of those APIs?

Thanks,
Bali

**Comment by misfir3** [comment]
Denim Group (I think) had a plugin (burp/zap) that would enumerate APIs to help with scanning (using the source). Search "dan cornell abc source-assisted pen testing"
