### ISSUE TITLE
WebGoat 7.1 Docker Challenge Stage 3

### ISSUE THREAD

**Issue by tomekr** [WebGoat/WebGoat#344]
It appears that after finishing stage 2 of the challenge the application breaks when trying to render stage 3. Here is the log output from docker:

https://gist.githubusercontent.com/tomekr/780064c917871940050bf9cf65a8961f/raw/43918828acd0b3fafb66a8f3993552c50e63a31f/webgoat_docker.log

And here is a screenshot of what is rendered after clicking the "Proceed to the next stage...(3)" button:

![screen shot 2017-04-08 at 1 22 30 pm](https://cloud.githubusercontent.com/assets/723637/24831406/776e3414-1c5e-11e7-87a0-d405e8286b82.png)

It appears there may be an issue with the output coming from netstat on the docker container?

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
