### ISSUE TITLE
Importing WSDL from url : how to authenticate ?

### ISSUE THREAD

**Issue by Open-Sec** [WebGoat/WebGoat#347]
Maybe this is not an issue, but, trying to import WSDL files using the URL fails because required authentication.
In previous WebGoat version, basic authentication was used and tools like SoapUI ask for credentials, but, current stable version uses j_spring_security_login via login.mvc.
The easy solution is to save the WSDL and import the file, set the cookie JSESSIONID and so on.
Is there anyway to import the WSDL from the URL ?

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
