### ISSUE TITLE
Encoding (?) issue in polyglot/hints

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#350]
the hint:
xxe.hints.simple.xxe.4=Try to include a doctype (<!DOCTYPE...) in the xml
show as ...
![image](https://cloud.githubusercontent.com/assets/5103241/25897805/5803ab9a-3581-11e7-947c-4d5f652126c0.png)

Likely some encoding issue with polyglot. Look into resolution with polyglot or a replacement

**Comment by nbaars** [comment]
Fixed
