### ISSUE TITLE
No guide on adding lessons to WebGoat 8

### ISSUE THREAD

**Issue by Zygro** [WebGoat/WebGoat#353]
I would like to contribute with remaking some lessons from the version 7 to version 8, However, I have great difficulty making a new lesson that would be displayed properly. Short guide would be much appreciated.

**Comment by nbaars** [comment]
Hi @Zygro 

You are correct, we are currently at the OWASP AppSEC EU Conference and working on getting a sample lesson in which you can use to create a new lesson. Hopefully we have this finished shortly.

Thanks for the feedback,
--Nanne

**Comment by misfir3** [comment]
AppSec EU was busier than anticipated for me (Summit and beyond), but hope to get this completed in the next couple weeks. Thanks @zygro for wanting to contribute!

**Comment by misfir3** [comment]
@Zygro - later than hoped, but there is now a webgoat-lessons/webgoat-lesson-template directory with sample files etc.  Still fairly basic, but should help. Start at the getting-started.txt file in the root of that directory (https://github.com/WebGoat/WebGoat/blob/develop/webgoat-lessons/webgoat-lesson-template/getting-started.txt) and let me know where it works and where it doesn't and we will update accordingly.

**Comment by magicansk** [comment]
Hi @Zygro @nbaars @misfir3,

Here to help! 
I would like to contribute.
Start with the webgoat-lessons/webgoat-lesson-template directory. 
Any further, please let me know.

Thanks

**Comment by nbaars** [comment]
Lesson is part of 8.0, closing
