### ISSUE TITLE
 mvn dependency:tree fails

### ISSUE THREAD

**Issue by gpsymantec** [WebGoat/WebGoat#356]
[INFO] ------------------------------------------------------------------------
[INFO] Building webgoat-plugins-parent 8.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WebGoat Parent Pom ................................. SUCCESS [  0.630 s]
[INFO] webgoat-container .................................. SUCCESS [  0.494 s]
[INFO] webgoat-plugins-parent ............................. FAILURE [  0.047 s]
[INFO] challenge .......................................... SKIPPED
[INFO] client-side-filtering .............................. SKIPPED
[INFO] cross-site-scripting ............................... SKIPPED
[INFO] http-basics ........................................ SKIPPED
[INFO] http-proxies ....................................... SKIPPED
[INFO] jwt ................................................ SKIPPED
[INFO] sql-injection ...................................... SKIPPED
[INFO] xxe ................................................ SKIPPED
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-server ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.064 s
[INFO] Finished at: 2017-06-12T14:44:10-07:00
[INFO] Final Memory: 39M/305M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webgoat-lessons-parent: Could not resolve dependencies for project org.owasp.webgoat.lesson:webgoat-lessons-parent:pom:8.0-SNAPSHOT: The following artifacts could not be resolved: org.owasp.webgoat:webgoat-container:jar:8.0-SNAPSHOT, org.owasp.webgoat:webgoat-container:jar:tests:8.0-SNAPSHOT: Could not find artifact org.owasp.webgoat:webgoat-container:jar:8.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :webgoat-lessons-parent

**Comment by nbaars** [comment]
@gpsymantec: Correct, you will need to run `mvn install` first. The lessons depend on the container so the jar needs to be there before Maven can continue
