### ISSUE TITLE
Port or create a new lessons for Authentication & Sessions

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#363]
Cookies (logout, create-a-cookie)

**Comment by misfir3** [comment]
I'd say for 8.0, just finish JWT (if not push that to 8.1) ... once stabilized and released, we can add content.

**Comment by misfir3** [comment]
@nbaars - I added the authent. (password reset) bypass. Good enough for 8.0 or we need something more?

**Comment by nbaars** [comment]
@aolle think we can close this issue since you added the `spoof cookie` lesson?

**Comment by aolle** [comment]
@nbaars yes, can be closed.
