### ISSUE TITLE
DOM Injection Lesson - Java Source does not work 

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#37]
Clicking on the JavaSource Button Generates a 
```SyntaxError: missing ; before statement
" + lineSep + "function validate() {" + lineSep```
in the javascript console.

**Comment by nbaars** [comment]
- Extracted the JavaScript.
- Fixed the lesson, the submit no longer generates a POST so needed to change the success case.

**Comment by nbaars** [comment]
Waiting on pull request
