### ISSUE TITLE
HTTP Status 500 - Unable to compile class for JSP

### ISSUE THREAD

**Issue by prometx** [WebGoat/WebGoat#376]
When starting the standalone .jar package, it seems to successfully start in the terminal output, but upon navigating to http://localhost:8080/WebGoat I receive the below tomcat error(s):

Has anyone else seen a similar issue?

`HTTP Status 500 - Unable to compile class for JSP:

type Exception report

message Unable to compile class for JSP:

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.util.Map cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.lang.Long cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.io.IOException cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.lang.Exception cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.lang.Throwable cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.util.Enumeration cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [1] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files

An error occurred at line: [15] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The hierarchy of the type index_jsp is inconsistent

An error occurred at line: [15] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The type index_jsp must implement the inherited abstract method JspSourceDependent.getDependants()

An error occurred at line: [21] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.util.Map cannot be resolved to a type

An error occurred at line: [21] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.String cannot be resolved to a type

An error occurred at line: [21] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.Long cannot be resolved to a type

An error occurred at line: [28] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.util.Map cannot be resolved to a type

An error occurred at line: [28] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.String cannot be resolved to a type

An error occurred at line: [28] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.Long cannot be resolved to a type

An error occurred at line: [29] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
_jspx_dependants cannot be resolved to a variable

An error occurred at line: [43] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.io.IOException cannot be resolved to a type

An error occurred at line: [43] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
No exception of type ServletException can be thrown; an exception type must be a subclass of Throwable

An error occurred at line: [49] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.Object cannot be resolved to a type

An error occurred at line: [55] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The method setContentType(String) from the type ServletResponse refers to the missing type String

An error occurred at line: [56] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The method getPageContext(Servlet, ServletRequest, ServletResponse, String, boolean, int, boolean) from the type JspFactory refers to the missing type String

An error occurred at line: 1 in the jsp file: /index.jsp
The type java.io.Writer cannot be resolved. It is indirectly referenced from required .class files
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

An error occurred at line: 1 in the jsp file: /index.jsp
The method write(char) is undefined for the type JspWriter
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

An error occurred at line: 1 in the jsp file: /index.jsp
The method write(char) is undefined for the type JspWriter
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

An error occurred at line: 3 in the jsp file: /index.jsp
The method write(char) is undefined for the type JspWriter
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

An error occurred at line: [69] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.Throwable cannot be resolved to a type

An error occurred at line: [75] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The method flush() from the type JspWriter refers to the missing type IOException

An error occurred at line: [77] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
The method clearBuffer() from the type JspWriter refers to the missing type IOException

An error occurred at line: [79] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.io.IOException cannot be resolved to a type

An error occurred at line: [81] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
No exception of type ServletException can be thrown; an exception type must be a subclass of Throwable

An error occurred at line: [89] in the generated java file: [/home/promet/Apps/Webgoat_7.1/.extract/work/Tomcat/localhost/WebGoat/org/apache/jsp/index_jsp.java]
java.lang.Throwable cannot be resolved to a type

An error occurred at line: 3 in the jsp file: /index.jsp
The method get(Class<? extends Tag>) from the type TagHandlerPool refers to the missing type Class
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

An error occurred at line: 3 in the jsp file: /index.jsp
The method setUrl(String) from the type RedirectTag refers to the missing type String
1: <%@ page session="false" %>
2: <%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
3: <c:redirect url="/login.mvc"/>

Stacktrace:
	org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:485)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.59 logs.`

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
