### ISSUE TITLE
Lessons not loading 

### ISSUE THREAD

**Issue by strax3** [WebGoat/WebGoat#382]
I am able to log into web goat but none of the lessons are showing. Please see log file. 
[webgoat_main.txt](https://github.com/WebGoat/WebGoat/files/1257742/webgoat_main.txt)

**Comment by strax3** [comment]
Was running on Java 9. Switching to Java 8 resolved this issue.

**Comment by misfir3** [comment]
Thanks for noting that ... WebGoat 7.1 or the current 8 Snapshot?

**Comment by strax3** [comment]
This was WebGoat 7.1
