### ISSUE TITLE
405 error in WSDL scanning lab.

### ISSUE THREAD

**Issue by cololadox2** [WebGoat/WebGoat#383]
When I enter the account number, select filed, and click on the Submit button in the corresponding lab page, the following error occurs.

AxisFault
 faultCode: {http://xml.apache.org/axis/}HTTP
 faultSubcode:
 faultString: (405) Method Not Allowed
 faultActor:
 faultNode:
 faultDetail:
    {}: return code: 405

The webgoat 5.4 developer version is fine. However, the 7.1 developer version has this error.

How do I fix it?

**Comment by nbaars** [comment]
Hi @cololadox2, thanks for the bug however we are not actively supporting 7.1 we are focusing on WebGoat 8 which will not contain this lesson anymore. Closing this one as won't fix.
