### ISSUE TITLE
Lesson Loading Scrolls down page in Firefox

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#39]
Tested FF and Chrome, but only noticed this in FF.

Anyone else noticing this?

**Comment by nbaars** [comment]
Tested on FF indeed it scrolls down, it seems like this is the same scrolling as it would when you click on Solution / Lesson plan.

**Comment by misfir3** [comment]
Should be closed after merging pull request 51

**Comment by nbaars** [comment]
Checked in Firfox and is fixed
