### ISSUE TITLE
Get Docker Image Pushed on Successful builds

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#396]
Need to get a docker image building/pushing on successful builds to avoid having to do so manually and getting tickets that have been fixed in develop, but not in the docker.

**Comment by nbaars** [comment]
Fixed, every develop build now pushes a snapshot tag to DockerHub
every tag build will push a tag with that version to DockerHub
a tag on master will push a new latest to DockerHub (and a tag with that version)
