### ISSUE TITLE
Introduction #3 - WebWolf Error

### ISSUE THREAD

**Issue by alancwoo** [WebGoat/WebGoat#403]
I'm running WebGoat and WebWolf (8.0.0-M2) as java jars in a vmware VM (on Ubuntu 16.04.3 LTS). When entering my webgoat 'email' (username@webgoat.org) into the field I get the following error:

![image](https://user-images.githubusercontent.com/1481890/32190959-bd183f94-bdaf-11e7-99b3-39ae6ec439dc.png)

*url: http://webgoat:8080/WebGoat/WebWolf/send*:
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Oct 30 20:16:46 CET 2017
There was an unexpected error (type=Not Found, status=404).
No message available
```
Have I misconfigured something?

**Comment by mario8x** [comment]
I got this issues too. I've been running by using command line `java -jar` for both webwolf and webgoat in Windows 10.

**Comment by nbaars** [comment]
Correct, the url was not correct. Fixed in release M4 which is in the process of releasing

**Comment by nbaars** [comment]
Release v8.0.0.M4 is out, this release contains a fix for this issue. @mario8x & @alancwoo can you try again? 

Thanks,
--Nanne

**Comment by alancwoo** [comment]
@nbaars Thank you, I can confirm this is fixed on my end!

**Comment by mario8x** [comment]
Thanks @nbaars , this issue was fixed.
