### ISSUE TITLE
Marking a lesson complete does not always work

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#405]
Sometimes it works for example http-basics lesson. For the SQL lesson it does not work.
Not sure but it looks like the endpoint is not responding with the correct lesson complete status.

**Comment by misfir3** [comment]
it's a brittle system overall ... something I'd like to find a way to address. It relies on the the progress response matching endpoints from jQuery client side queries/filters (in a nutshell).  Had to hack around this on at least one other lesson.  Flexibility vs stability going on here.

**Comment by nbaars** [comment]
For now fixed with polling for changes, it works but server side events/websockets will be a better fit. 
If a user finishes a lesson out of band (meaning not through WebGoat but for example by repeating the request from Firefox) the page navigation will be updated. Similarly when all lesson are completed the menu item will turn green as well.
