### ISSUE TITLE
I can't login in webwolf

### ISSUE THREAD

**Issue by jessusniww** [WebGoat/WebGoat#408]
I follows the section "Run from the sources",when I execute "mvn clean install"  and "mvn -pl webwolf spring-boot:run",then I enter the address "http://localhost:8081/WebWolf",Prompt me to enter the username and password,but I don't know where to get a username and password，help。

**Comment by jessusniww** [comment]
Now,I start the webgoat-container,I enter "http://localhost:8080/WebGoat",register a user,when I login ,encounter a error  like this "Fri Dec 01 11:02:52 CST 2017
There was an unexpected error (type=Internal Server Error, status=500).
Index: 0, Size: 0"

**Comment by pirent** [comment]
@jessusniww 
Did you check the console log? I guess you also get the error of "No lesson found" (aka Index:0, Size: 0)

**Comment by nbaars** [comment]
@jessusniww can you try: `mvn -pl webgoat-server/ spring-boot:run`?
This is a bug reported by @pirent as well and I've updated the bootstrap script on the release 8 branch. 

Let me know if you encounter other problems, closing for now please open the issue again if this does not solve your issue

--Nanne
