### ISSUE TITLE
Implement Loading Spinner on Menu

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#41]
It can take a moment to run/load (at least locally).  On initial menu load, implement spinner while menu loads.

**Comment by nbaars** [comment]
Indeed spinner would be a nice addition.

Noticed the same, loading of the plugins takes some time probably. I will investigate what's taking up most of the time and maybe implement some kind of caching if possible.

**Comment by span** [comment]
Is this an issue only with the menu or should the lesson content (and any other ajax loaded content) also have a spinner?

**Comment by misfir3** [comment]
@span - this was intended for the menu. Was thinking earlier today about need to specify that. Also, I have a commit that I will push to my fork (and issue a pull request on) [hopefully] tomorrow
