### ISSUE TITLE
Version: 8.0.0.M5 Character Encoding Issues

### ISSUE THREAD

**Issue by codeliger** [WebGoat/WebGoat#411]
I tried webgoat on the latest version of chrome and firefox and the instructions are messed up and impossible to understand.

SQL Injection Advanced:
> Special Characters
> 
> /* */ are inline comments — , # are line comments 'Select * from users where name = â€˜adminâ€™--and pass = â€˜passâ€™'
> 
> ; allows query chaining 'Select * from users; drop table users;'
> 
> â€™,+,|| allows string concatenation Char() strings without quotes 'Select * from users where name = â€˜+char(27) or 1=1'
> Special Statements
> 
> Unions allows overlapping of database tables 'Select id, text from news union all select name, pass from users'
> 
> Joins allows connecting to other tables

**Comment by nbaars** [comment]
Added extra encoding when transforming the asciidoc. Needs more testing seen this once before during a training probably happens when encoding on local machine is explicitly set

**Comment by nbaars** [comment]
@codeliger can you test it with our latest release: https://github.com/WebGoat/WebGoat/releases/tag/v8.0.0.M6 

Thanks,
--Nanne

**Comment by cr0sstalk** [comment]
@nbaars I'm still experiencing the encoding issues using v8.0.0.M6. I am using FF nightly. I'll check it out on Chrome and report back.

**Comment by nbaars** [comment]
Fixed the ` with normal quotes which we use in different lessons as well. 
Release pending

**Comment by ixe013** [comment]
@pjhggns, can/did you send a pull request to @nbaars? I could not find it. I would like to avoid using a fork just to fix a silly typo...

**Comment by pjhggns** [comment]
@ixe013,  I did not do a pull request for code related to this issue. I this the code is checked into
the main, and my commit was from syncing my fork in which I have been working on adding some new 
encoding lessons. [I haven't been able to work on it lately but expect to get back to it this week.]
Am I reading this correctly?

**Comment by nbaars** [comment]
@pjhggns you can use the `develop` or `release/v8.0.0` branch which contains this commit

**Comment by nbaars** [comment]
This fix is already part of an official V8 milestone release which can be downloaded. Looking at the answer above this solved the issue, closing. thanks @pjhggns for testing.
