### ISSUE TITLE
Unable to see buttons like HTTP request parameters, the HTTP request cookies, and the Java source code

### ISSUE THREAD

**Issue by samchughtai** [WebGoat/WebGoat#417]
I have installed and set up webGoat8.0.0.RELEASE.jar successfully. When I tried to login there were no in built users I registered my own user but now I am unable to see the button in HTTP basic lesson. Please check attachment and I am unable to find these buttons. Am I missing something?
![2018-01-03 20_08_51-webgoat](https://user-images.githubusercontent.com/35069518/34525848-25e44adc-f0c2-11e7-9ead-c4a712d57336.png)

**Comment by nbaars** [comment]
Removed the complete paragraph as it no longer reflects the way of working within WebGoat

**Comment by seanmahoney** [comment]
I'm having the same problem.  I just installed v8.0.0.M21 and the only buttons I have are 'show hints' and 'restart lesson'.  How can I resolve this?

**Comment by chloeblazey** [comment]
Was this ever resolved? I installed v8.0.0.M25 and have the same problem.

**Comment by anagfar** [comment]
So "Turn on Show Parameters or other features" does not really exists any more? Then why is still showing up on the hints?.

Thank you
