### ISSUE TITLE
Intro Lesson - Unable to send email to WebWolf 

### ISSUE THREAD

**Issue by strano666** [WebGoat/WebGoat#425]
I'm unable to send email to WebWolf in the Introduction Lesson.
The error is
`2018-01-20 16:40:55.225 ERROR 5137 --- [io-8080-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/WebGoat] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException: 500 null] with root cause`

It happens both with tar.gz release and with git version.

Furthermore, i dont know if it is relate to each other, but when i create a WebGoat User and then i try to log-in with same credentials in WebWolf, application tell me that the credentials are invalid.
So, for the email test, i've created the same user, with same credentials, in WebWolf.

**Comment by Sambsquanch** [comment]
Reproduced here as well. Not utilizing docker, utilizing .jar files. Problem occurs when entering e-mail to send to WebWolf, UI displays "Of course you can send mail to user sambsquanch however you will not be able to read this e-mail in WebWolf, please use your own username."

Also, WebWolf did not associate the credentials I entered into WebGoat and therefore had to register in WebWolf as well as WebGoat.

**Comment by nbaars** [comment]
Can you try version M8 this was indeed a bug.

Thanks for the report,
--Nanne

@Sambsquanch created a new issue to solve your second remark, we had this in the beginning but we internally used Mongo which gave a startup order between the applications. We moved to plain old SQL again this should no longer be a problem.

**Comment by nbaars** [comment]
Important: @strano666 and @Sambsquanch please first remove your `.webgoat` directory in your home directory

**Comment by strano666** [comment]
With M8 it's all ok!
