### ISSUE TITLE
Docker container running as non root

### ISSUE THREAD

**Issue by javixeneize** [WebGoat/WebGoat#435]
Hi

I am trying to run webgoat as a docker container in an environment that doesnt allow me to execute containers where i am the root user.

Is there any non-root version docker image for webgoat? 

Thanks

**Comment by nbaars** [comment]
@javixeneize not sure what you mean, if you want to run docker on your system as non-root you have to administer this on your system, see for example: https://docs.docker.com/install/linux/linux-postinstall/

Can you elaborate a bit more, what is the error you see in the console?

**Comment by nbaars** [comment]
Closing as we cannot reproduce, @javixeneize feel free to reopen the issue if you encounter the same problem
