### ISSUE TITLE
Error due to the capitalization of the first letter of the table name 'transactions' different in create, insert, drop statements

### ISSUE THREAD

**Issue by mouseletsean** [WebGoat/WebGoat#443]
## Error description
There will be an error in the follow circumstances:
1. Configure `web.xml` of webgoat to use mysql as database.
2. Mysql server is installed on linux platform and table name is sensitive by default.
3. Start webgoat, enter the lesson `String SQL Injection`.
4. Restart webgoat, enter the same lesson again. The error will be shown on the page.
```
* Error generating org.owasp.webgoat.plugin.SqlStringInjection
```
Error log in `catalina.out`
```
2018-03-02 15:02:33,547 INFO  - Role: user
PATH: /home/prac/webgoat/apache-tomcat-7.0.82/webapps/webgoat/database
Database Connection String: jdbc:mysql://127.0.0.1:3306/webgoat?useSSL=false
Successful connection to database
Info - Could not drop transactions table
Error: unable to create transactions table: Table 'Transactions' already exists
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'Transactions' already exists
```

## Cause analysis
https://github.com/WebGoat/WebGoat/blob/a922c001824d4571578e2188d13574597446318b/webgoat-container/src/main/java/org/owasp/webgoat/session/CreateDB.java#L909
https://github.com/WebGoat/WebGoat/blob/a922c001824d4571578e2188d13574597446318b/webgoat-container/src/main/java/org/owasp/webgoat/session/CreateDB.java#L916
https://github.com/WebGoat/WebGoat/blob/a922c001824d4571578e2188d13574597446318b/webgoat-container/src/main/java/org/owasp/webgoat/session/CreateDB.java#L939
The table name is **`Transactions`** in create and insert statements but **`transactions`** in drop statement. The capitalization of the first letter `T` is different. So the drop statement cannot drop the table **`Transactions`** correctly. And then the insert statement execute error: `Table 'Transactions' already exists`.

## Workaround
Set the `lower_case_table_names` parameter of mysql to make it table name case-insensitive.

## Solution
Change the table name in create and insert statements to `transactions`.

**Comment by nbaars** [comment]
Sorry but we are no longer actively supporting WebGoat 7.1
