### ISSUE TITLE
docker# cat: /home/webgoat/.webgoat/XXE/secret.txt: No such file or directory

### ISSUE THREAD

**Issue by offsecn00b** [WebGoat/WebGoat#446]
Per the lessons this secret.txt file should exist but doesn't exist in the lastest docker release. No permissions to copy it from the cat: /home/webgoat/.webgoat-8.0.0.M12/XXE/ directory either. I'm not sure if this matters or not.

EDIT: looks like its getting copied their deliberately during the startup process:

2018-03-12 18:11:13.357  INFO 1 --- [           main] o.o.w.plugin.challenge3.Assignment3      : Copied secret.txt to: /home/webgoat/.webgoat-8.0.0.M12

**Comment by nbaars** [comment]
Closing, as we released v8.0.0.M15
