### ISSUE TITLE
How to enable hosts other than localhost? (WebGoat 8)

### ISSUE THREAD

**Issue by 89jase** [WebGoat/WebGoat#450]
Hi all 

Firstly sorry if this isn't in the right place. I can't seem to find any other message board for Web Goat.

So as the title says, How can I enable WebGoat 8 to run on hosts other than localhost?
I'm trying to setup a Pen Test Environment in AWS but unsure how to do it on version 8 seems it's contained in a single JAR file and no Tomcat conf files.

And yes I'm aware of the vulnerability, this server will be started / stopped only when needed

Thanks in advance!

**Comment by nbaars** [comment]
@89jase can this help you further: https://github.com/WebGoat/WebGoat/wiki/FAQ#local-host-ip-config

Let us know if this does not solve your issue.
