### ISSUE TITLE
Test Failure on SqlInjectionLesson5aTest

### ISSUE THREAD

**Issue by MLobry** [WebGoat/WebGoat#452]
OS : Windows 7 Version 6.1
architecture : amd64
JDK version : 1.8.0_162

Hello,

I tried the maven way to install Webgoat and I have a test failure error in SqlInjection Test Suite :

On Powershell Terminal

> [INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WebGoat Parent Pom 8.0.0.M3 ........................ SUCCESS [  0.275 s]
[INFO] webgoat-container .................................. SUCCESS [ 34.156 s]
[INFO] webgoat-plugins-parent ............................. SUCCESS [  2.127 s]
[INFO] bypass-restrictions ................................ SUCCESS [ 12.996 s]
[INFO] challenge .......................................... SUCCESS [  6.710 s]
[INFO] client-side-filtering .............................. SUCCESS [  1.130 s]
[INFO] cross-site-scripting ............................... SUCCESS [  7.489 s]
[INFO] html-tampering ..................................... SUCCESS [  0.781 s]
[INFO] http-basics ........................................ SUCCESS [  0.768 s]
[INFO] http-proxies ....................................... SUCCESS [  2.941 s]
[INFO] insecure-login ..................................... SUCCESS [  1.546 s]
[INFO] jwt ................................................ SUCCESS [  0.764 s]
[INFO] sql-injection ...................................... FAILURE [ 11.957 s]
[INFO] xxe ................................................ SKIPPED
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-introduction ............................... SKIPPED
[INFO] webwolf-introduction ............................... SKIPPED
[INFO] auth-bypass ........................................ SKIPPED
[INFO] missing-function-ac ................................ SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] webgoat-server ..................................... SKIPPED
[INFO] webwolf 8.0.0.M3 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 min
[INFO] Finished at: 2018-04-17T11:09:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-tes
t) on project sql-injection: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\me\WebGoat\webgoat-lessons\sql-injection\target\
surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following arti
cles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sql-injection

All surefire reports are ok except one in
C:\Users\me\WebGoat\webgoat-lessons\sql-injection\target\surefire-reports\org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5aTest.txt

Content of report below :

> -------------------------------------------------------------------------------
> Test set: org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5aTest
> -------------------------------------------------------------------------------
> Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.725 sec <<< FAILURE! - in org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5aTest
unknownAccount(org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5aTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: 
JSON path "$.feedback"
Expected: is "Aucun r�sultat correspondant. Essayez encore."
     but: was "No results matched. Try Again."
	at org.owasp.webgoat.plugin.introduction.SqlInjectionLesson5aTest.unknownAccount(SqlInjectionLesson5aTest.java:55)

Best regards,

**Comment by nbaars** [comment]
Explicitly added UTF-8 encoding, this would hopefully fix it. Will be part of next release
