### ISSUE TITLE
Correct WebWolf Docker command

### ISSUE THREAD

**Issue by brohan** [WebGoat/WebGoat#453]
In the WebGoat8 docker application, WebWolf lesson (http://127.0.0.1:8080/WebGoat/start.mvc#lesson/WebWolfIntroduction.lesson) the code for launching the WebWolf docker appears to be incomplete. I was able to successfully launch the docker with the following command:

docker run -p 8081:8081 -it webgoat/webwolf /home/webwolf/start.sh

vs the listed command of:

docker run -it 8081:8081 /home/webwolf/run.sh

**Comment by nbaars** [comment]
Thanks indeed fixed in next release.
