### ISSUE TITLE
How to reset/drop the database?

### ISSUE THREAD

**Issue by h-rueda** [WebGoat/WebGoat#461]
Hello:

I am using WebGoat 8 and after a couple of days I am getting the message `There was an unexpected error. Please try again.` on every page a visit.

I cannot find the way to drop/delete the database and make a fresh start.

Where is the WebGoat database stored and how can I drop it?

**Comment by nbaars** [comment]
@h-rueda you can remove the `.webgoat-VERSION` directory in your home directory. For example: `.webgoat-v8.0.0.M14/`. If you are using an older version it can also be just the `.webgoat` directory in your home directory.
This will reset WebGoat back to its original state.

We will add a button in the UI of WebGoat which will do exactly this.

**Comment by nbaars** [comment]
Reset lesson database button has been added it will clean the lesson database only and restore it to its original state
