### ISSUE TITLE
How to use Lessons on WebGoat8?

### ISSUE THREAD

**Issue by 0xzhang** [WebGoat/WebGoat#465]
I have already "mvn package",but how can I add it on the website 
or how can I use it 
or that just fit WebGoat7.x?

**Comment by nbaars** [comment]
@0xzhang do you want to build and run from Maven? If so you can find the appropriate commands in the `README.md` in the root directory.

**Comment by 0xzhang** [comment]
@nbaars Thank you very much, it's my firsst time use Maven, I have execute the command in the README.md, but I don't know how to open the corresponding lessons, the generated jar can't be executed.

**Comment by nbaars** [comment]
@0xzhang you can also download the release from Github or use the Docker image from DockerHub.

For building it from the source, can you try the release8 branch like:
```
git checkout release/v8.0.0
mvn clean install
java -jar webgoat-server/target/webgoat-server-v8.0.0.M14.jar
```

**Comment by 0xzhang** [comment]
@nbaars ths, I'll try later ：）
