### ISSUE TITLE
IDOR lesson url error

### ISSUE THREAD

**Issue by freetest** [WebGoat/WebGoat#466]
http://127.0.0.1:8080/WebGoat/start.mvc#lesson/IDOR.lesson/4

when i  submit the View Profile button 
 url is http://127.0.0.1:8080/WebGoat/IDOR/profile/{userid}

<img width="971" alt="1111111" src="https://user-images.githubusercontent.com/5380255/39974163-75b78d8c-5759-11e8-8c67-c1737749d6c7.png">

**Comment by misfir3** [comment]
In this case, the URL is a placeholder and intended to be modified with the proxy based on the information you have already gathered.

**Comment by freetest** [comment]
thanks
