### ISSUE TITLE
WebGoat 8.0.0 Windows installation and errors logging into WebGoat

### ISSUE THREAD

**Issue by Shadow2xx** [WebGoat/WebGoat#467]
Idk if I am retarded, but I can't install WebGoat 8 for windows. There isn't a .bat file...

Or is this the same installation as descripted in the tutorial?

**Comment by jetweelim** [comment]
just do a 

java -jar webgoat_xxx.jar

**Comment by Shadow2xx** [comment]
Thanks for your reply!

**Comment by Shadow2xx** [comment]
It throws an error:

Error: Unable to access jarfile WebGoat-8.0.0.M14.jar

**Comment by Miraj50** [comment]
I am also getting the same error when I run `java -jar ~/Downloads/webgoat-server-8.0.0.M14.jar`. Please do help !
My java version :
`openjdk 10.0.1 2018-04-17`
`OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)`
`OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)`

**Comment by nbaars** [comment]
This error occurs if you are using Java 9 or higher, using the following command will fix the issue:

```
java --add-modules java.xml.bind -jar ~/Downloads/webgoat-server-8.0.0.M14.jar
```
I will add this to the FAQ for now we should fix this in the Maven build.

**Comment by Miraj50** [comment]
@nbaars @Shadow2xx Thank you for that. Got it running. I signed up with a username and password. But is it just me who is getting this error message? In addition to this, none of the topics/challenges are showing up when I click on them!

![screenshot from 2018-05-15 19-54-11](https://user-images.githubusercontent.com/23695844/40062966-f8bea564-5879-11e8-9c62-9a9ed72aa3ef.png)

**Comment by nbaars** [comment]
@Miraj50 do you see any logging in the console?

**Comment by Shadow2xx** [comment]
@nbaars my hero! Thank you so much!

**Comment by Miraj50** [comment]
@nbaars This is what I get until I have logged in.
I have to get to get the whole image instead of just copy and paste.

![screenshot from 2018-05-15 21-19-18](https://user-images.githubusercontent.com/23695844/40068298-eaea1426-5885-11e8-9c62-ff06383cbe27.png)

**Comment by nbaars** [comment]
@Miraj50 strange there is no obvious error, can you try to remove the `.webgoat` directory? It is located here in your case: `/home/miraj/.webgoat-8.0.0-M14` you can remove the complete directory and start WebGoat again.

**Comment by Avneel123** [comment]
hello am getting error while installing web goat in windows platform

i have downloaded and installed webgoat java - jar 

while opening it to browser it shows this error

Error
Invalid client request received: First line of request did not contain an absolute URL - try enabling invisible proxy support.

GET /WebGoat HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Sec-Fetch-Site: none
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9


please help me out

**Comment by gamrabenmarzouka** [comment]
je veux installer webgoat java sur kali je eu cette erreur

![Capture d’écran 2023-03-12 205911](https://user-images.githubusercontent.com/61563424/224570087-e3b042b9-7779-41a1-8131-7e36ba4841fa.png)

**Comment by DAF1k** [comment]
the solution can be also if you download the file and you with proxychains
