### ISSUE TITLE
Submit Button is not working

### ISSUE THREAD

**Issue by mgsein** [WebGoat/WebGoat#468]
I do all the instructions that they were said step by step.
But the submit button in HTTP proxies section is not working.
The problem is here which is that the post is not woking when I click submit button in WebGoat.
![12332](https://user-images.githubusercontent.com/14964092/40280602-2346f51a-5c7c-11e8-9efb-9a47b0542650.PNG)

**Comment by nbaars** [comment]
@mgsein you need to change it to a GET, see assignment: 

* Change the Method to GET

The assignment only exposes a GET endpoint

**Comment by mgsein** [comment]
Hi friend,

My problem with that is I can't intercept the connection after clicking
submit button by using OWASP ZAP{ I follow the instructions correctly but
it didn't work}
