### ISSUE TITLE
CSRF json lession doesn't accept suggested solution 

### ISSUE THREAD

**Issue by ralfvandenbroek** [WebGoat/WebGoat#475]
The CSRF json lesson which expects the user to change the content type to text/plain does not accept the solution indicated in CSRFFeedback.java. If I upload a file with those contents to WebWolf and access it, the Origin header will be http://localhost:9090 and the Referer header will be http://localhost:9090/..., which will not pass the check in hostOrRefererDifferentHost. It seems this logic changed in commit 1edceb0aa8a0596be6b760b14b977e9b4c5e9971.

**Comment by nbaars** [comment]
Fixed with new release
