### ISSUE TITLE
User name does not accept dashes

### ISSUE THREAD

**Issue by ralfvandenbroek** [WebGoat/WebGoat#476]
The user name does not accept dashes, so one cannot make a user with the prefix csrf-, as indicated in the CSRF login lesson. This logic seems to have been implemented in commit fc2c99bcb4fbb355c9b1547dbdd777ad54927e6b

**Comment by nbaars** [comment]
Restricted the characters which can be used for a username to digits and characters. During a workshop I ran into the issue users used: test@test.com as username which broke the e-mail lessons. I will update this one to allow the dash.

**Comment by nbaars** [comment]
Fixed with new release
