### ISSUE TITLE
WebGoat Email

### ISSUE THREAD

**Issue by nkitmitto** [WebGoat/WebGoat#478]
Currently working through setting up WebWolf, I got that Docker container running along with WebGoat.  Both I can log into successfully.  The issue I'm running into now is when I go to WebGoat to send an email, it fails to connect to http://localhost:8081/mail.  This should be pointed at `http://${webwolf.host}:${webwolf.port}/WebWolf/mai`l  instead.

https://github.com/WebGoat/WebGoat/blob/c510bd9bf1a85c753d76fa86ae95bea045227bff/webgoat-container/src/main/resources/application.properties#L43

**Comment by BTRBT** [comment]
Same thing here. Error message I get is as follows:

> I/O error on POST request for "http://localhost:9090/mail": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)

**Comment by nbaars** [comment]
WebGoat cannot reach WebWolf through `localhost`, there are two options:

1) Use our docker-compose.yml file from our repository: https://github.com/WebGoat/WebGoat/blob/develop/docker-compose.yml 
2) Create a network, see below.

For 1 copy the file and run: `docker-compose up`
For 2:

```
docker network create webgoat_network
docker run -p 8080:8080 --net webgoat_network --name webgoat -e WEBWOLF_HOST=webwolf -it webgoat/webgoat-8.0 /home/webgoat/start.sh
docker run --net webgoat_network --name webwolf -e spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat -it -p 9090:9090 webgoat/webwolf /home/webwolf/run.sh
```

This creates a network and the containers are able to find each other based on the container name

@nkitmitto @BTRBT can you confirm this is working for you as well, so I can update the FAQ and documentation?

**Comment by BTRBT** [comment]
Sorry, I'm an idiot. I'm not running webgoat on docker. I'm running it in VirtualBox with a host-only bridged network and the following commands:

> java -jar webgoat-server-8.0.0.M17.jar --server.address=x.x.x.x
> java -jar webwolf-8.0.0.M17.jar --server.address=x.x.x.x

I clearly shouldn't have said "Same here" given the distinctions in how I'm running the software. My apologies. Getting the same error when webgoat tries to send email to webwolf, though. I'm able to access both through my host system's browser.

Sorry again. I'm quite new to all of this.

**Comment by nbaars** [comment]
@BTRBT you start both of them in the same VirtualBox instance right? If so you do not need to specify `--server.address` You can take a look at our Vagrantfile which starts both of them and forwards the port to the host machine.

**Comment by nkitmitto** [comment]
@nbaars  The docker-compose worked, however, the individual docker commands did not.  If I get some time soon, I'll debug why it did not work and let you know.

Thanks!!

**Comment by nbaars** [comment]
We now moved completely to using `docker-compose` which simplifies starting both containers. Starting different Docker containers really complicates things and if you really want to start it as two separate Docker containers the `docker-compose.yml` should give enough hints and tips how to do this.

**Comment by StenKoning** [comment]
Currently downloading the YML file and running docker-compose up gives a connection refused error. So does running the curl command.

nbaars' code solved the problem:

```
docker network create webgoat_network
docker run -p 8080:8080 --net webgoat_network --name webgoat -e WEBWOLF_HOST=webwolf -it webgoat/webgoat-8.0 /home/webgoat/start.sh
docker run --net webgoat_network --name webwolf -e spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat -it -p 9090:9090 webgoat/webwolf /home/webwolf/run.sh
```
