### ISSUE TITLE
webgoat 8 debug mode in eclipse

### ISSUE THREAD

**Issue by ank113** [WebGoat/WebGoat#489]
I'm trying to run webgoat 8 in debug mode in my local eclipse from source code and getting following exception ... please advise ....

2018-06-19 17:02:44.178  INFO 5540 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-06-19 17:02:44.194  INFO 5540 --- [  restartedMain] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-06-19 17:02:44.209 ERROR 5540 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   :

**Comment by nbaars** [comment]
@ank113 I've tried it but I'm able to debug the application from within Eclipse, one question do you start the debugging session on this class: `org.owasp.webgoat.StartWebGoat`?

**Comment by alpha-k911** [comment]
i got this error
![screenshot from 2018-10-28 15-21-27](https://user-images.githubusercontent.com/34766587/47614386-407ac400-dac5-11e8-8b33-daf82d03302d.png)

**Comment by nbaars** [comment]
@alpha-k911 do you happen to have a stacktrace you can share with us?

**Comment by nbaars** [comment]
Closing as no input received, @alpha-k911 feel free to open the issue if you want

**Comment by alpha-k911** [comment]
Solved the issue... Thanks..
