### ISSUE TITLE
Neither Plain Properties nor XML

### ISSUE THREAD

**Issue by hstoetz** [WebGoat/WebGoat#493]
Currently, the main UI and user authentication work fine, but for some reason the lesson data refuses to load. Screenshot

Whenever I try and access a lesson, this message appears in the console,"No properties file found for [classpath:i18n/messages_en] - neither plain properties nor XML." 
[Screenshot](https://i.stack.imgur.com/XWkvK.png)

I am running Java 9 on the latest version of KALI Linux and when I execute the command in the terminal it is entered as follows: java --add-modules java.xml.bind -jar ~/Downloads/webgoat-server-8.0.0.M14.jar
[Screenshot](https://i.stack.imgur.com/3I9Lj.png)

The java.xml.bind has been added per documentation for Java 9. However, I believe this may be part of the problem as I am receiving an XML related error. Without adding this, WebGoat does not function at all on localhost. I have not seen this error anywhere else, any guidance would be greatly appreciated

**Comment by nbaars** [comment]
see #541 need to test with different locales and make sure we have a fallback that works

**Comment by zubcevic** [comment]
I would say run version 8.1 and use Java 11. 
But the issue could be related to the encoding used on the OS. Similar for the Windows instances, you could try: 
-Dfile.encoding=UTF-8
