### ISSUE TITLE
WebGoat not running

### ISSUE THREAD

**Issue by Ballanear** [WebGoat/WebGoat#499]
Hi Gents!

I'm running command java -jar webgoat-server-8.0.0.M21.jar and receiving such notice:

> root@Kali:~# java -jar webgoat-server-8.0.0.M21.jar 
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::       (v1.5.12.RELEASE)
> 
> 2018-07-05 23:11:20.744  INFO 11897 --- [           main] org.owasp.webgoat.StartWebGoat           : Starting StartWebGoat v8.0.0.M21 on Kali with PID 11897 (/root/webgoat-server-8.0.0.M21.jar started by root in /root)
> 2018-07-05 23:11:20.749 DEBUG 11897 --- [           main] org.owasp.webgoat.StartWebGoat           : Running with Spring Boot v1.5.12.RELEASE, Spring v4.3.16.RELEASE
> 2018-07-05 23:11:20.750  INFO 11897 --- [           main] org.owasp.webgoat.StartWebGoat           : No active profile set, falling back to default profiles: default
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/root/webgoat-server-8.0.0.M21.jar!/BOOT-INF/lib/groovy-2.4.15.jar!/) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 2018-07-05 23:11:21.393  INFO 11897 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7d8995e: startup date [Thu Jul 05 23:11:21 CEST 2018]; root of context hierarchy
> 2018-07-05 23:11:25.611  INFO 11897 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$dadfbd22] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
> 2018-07-05 23:11:26.719  INFO 11897 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
> 2018-07-05 23:11:26.774  INFO 11897 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> 2018-07-05 23:11:26.774  INFO 11897 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.29
> 2018-07-05 23:11:26.983  INFO 11897 --- [ost-startStop-1] o.a.c.c.C.[.[localhost].[/WebGoat]       : Initializing Spring embedded WebApplicationContext
> 2018-07-05 23:11:26.984  INFO 11897 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5602 ms
> 2018-07-05 23:11:27.593  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
> 2018-07-05 23:11:27.594  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
> 2018-07-05 23:11:27.594  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
> 2018-07-05 23:11:27.594  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
> 2018-07-05 23:11:27.594  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
> 2018-07-05 23:11:27.596  INFO 11897 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
> 2018-07-05 23:11:27.597  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
> 2018-07-05 23:11:27.597  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
> 2018-07-05 23:11:27.597  INFO 11897 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@45673f68]: [Thread[main,5,main]]: setDatabaseName(0,webgoat)
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@45673f68]: [Thread[main,5,main]]: setDatabasePath(0,/root/.webgoat-8.0.0.M21//data/webgoat)
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) entered
> [Server@45673f68]: [Thread[main,5,main]]: checkRunning(false) exited
> [Server@45673f68]: [Thread[main,5,main]]: setDaemon(true)
> [Server@45673f68]: [Thread[main,5,main]]: setTrace(false)
> [Server@45673f68]: [Thread[main,5,main]]: setSilent(true)
> [Server@45673f68]: Initiating startup sequence...
> [Server@45673f68]: Server socket opened successfully in 12 ms.
> 2018-07-05 23:11:28.200  INFO 11897 --- [erver @45673f68] hsqldb.db..ENGINE                        : open start - state modified
> 2018-07-05 23:11:28.225  INFO 11897 --- [erver @45673f68] hsqldb.db..ENGINE                        : checkpointClose start
> 2018-07-05 23:11:28.226  INFO 11897 --- [erver @45673f68] hsqldb.db..ENGINE                        : checkpointClose synched
> 2018-07-05 23:11:28.287  INFO 11897 --- [erver @45673f68] hsqldb.db..ENGINE                        : checkpointClose script done
> 2018-07-05 23:11:28.405  INFO 11897 --- [erver @45673f68] hsqldb.db..ENGINE                        : checkpointClose end
> [Server@45673f68]: Database [index=0, id=0, db=file:/root/.webgoat-8.0.0.M21//data/webgoat, alias=webgoat] opened successfully in 672 ms.
> [Server@45673f68]: Startup sequence completed in 688 ms.
> [Server@45673f68]: 2018-07-05 23:11:28.414 HSQLDB server 2.3.4 is online on port 9001
> [Server@45673f68]: To close normally, connect and execute SHUTDOWN SQL
> [Server@45673f68]: From command line, use [Ctrl]+[C] to abort abruptly
> 2018-07-05 23:11:29.928  INFO 11897 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
> 2018-07-05 23:11:29.957  INFO 11897 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
> 	name: default
> 	...]
> 2018-07-05 23:11:30.106  INFO 11897 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.12.Final}
> 2018-07-05 23:11:30.109  INFO 11897 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
> 2018-07-05 23:11:30.112  INFO 11897 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
> 2018-07-05 23:11:30.150  WARN 11897 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> [Server@45673f68]: Initiating shutdown sequence...
> 2018-07-05 23:11:30.159  INFO 11897 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
> 2018-07-05 23:11:30.207  INFO 11897 --- [           main] utoConfigurationReportLoggingInitializer : 
> 
> Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
> 2018-07-05 23:11:30.231 ERROR 11897 --- [           main] o.s.boot.SpringApplication               : Application startup failed
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.12.RELEASE.jar!/:1.5.12.RELEASE]
> 	at org.owasp.webgoat.StartWebGoat.main(StartWebGoat.java:38) [classes!/:8.0.0.M21]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [webgoat-server-8.0.0.M21.jar:8.0.0.M21]
> Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
> 	at org.hibernate.boot.spi.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
> 	at org.hibernate.boot.MetadataSources.<init>(MetadataSources.java:87) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:179) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:149) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
> 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:384) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336) ~[spring-orm-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626) ~[spring-beans-4.3.16.RELEASE.jar!/:4.3.16.RELEASE]
> 	... 24 common frames omitted
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[na:na]
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[na:na]
> 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[webgoat-server-8.0.0.M21.jar:8.0.0.M21]
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
> 	... 35 common frames omitted
> 
> [Server@45673f68]: Shutdown sequence completed in 118 ms.
> [Server@45673f68]: 2018-07-05 23:11:30.273 SHUTDOWN : System.exit() was not called

**And Java running on my Kali**

> java -version
> openjdk version "10.0.1" 2018-04-17
> OpenJDK Runtime Environment (build 10.0.1+10-Debian-4)
> OpenJDK 64-Bit Server VM (build 10.0.1+10-Debian-4, mixed mode)

Please help, because if I open 

> http://localhost:8080/webgoat/attack

nothing happens

**Comment by prototyqe** [comment]
same problem

**Comment by jokkr** [comment]
same problem need Help.... My system is Kali linux 2018.1

**Comment by blueteamtech** [comment]
I had the same error. The added Java module helped me get this running.

> java --add-modules java.xml.bind -jar webgoat-server-8.0.0.M21.jar

**Comment by homersimpsons** [comment]
According to [this](https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378) the module `java.xml.bind` have been removed in JDK 11

**Comment by nbaars** [comment]
@homersimpsons @jokkr in release M22 we upgraded to M22 which would fix those issues

**Comment by nbaars** [comment]
Version M23 has been released

**Comment by scotbellamy** [comment]
I am running M24 using Open JDK 11 and am having the same problem.  As mentioned in an earlier post, java.xml.bind does not exist in JDK 11.  How do I fix this?

**Comment by sethwilsonUS** [comment]
I'm having the same issue with M24.

**Comment by ferasbbm** [comment]
use version 7

**Comment by danyalson-py** [comment]
Capitalize the W and G
http://<ip address>:8080/WebGoat/login
