### ISSUE TITLE
why can't login wwebwolf from remote?

### ISSUE THREAD

**Issue by GitHubNull** [WebGoat/WebGoat#501]
why can't login wwebwolf from remote? SInce webwolf can't login from remote (default is localhost), I must run webgoat in localhost also! But I want run them all in raspberry...

**Comment by nbaars** [comment]
@GitHubNull if you pass `server.address=...` to the java command you can bind it to any address, by default it binds to localhost. You can at our docker-compose file to see how you can pass these variables (https://github.com/WebGoat/WebGoat/blob/develop/docker-compose.yml)
