### ISSUE TITLE
SQL Injection (mitigation) bug 

### ISSUE THREAD

**Issue by 60noy** [WebGoat/WebGoat#505]
There's a bug in the lesson SQL Injection (mitigation).
If I submit one of the ip addresses in the list - I complete the challenge.
Here's the image before submitting:
![Image before submitting](https://image.ibb.co/mAes1o/wrong_sql1.png)

And here's after submitting
![Image before submitting](https://image.ibb.co/eyKEE8/wrong_sql2.png)

Tested on Standalone Webgoat (webgoat-server-8.0.0.M17.jar)

**Comment by grssnbchr** [comment]
Also, I have a question:  The attack description says that an ORDER BY clause can be used to circumvent prepared statements: `Question: Does a prepared statement always prevent against an SQL injection? Answer: No it does not`

However, it looks like in the code that queries the servers, no actual prepared statements are used: 

https://github.com/WebGoat/WebGoat/blob/f9e552f1cd9f73cb360d3361eb70964c0f5979a5/webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/Servers.java#L45

The query is wrapped by a prepared statement function call, but uses normal string concatenation imho.

Can someone explain this, or is this a bug?

**Comment by nbaars** [comment]
@grssnbchr the '?' syntax in prepared statements can only be used for input parameters so you cannot use `order by ?` in a prepared statement. Because you cannot use this you have to use for example a string concatenation. Feeding the result to a prepared statement does not help in preventing the possible SQL injection though the order by. So the question points to the fact that using prepared statements might not always save you.

**Comment by grssnbchr** [comment]
Alright, but why can it only be used for "input parameters"? What do you mean by that? If I only allow column names (by using a whitelist, e.g.), couldn't I use a prepared statement with `order by ?` ?

**Comment by nbaars** [comment]
No that's not possible, parameters can only be used where one would put a single value, for example a string or date or a numerical value.
For example you cannot: 

```
SELECT * FROM ? WHERE id = 'WebGoat'
SELECT * FROM users ORDER BY ?
```
etc. You can only use the ? for values.
