### ISSUE TITLE
Where and how should I look for the file where the source code is present?

### ISSUE THREAD

**Issue by honeywarid** [WebGoat/WebGoat#506]
![image](https://user-images.githubusercontent.com/41227879/42778763-c855d86c-895b-11e8-83f0-69a2f854dbd8.png)

This is regarding "CSRF Token By-Pass". On the page, reached after clicking "Show Solution", I was told to look at the certain source code lines. But I did not succeed in locating that file containing the source code.

**Comment by nbaars** [comment]
We are no longer actively supporting release 7.1 therefore we are closing this issue, sorry
