### ISSUE TITLE
Possible bug in PasswordReset.lesson/1?

### ISSUE THREAD

**Issue by grssnbchr** [WebGoat/WebGoat#511]
* I'm running Webgoat 8 M21 and Webwolf M21 standalone. 
* Webgoat runs on port 8081 (because Burp runs on 8080), and Webwolf runs on 9090.
* I completed the WebWolfIntroduction.lesson - so sending a mail and a request to the landing page worked (I just tested this again). 
* Now the problem: in PasswordReset.lesson/1, where you have to click on "Forgot your password" and send a mail to userxyz@webgoat.org, the mail never arrives in the Webwolf mail address. `userxyz` is also the username I use to login to Webwolf. 
* Also: Once I click on "continue" in the password reset login form, I solely get: "Sorry the solution is not correct, please try again". Shouldn't that be something like: "Your password has been sent to userxyz@webgoat.org"?

**Comment by nbaars** [comment]
Thanks I see what's going wrong let me fix this

**Comment by nbaars** [comment]
Fixed in the development branch

**Comment by grssnbchr** [comment]
That was fast, thanks!

**Comment by nbaars** [comment]
Version M23 has been released
