### ISSUE TITLE
Password reset lesson 5 not working

### ISSUE THREAD

**Issue by anakin1** [WebGoat/WebGoat#512]
Lesson 5 requires you to initiate a password reset link for tom@webgoat-cloud.org. My understanding of reviewing the hints and the source code is that:

- you fill out the "forgot password" form with the e-mail of tom@webgoat-cloud.org
- intercept the request, and modify the Host header from localhost:8080 to localhost:9090
- login to WebWolf and access the Incoming Requests tab

However no links appear in the Incoming Requests tab on WebWolf - it's as if the lesson is ignoring the modified host header.  Or do I have the solution completely wrong?

Here is the HTTP request, with the modified Host header:

POST http://localhost:8080/WebGoat/PasswordReset/reset/create-password-reset-link HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Referer: http://localhost:8080/WebGoat/start.mvc
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
X-Requested-With: XMLHttpRequest
Content-Length: 29
Cookie: JSESSIONID=B902C62C30A6DA2843CCB90CCE246554; WEBWOLFSESSION=4C6F4094BEF4E1659975F56B5EA9E9D0
Connection: keep-alive
Host: localhost:9090

email=tom%40webgoat-cloud.org

**Comment by mwiekens** [comment]
Have the same problem with webgoat-8.0.0.M21

**Comment by nbaars** [comment]
@anakin1 This is a known issue within ZAP (https://www.bountysource.com/issues/24773292-header-always-updated-on-send-cannot-resend-some-requests). We need to update the lesson and clarify that using ZAP is not an option

**Comment by nbaars** [comment]
Things to do: add a note to the lesson that it is not possible to use ZAP

**Comment by nbaars** [comment]
Added extra remark in the lesson about using OWASP ZAP

**Comment by nbaars** [comment]
Version M23 has been released

**Comment by central-yharnam** [comment]
Hello, I recently came across this same issue and I am using burp suite but it doesn't work. I know that the intercept is working because when I do the password reset for my own webgoat account I get a request on webwolf. But when changing the email to tom, not requests appear.

**Comment by Xanda639** [comment]
I want to get my email back that I forgot the password and email

**Comment by Xanda639** [comment]
https://github.com/WebGoat/WebGoat/issues/512#issuecomment-1437462745

**Comment by Triplei1** [comment]
Where can I find the forgotten password form please?

**Comment by soupifelicia-cyber** [comment]
rymou.belmout@gmail.com
