### ISSUE TITLE
Help with Weboat 8 install

### ISSUE THREAD

**Issue by nmyprime32** [WebGoat/WebGoat#514]
Hi, first time trying to install WebGoat 8 to learn and discover application flaws and security. I'm eager to get started but i don't know how after trying to install on my windows 10 PC. If someone can give me guidance or tutorial that is easy to follow, I would greatly appreciate it. 

Thanks, 
Tyler

**Comment by nbaars** [comment]
@nmyprime32 did you follow the README.md? https://github.com/WebGoat/WebGoat? 

If you get stuck, let us know so we can update the documentation, please reopen this issue
