### ISSUE TITLE
Java 10 Build fails for "mvn install"

### ISSUE THREAD

**Issue by gpsymantec** [WebGoat/WebGoat#515]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 68 source files to /home/g/WebGoat/webgoat-container/target/classes
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WebGoat Parent Pom ................................. SUCCESS [  0.226 s]
[INFO] webgoat-container .................................. FAILURE [  2.101 s]
[INFO] webgoat-plugins-parent ............................. SKIPPED
[INFO] bypass-restrictions ................................ SKIPPED
[INFO] challenge .......................................... SKIPPED
[INFO] client-side-filtering .............................. SKIPPED
[INFO] cross-site-scripting ............................... SKIPPED
[INFO] html-tampering ..................................... SKIPPED
[INFO] http-basics ........................................ SKIPPED
[INFO] http-proxies ....................................... SKIPPED
[INFO] insecure-login ..................................... SKIPPED
[INFO] insecure-deserialization ........................... SKIPPED
[INFO] jwt ................................................ SKIPPED
[INFO] sql-injection ...................................... SKIPPED
[INFO] xxe ................................................ SKIPPED
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-introduction ............................... SKIPPED
[INFO] webwolf-introduction ............................... SKIPPED
[INFO] auth-bypass ........................................ SKIPPED
[INFO] missing-function-ac ................................ SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] password-reset ..................................... SKIPPED
[INFO] webgoat-server ..................................... SKIPPED
[INFO] webwolf ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.253 s
[INFO] Finished at: 2018-08-20T16:33:11-07:00
[INFO] Final Memory: 52M/159M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project webgoat-container: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :webgoat-container
gaurav@ubuntu:~/WebGoat$

**Comment by nbaars** [comment]
@gpsymantec this is correct, since version M22 we fully support version 11 of Java and stopped supporting Java 8

**Comment by nbaars** [comment]
Version M23 has been released
