### ISSUE TITLE
Unable to run in JDK 11

### ISSUE THREAD

**Issue by DoMINAToR98** [WebGoat/WebGoat#522]
java --add-modules java.xml.bind -jar webgoat-server-8.0.0.M21.jar
This command doesn't work for Java 11 as  " --add-module " is not working anymore.
What to do?

**Comment by tbobov123** [comment]
same here, one workaround would be to downgrade java:

sudo update-alternatives --config java

**Comment by gagarwa** [comment]
The module is no longer available in JDK, but is there in Java EE.  If you extract from there and run it, it should work, or try running as Java EE application (change your env variables).

**Comment by nbaars** [comment]
We moved to Java 11 completely as Java 8 is no longer supported, fixed in release M22

**Comment by nbaars** [comment]
Version M23 has been released

**Comment by taheroo** [comment]
> same here, one workaround would be to downgrade java:
> 
> sudo update-alternatives --config java

worked for me. Thank you very much
