### ISSUE TITLE
Readme binding security clarifications

### ISSUE THREAD

**Issue by PWx21** [WebGoat/WebGoat#524]
> WARNING 1: While running this program your machine will be extremely vulnerable to attack. You should disconnect from the Internet while using this program. WebGoat's default configuration binds to localhost to minimize the exposure.
>...
>2. Run using Docker
curl https://raw.githubusercontent.com/WebGoat/WebGoat/develop/docker-compose.yml | docker-compose -f - up
Important: the current directory on your host will be mapped into the container for keeping state.

By binding to localhost, the minimized exposure is the same preventative measure described here, right? https://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server So outside of other changes to the local machine, by binding to localhost the vulnerable application isn’t exposed at all to the outside world?

Related to this, I’m struggling to figure out on my own if Docker by default binds to localhost/127.0.0.1, or 0.0.0.0. I assume it's to localhost, since it would partially explain the discrepancy between the Readme for a Standalone setup: 
`java -jar webgoat-server-8.0.0.VERSION.jar [--server.port=8080] [--server.address=localhost]`
And Docker setup https://github.com/WebGoat/WebGoat/blob/develop/docker-compose.yml#L13 binding to 0.0.0.0 - that binding only applies to things within the container?

(comment): If Docker isn’t default binding to localhost, then I don’t think the docs for the Docker setup should give a one-liner that presumes internet-connectivity by simultaneously making the curl call and setting up the container.

Regarding “the current directory on your host will be mapped into the container for keeping state”? - By mapping the directory, that means the container will have direct/full access to the directory the command is run from on the local machine? And is the concern then - that if anything from the internet/outside sufficiently attacks the vulnerable application, then they’d also have access to those mapped files from the directory?

Thanks for your time.

**Comment by nbaars** [comment]
@PWx21 that note has been present long before the added Docker containers. We used to provided only a jar file which people could bind to any address. You can bind it to your ip address which would make it discoverable in the network. Also the Docker parameters can be overwritten when starting Docker.

I agree about the one liner, but I think it is better to leave it in as it is a vulnerable application and just to be very sure it is best to not connect to the internet at all. We use to have a lesson about remote code exec which was not limited to the command you would use, you can image what can happen...

Do you agree that we can leave the note and that the best practice is to disconnect from a network unless you are really sure the container cannot be reached from the outside?

If not can you help rewriting the text?

**Comment by nbaars** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still think we need to change this in our current version.
