### ISSUE TITLE
I can't run OWASP ZAP and WebGoat together.

### ISSUE THREAD

**Issue by Swetabhsuman8** [WebGoat/WebGoat#530]
Hello sir,

I am getting few problems, **### please help me to fix thi**s - I am not able to run ZAP and WebGoat together because of PORT issue. Both applications are using PORT 8080, I tried hard but I think I am missing something.

- **I am running WebGoat V8 Standalone.** 

Thank you,
Swetabh Suman

**Comment by joubin** [comment]
Change the ZAP port to some other port. 

[Fast forward to 1:13](https://www.youtube.com/watch?v=vl5cPKMmzVA)

**Comment by Swetabhsuman8** [comment]
Yeah I was thinking the same but I was not able to find out out how to do it. Thank you so much for the video.
