### ISSUE TITLE
Can't login to a clean new WebGoat deployment

### ISSUE THREAD

**Issue by groulot** [WebGoat/WebGoat#531]
Hello.

I run webgoat with the docker-compose configuration from the master branch (develop fails).
When I go to http://127.0.0.1:8080/WebGoat the login page is displayed, so far so good.

But guest in the login box and password fails with this error message:
```Invalid username and password```

Did I miss an initialization phase, something that should have created the guest account?

**Comment by alinleonard** [comment]
@groulot have the same issue , even after creating an account and I can see in webgoat.log the insert the login does not work . (Java 10)

**Comment by alinleonard** [comment]
@groulot I have a update, if you use edge the login works , chrome Version 69.0.3497.100 (Official Build) (64-bit) does not work .

**Comment by groulot** [comment]
Thanks for the information !

**Comment by nbaars** [comment]
@alinleonard Java 10 was not fully supported, since M22 we completely moved to Java 11 so this issue should be fixed. I tested on the lasted Chrome version on Linux which worked with creating a new user.

**Comment by nbaars** [comment]
Version M23 has been released
