### ISSUE TITLE
InsecureDeserializationTask

### ISSUE THREAD

**Issue by Kyoku57** [WebGoat/WebGoat#532]
Hi, 

I launch WebGoat 8.0M21 through a vagrant machine that launch the download release jar and exposes 8080 on my localhost.

I forge a token that it is a base64+serialize Object that includes a readObject with Thread.sleep(5000)

I send "rO0ABXNyAAdSYWxlbnRpAAAAAAAAAAECAAB4cA==" token to
http://localhost:8080/WebGoat/InsecureDeserialization/task

but I have a negative response from my VM
{
  "lessonCompleted" : false,
  "feedback" : "Sorry the solution is not correct, please try again.",
  "output" : null
}

If I analyzed the code 
https://github.com/WebGoat/WebGoat/blob/develop/webgoat-lessons/insecure-deserialization/src/main/java/org/owasp/webgoat/plugin/InsecureDeserializationTask.java

and put it in a simple main, this is work with my token ...

So what's the difference ?

**Comment by imsilence** [comment]
I have encountered the same problem, how can I solve it?

**Comment by imsilence** [comment]
I found that the seriablizable class must exist on the server's classpath. How can I solve it?
