### ISSUE TITLE
Default setup, still cannot connect on port 8080  

### ISSUE THREAD

**Issue by omkar-ukirde** [WebGoat/WebGoat#554]
I did default setup using the latest Docker image. Ran given docker command still nothing on localhost:8080.
Same I tried using Debian Buster server with latest Java. Still nothing.
Installed Java on windows and ran jar file nothing.
Please verify the latest build on your side. 
I have gone through all logs everything looks good. But if you want some logs I'll be happy. Since my issue is very basic.

**Comment by nbaars** [comment]
@omkar-ukirde  did you go use the followin URL: http://localhost:8080/WebGoat to connect to WebGoat?

**Comment by omkar-ukirde** [comment]
Thank you, this line "http://127.0.0.1:8080/WebGoat/login" should be added in a readme.
