### ISSUE TITLE
Installation Issue with Java Runtime Class Version

### ISSUE THREAD

**Issue by jeffsani** [WebGoat/WebGoat#555]
Installed the default-jre on Ubuntu 1804 and then tried to install the WG jar file but I am getting an error that the version of the Java Runtime only recognizes class file versions up to 54.  /org/owasp/webgoat/StarWebGoat has been compiled by the Java Runtime (class file version 55.0).  Should I just compile locally?

**Comment by nbaars** [comment]
@jeffsani the default jre is probably Java 8, WebGoat runs on Java 11. You can download Java 11(no need to install it unzipping it is enough) or use our Docker image.
