### ISSUE TITLE
General UI problem: highlight of current lesson page is not really visible

### ISSUE THREAD

**Issue by reruesch** [WebGoat/WebGoat#557]
CSS stye for `.cur-page` has to be improved, the marking is almost not visible (not enough contrast)
Suggestion:  change line 1005 of file `main.css` to `border: 3px solid #0c6bf6;`
(blue, light enough to be seen)

**Comment by zubcevic** [comment]
I will add this to #620

**Comment by zubcevic** [comment]
done in latest develop
