### ISSUE TITLE
Possible problem with [—service.port=9090]

### ISSUE THREAD

**Issue by jpitz31** [WebGoat/WebGoat#559]
Just installed the latest Web Goat (webgoat-server-8.0.0.M24.jar)
on OS X Mojave.

I am using the Java .jar format to launch the app.

The command line I pass is as follows:

java -jar webgoat-server-8.0.0.M24.jar [--server.port=9090] [--server.address=localhost]

Notice the [—service.port=9090]

When I start web goat I watch the log output and it appears that Tomcat is using port 8080 by default:

2019-02-25 18:59:02.736  INFO 62777 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)

I am assuming that Tomcat is suppose to use this parameter [--server.port=9090]

But I am not sure if this is a bug or not.  

But I wanted to pass this information along anyway.

**Comment by zubcevic** [comment]
if port 9090 is free, java -jar webgoat-server-8.0.0.M24.jar --server.port=9090 should work. 

However, Spring Boot has a strange way of reading the command line parameters and you can only pass on 1 parameter in this way.

The alternative is: java -jar webgoat-server-8.0.0.M24.jar --spring.config.location=/tmp/application-webgoat.properties

Then you can override any or all of the properties. I had to do this for both WebGoat and WebWolf on a server where port 9001 was already in use.

**Comment by davewichers** [comment]
@jpitz31 - I just tried this and it worked fine for me:  "Tomcat started on port(s): 9090 (http)".

Did you actually put the brackets [  ] around the --server.port parameters. If so, that's your problem. They are provided in the documentation to indicate those parameters are optional.  You need to NOT include them if you actually want those parameters to take affect. Can you try again and see if your problem goes away. Please let us know as we can then close this ticket if so.
