### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by iam-Arvind** [WebGoat/WebGoat#561]
java -jar webgoat-server-8.0.0.M24.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/owasp/webgoat/StartWebGoat has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by SreecharanShroff** [comment]
your local JDK version is < webgoat-server...jar compiled version
please change your local JDK to version >= webgoat-server...jar compiled version (Build-Jdk: 11.0.2)

**Comment by iam-Arvind** [comment]
yes its working by changing to 11.0.2 but by latest version of java burp suite is not working any solutions for it

**Comment by SreecharanShroff** [comment]
again same incompatible JDK version. Burp suite might be compiled with older version of JDK

**Comment by iam-Arvind** [comment]
yes burp suite required older version of jdk and wegoat server needed latest version of jdk how can compile both at a time ??

**Comment by SreecharanShroff** [comment]
this is not webgoat issue, please check with burp team

**Comment by iam-Arvind** [comment]
ok thx mr sree charan

**Comment by SBAFUNDZ** [comment]
main" java.lang.UnsupportedClassVersionError: org/owasp/webgoat/StartWebGoat has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.     ,please i run jdk 11.0.11 version
please anyone help
