### ISSUE TITLE
can't launch with Java 11 (no jre)

### ISSUE THREAD

**Issue by CaosFR** [WebGoat/WebGoat#569]
Hi,

I can't launch Webgoat on Windows since Java 11 is needed.

If I install the last version of Java 11 (JDK 11).
=> Could not fin Java SE Runtime Envionnement
If I install the last Java SE Runtime Envionnement (JRE 8)
=> WebGoat has been compiled by a more recent version of the Java Runtime.

They don't have any JRE 11 on oracle web site. I dont understand, how can I use WebGoat.
Can someone help me ?

TY

**Comment by zubcevic** [comment]
If you download Oracle JDK11 and it is on the command path. java -version should show version 11 and you can run the application.

If you want to run using Java 8 JDK/JRE you should build the sources from this repository, just disable the JDK 11 checks in two of the maven pom files. Then running on JDK 8 will also work.

So it is not really a WebGoat issue.

Please be aware that you perhaps need to skip the unit tests as mentioned in my pull request and also that running unit tests and on IBM Java will fail as well. Running the app on IBM JDK 8 is ok. Running on JDK 11 makes the billion laughs attack harder

**Comment by CaosFR** [comment]
Hi,

TY for your help. So I have add the JDK 11 to my path and force webgoat start with this instead of JRE 8. Now the program could run but if I go to web goat url I have a blank page.

May my log could help you (I have see few warning inside)
I have try different port (8080,9090,1616) and address (127.0.01, 192.168.10.1, localhost) but same issue.
[webgoat_log.txt](https://github.com/WebGoat/WebGoat/files/2987231/webgoat_log.txt)

TY

**Comment by zubcevic** [comment]
http://127.0.0.1:8080/WebGoat
is the starting point. The context root is very important.
java -Dfile.ecoding=UTF-8 -jar webgoat-server-8...jar

**Comment by CaosFR** [comment]
It's work now :) :+1: 

Thanks

**Comment by zubcevic** [comment]
Great, perhaps you can close the issue now

**Comment by davewichers** [comment]
FYI, an easy way to switch between different Java versions on practically all platforms is to use: jabba (https://github.com/shyiko/jabba). I've only used the Windows 10 version, which works great. I've been using jenv (https://www.jenv.be/), but this hasn't been updated in over 5 years and so doesn't support Windows 10, but seems to work for Linux still just fine.
@zubcevic - I think you, or someone on the WebGoat team, should just close this ticket.
