### ISSUE TITLE
jwt lesson 7 cannot be solved, credentials in the source code

### ISSUE THREAD

**Issue by halfluke** [WebGoat/WebGoat#575]
Please see here

https://www.reddit.com/r/Pentesting/comments/8xxozf/webgoat_8_authentication_flaws/

**Comment by nbaars** [comment]
@halfluke correct the most critical part is missing, added it to the lesson now you should be able to find out how the login as Jerry works and also have an idea how the other endpoints must be invoked to solve the lesson
