### ISSUE TITLE
Unable to use standalone WebWolf running om the IP other than localhost

### ISSUE THREAD

**Issue by serega2k** [WebGoat/WebGoat#582]
I'm getting an error "There was an error while sending the e-mail. Is WebWolf running?
I/O error on POST request for "http://localhost:9090/mail": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect" when I'm trying to send an email to WebWolf from WebGoat.
Both of them are standalone mapped to IP 10.110.5.59

**Comment by zubcevic** [comment]
If you want to override settings, check my example in: [webgoat-training](https://github.com/zubcevic/webgoat-training) 
Especially the nondefault folder. In your case adjust the parameters for the webwolf host in both property files.

**Comment by serega2k** [comment]
Thank you a lot! It helped!
