### ISSUE TITLE
I'm logged in as admin but I can't see any admin function (8.0.0.M24)

### ISSUE THREAD

**Issue by serega2k** [WebGoat/WebGoat#583]
Hi
I wonder if there is an option to see an admin dashboard where I can track the progress of my trainees?
And if it present - how to get access to it? I'm logged in as admin (WEBGOAT_ADMIN role)

**Comment by nbaars** [comment]
@serega2k at the moment there are no admin functions, the current roles were ported from the old version but have no effect. We will add admin functionality back into WebGoat in the near future. For now I will close this issue
