### ISSUE TITLE
challenge8 - Not solvable because of GET mapping?

### ISSUE THREAD

**Issue by JoeFound** [WebGoat/WebGoat#584]
https://github.com/WebGoat/WebGoat/blob/bb7fb3f197f3a01cd2a070fc8decc070724ed72e/webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/plugin/challenge8/Assignment8.java#L37

If I got the goal of this challenge right, it seems that challenge8 cannot be solved because of the \@GetMapping annotation that forces the mapping to the *GET* Method and the check for the solution that requires that the Request Method is not *GET*.

https://github.com/WebGoat/WebGoat/blob/bb7fb3f197f3a01cd2a070fc8decc070724ed72e/webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/plugin/challenge8/Assignment8.java#L42

A possible resolution for this issue could be to use \@RequestMapping annotation without defining the method attribute

**Comment by nbaars** [comment]
@JoeFound no this is not an issue, you are on the right track: is there a http method which is actually a GET as well?
