### ISSUE TITLE
No indication for exercise completion - Google Chrome Developper Tools chapter

### ISSUE THREAD

**Issue by gaelletjat** [WebGoat/WebGoat#599]
In the **General section**
**Google Chrome Developper Tools** chapter, there is no indication for the exercise completion.
I used both Google Chrome and Firefox for the same result (exercise completion color not turning green) as you would see in the screenshots below.

<img width="1431" alt="developper_tools" src="https://user-images.githubusercontent.com/13528237/57984034-5ffb1f00-7a0c-11e9-9a0e-2519105c6d69.png">

<img width="1431" alt=" network_tab1" src="https://user-images.githubusercontent.com/13528237/57984045-786b3980-7a0c-11e9-80d2-c272fd9433b1.png">

<img width="1438" alt=" network_tab2" src="https://user-images.githubusercontent.com/13528237/57984054-84ef9200-7a0c-11e9-8304-9658a534770b.png">

Please advise.

Thank you

**Comment by zubcevic** [comment]
I think you are right and it seems to be related to the fact that these exercises are reusing functionality from other categories like CrossSiteScripting. Maybe the team of @MaxGeldner can think of a solution for this.

**Comment by MaxGeldner** [comment]
Hello. We had this issue earlier with other assignments aswell. It was not present in the built version of WebGoat, only when starting it via e.g. IntelliJ.  Does this happen in the built version as well, @GaelleTjat?
I looked into the issue when we noticed the bug, but couldn't find anything that would cause it. Unfortunately at the moment I have no idea how to fix it (also because time passed since I last worked with WebGoat). If I got time I'll try to look into it again.

**Comment by GaelleTjat** [comment]
Hello @MaxGeldner , thank you for following up. Yes. The issue is present in the current version of WebGoat.
Will be looking forward for the resolution.
Thank you

**Comment by davewichers** [comment]
We noticed this issue last night as well, when running webgoat like so: java -jar webgoat-server-8.0.0.M25.jar

**Comment by MaxGeldner** [comment]
Hello. Unfortunately I didn't really have time to look into it in the last few weeks and I wont have much time for the next two weeks either.

**Comment by zubcevic** [comment]
I will take a look and try to fix this. As part of the fixes for #619

**Comment by zubcevic** [comment]
done in latest develop

**Comment by jugges** [comment]
@zubcevic Is there a plan to release a new version including these new fixes?
