### ISSUE TITLE
Lessons on session management flaws and weak session IDs

### ISSUE THREAD

**Issue by Maktm** [WebGoat/WebGoat#602]
What happened to the session management flaws that were available in WebGoat 7? I can't find them in WebGoat 8? Are they just being added in slowly or am I missing something? I tried searching through release notes to see if the change was mentioned but could not find anything.

**Comment by misfir3** [comment]
Yeah, our intent was to slowly add back in items/lessons ... quality and updated content are a focus, but our pace is really slow currently.

**Comment by Maktm** [comment]
Good to know. I'll leave this issue open so that i can be closed once it's added or you can just close it out if you deem it closeable. Thanks for the response! :)
