### ISSUE TITLE
webgoat doesn't take into account the --server.adresse to allow remote connections

### ISSUE THREAD

**Issue by h-rueda** [WebGoat/WebGoat#603]
Download the webgoat standalone server in a virtual machine (VM)
Execute java -jar webgoat-server-8.0.0.M25.jar --server.adresse=<IP adresse>

Open a browser in another compet and type <IP adresse>:8080/WebGoat

Result:
The connection is refused

**Comment by zubcevic** [comment]
With #596 you can use the WEBGOAT_HOST and WEBWOLF_HOST variables to change the server address

**Comment by zubcevic** [comment]
or you can override all settings using something similar like:  https://github.com/zubcevic/webgoat-training/tree/master/nondefault

**Comment by davewichers** [comment]
@h-rueda - this feature works for me. Are you truly trying to set the server address to blank? That won't work. You have to set it to a valid hostname or IP address. And of course you have to spell the parameter correctly.  Try again like so: java -jar webgoat-server-8.0.0.M25.jar --server.addresse=YOURIPADDRESS, and if you use your correct IP, then navigating to: http://YOURIPADDRESS:8080/WebGoat should work just fine.  You can also verify it works by using: localhost    first, as the IP address to verify that works first, before trying a specific IP address or hostname.

**Comment by nsilver7** [comment]
I'm also having this issue and trying to understand if it's an application issue or a routing issue.

If I invoke the standalone jar like so: 
`sudo java -jar webgoat-server-8.0.0.M25.jar --server.address=10.116.10.158 --server.port=80`

Then test locally on this server:
`curl -IkL http://localhost/WebGoat
curl: (7) Failed connect to localhost:80; Connection refused`

`curl -IkL http://10.116.10.158/WebGoat
HTTP/1.1 302
Location: http://10.116.10.158/WebGoat/
...`

So it appears to be accepting the parameters.  However when attempting to access webgoat over a network link, it fails to accept the connection.  SYN timeout again and again.

**Comment by zubcevic** [comment]
I do not think that you can use two -- arguments in spring boot. 
See also https://www.baeldung.com/spring-boot-command-line-arguments 

You can checkout #596 or https://github.com/zubcevic/webgoat-training/tree/master/nondefault to see examples of overriding multiple settings together.

**Comment by nsilver7** [comment]
If that were true, wouldn't the curl commands have failed to connect on port 80 (I believe default is 8080)?

Regardless the application isn't accepting on port 80 or 8080 via network.  I have a few ideas I want to try out today, one of them being to nginx proxy the request to webgoat.  Will post back if I can figure out a solution.

**Comment by nsilver7** [comment]
OK so the nginx reverse proxy is one solution to this issue, though I admit do not understand what the root cause problem is.. 

so run WebGoat jar in its default configuration (localhost:8080) then install nginx and add this or something similar to your conf

```
server {
    location / {
        proxy_pass http://localhost:8080
    }
```

**Comment by abcsell** [comment]
It seems that the internal IP is a variable. Neither jar package nor server.adress can be modified. Unless you compile it yourself, reverse proxy is a good way

**Comment by zubcevic** [comment]
#731 It should now be possible to run WebGoat and WebWolf behind a reverse proxy.

There were some links and things that needed adjustments. Like when WebGoat sends requests to WebWolf in the XXE and password reset cases.

You can see a preview of this with docker swarm/stack example in: https://github.com/zubcevic/webgoat-training/tree/master/docker-swarm

However this example requires you to create a local docker image from the latest WebGoat develop branch: And then tag it as: webgoat/webgoat-8.0:test

**Comment by zubcevic** [comment]
#737 shows a solution for this
