### ISSUE TITLE
ellipses in lessons become garbled i.e., (Ã¢â‚¬Â¦)

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#605]
Looking at the source for: SqlInjection_introduction_content2.adoc, I see this text: "confidentiality (…) & integrity (update)"

However, when you look at the content in WebGoat itself: http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/2, I'm seeing this text as: "confidentiality (Ã¢â‚¬Â¦) & integrity (update)"

As you can see, the ellipses (i.e., the ... ) are becoming garbled.  I've noticed this throughout the SQL Injection lessons in WebGoat and there may be more of these in other lessons as well. The above is just one instance, as an example.

Can you figure out the cause and fix it, or eliminate the use of ellipses (e.g., by using dot space dot space dot, or something) so these garbled characters go away.

**Comment by zubcevic** [comment]
seems similar to #544

did you try
I have noticed the same issue when the OS is e.g. Windows. Then the start screen also has one strange set of characters in the middle of the content. This is resolved by forcing the file encoding at start of the JVM.

java -Dfile.encoding=UTF-8 -jar webgoat-server.....

**Comment by davewichers** [comment]
When I try: java -Dfile.encoding=UTF-8 -jar webgoat-server....., with both Java 8 and Java 11, I get this error:

Error: Could not find or load main class .encoding=UTF-8
Caused by: java.lang.ClassNotFoundException: /encoding=UTF-8

I think this used to be supported by Java (not sure), but apparently the way you are supposed to do this is to instead set:  JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"  first, and then run webgoat as normal.

If you have done it right, you'll see:  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8    as the first line of output immediately after starting WebGoat.

Given that this works, seems like the proper solution to this is for WebGoat itself to set this parameter during its startup sequence, or to create a WebGoat start script that first sets this option, and then launches WebGoat such that this 'just works' on all platforms without users having to know about this 'special' launch option to get it to work properly.  Seems like creating such a script for Windows and Linux, wouldn't be that hard.  This script should also be written to accept the address and port number parameters so they can optionally be passed to the script directly, rather than having to hack the script itself to set those parameters.

**Comment by nbaars** [comment]
@davewichers and @zubcevic seems related to Tomcat as well, as we moved to Undertow as web server the problem seems to be fixed. I tested on Windows and previously I use to see ` confidentiality (Ã¢â‚¬Â¦)` in the SQL lesson but in the new version I can see `confidentiality (…)` as present in the underlying asciidoc source file

So when we release M26 this should be fixed

**Comment by nbaars** [comment]
Actually fix with a commit by @zubcevic which sets the encoding of the adoc files
