### ISSUE TITLE
docker build -t webgoat/webgoat-8.0 fails

### ISSUE THREAD

**Issue by texnokot** [WebGoat/WebGoat#606]
Hi,

tried today to run:
`docker build -t webgoat/webgoat-8.0 .`
after cloning the repo and following instructions from documentation. But got:
```
Step 6/9 : COPY target/webgoat-server-${webgoat_version}.jar /home/webgoat/webgoat.jar
COPY failed: stat /var/lib/docker/tmp/docker-builder109324338/target/webgoat-server-v8.0.0-SNAPSHOT.jar: no such file or directory
```

Tried on different OS and places. Get the same.

**Comment by pasdam** [comment]
Did you build the WebGoat artifact before running that command as described in the [README](https://github.com/WebGoat/WebGoat#docker-on-x86)? In particular I believe you might be missing the following line:

```sh
mvn install
```
