### ISSUE TITLE
SQL Injection (intro) (Stage 2) Please make SQL query box bigger

### ISSUE THREAD

**Issue by JonathonWichers** [WebGoat/WebGoat#607]
This is a minor usability issue.

Can you make the SQL query input field bigger on this page, and on stage 3-5 as well? The attack query is far larger than the input field, so most of the text scrolls out of sight.

**Comment by zubcevic** [comment]
seems the same as #544 
did you try with UTF-8

I have noticed the same issue when the OS is e.g. Windows. Then the start screen also has one strange set of characters in the middle of the content. This is resolved by forcing the file encoding at start of the JVM.

java -Dfile.encoding=UTF-8 -jar webgoat-server....

**Comment by zubcevic** [comment]
Sure, I will do that. But feel free to make a pull-request through forking and contributing.

**Comment by zubcevic** [comment]
done
