### ISSUE TITLE
Eclipse Errors 

### ISSUE THREAD

**Issue by hgrov52** [WebGoat/WebGoat#612]
Following the provided instructions as well as #593, I am still getting many errors when I try to build the master branch in Eclipse. I have tried 
-building eclipse files with maven then importing general project
-importing as a maven project and building with external maven installation

I am using Maven 3.6, JDK 11 and Eclipse 2018-12. 

Are there any further instructions needed than those provided? There must be something that I'm missing.

**Comment by zubcevic** [comment]
You should also have lombok support installed in Eclipse
