### ISSUE TITLE
为啥我这个启动不起来！

### ISSUE THREAD

**Issue by KuanKuanya** [WebGoat/WebGoat#616]
一开始启动类错误StartWebGoat启动类没写Strat这个我加上了这个服务能启动了，另一个webwolf启动不了咋回事一个org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to obtain JDBC Connection
Bean注入错误
一个
![9RX%49DESFL8%3H%0GUA)H0](https://user-images.githubusercontent.com/36219704/60760261-0ce53600-a065-11e9-8df9-7e1861ef8190.png)
java.net.ConnectException: Connection refused: connect拒绝连接错误

**Comment by zubcevic** [comment]
不知道为啥.
probably a port conflict. Check if port 8080, 9090 and 9001 ! are free or change the values in application.properties. 9001 is used by the in-memory database. If that fails the entityManagerFactory will also fail

**Comment by supenghao** [comment]
端口被占用了
 
---原始邮件---
发件人: "René Zubcevic"<notifications@github.com>
发送时间: 2019年7月12日(星期五) 中午1:58
收件人: "WebGoat/WebGoat"<WebGoat@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [WebGoat/WebGoat] 为啥我这个启动不起来！ (#616)



不知道为啥.
 probably a port conflict. Check if port 8080, 9090 and 9001 ! are free or change the values in application.properties. 9001 is used by the in-memory database. If that fails the entityManagerFactory will also fail

**Comment by zubcevic** [comment]
你应该看看 https://github.com/zubcevic/webgoat-training/tree/master/nondefault 
或者 #596

**Comment by nbaars** [comment]
Merged, thanks @zubcevic

**Comment by zubcevic** [comment]
Are your issues resolved?

**Comment by KuanKuanya** [comment]
没解决，后来没用，因为对这个不是太熟悉，有些东西解决不了

**Comment by KuanKuanya** [comment]
当时没等到你的回复后来就忘了登录github了，今天登录看到了你给我发的消息了，回头我试试

**Comment by KuanKuanya** [comment]
> 您的问题已解决吗？

对了，我还想问一下这个有对应的渗透教程嘛？

**Comment by KuanKuanya** [comment]
> 您的问题已解决吗？

我的问题已经解决了，今天下载了一份最新的然后重新弄了一下就可以了，你的那个webgoatserver下的启动类还是没改哈哈，还是错的呢，看了下你写的代码感觉很棒，有时间研究下

**Comment by KuanKuanya** [comment]
看了大佬写的感觉脑壳有点疼，都是英文对于我这种英文很low的人来说有点难搞
![image](https://user-images.githubusercontent.com/36219704/61729716-6d38df00-adaa-11e9-9272-c04832d7e93a.png)

**Comment by nbaars** [comment]
As far as I can tell this issue has been resolved, @KuanKuanya closing the issue
