### ISSUE TITLE
Issue with lesson validation

### ISSUE THREAD

**Issue by PiAil** [WebGoat/WebGoat#619]
I'm trying to make a walkthrough for all the lessons, and I'm facing bugs with lots of them:

**Introduction** - WebWolf:

4 The **Save** field on the reset password page appears to be buggy. It performs a POST to http://webwolf:9090/landing , which is not a valid address with the basic installation via Docker.

**General** - Google Chrome Developer Tools

4, 6 Validation does not work.

**Injection Flaws** - SQL Injection (advanced)

3, 5 Validation does not work. 

**Injection Flaws** - SQL Injection (managed)

6 Example code does not work.
```
try {
    Connection conn = null;
    System.out.println(conn);   //should output 'null'
} catch (Exception e) {
    System.out.println("Oops. Something went wrong!");
}
```
Error message:
```
Could not compile code:
error while writing TestClass: /TestClass.class
```

I haven't checked other lessons for the moment. There is maybe something I didn't get, don't know.

**Authentification Flaws** - Password Reset

6  Validation does not work. 

**Authentification Flaws** - JWT Tokens

4, 7 Validation does not work.

**Comment by zubcevic** [comment]
Yes, you are right. The way the validations are linked to the coloured buttons and the categories behind them is not always resulting in the expected UI behaviour. I will look into the mentioned problem areas and try to fix it. Or perhaps consider that mechanism for re-design.
So currently, the validation in terms of correct/incorrect work, but the progress markers do not always show that.

As for the other observation SQL managed 6 I will also check this.
By the way I removed the "solution" parts of your answer, so it can remain a challenge for others as well

**Comment by zubcevic** [comment]
Can you check if it is ok for you now? As for the example code: That is not the right solution. The correct solution works fine.

**Comment by PiAil** [comment]
It is better yeah ! Here the bugs I still have. Note that I'm running Webgoat and Webwolf on localhost, not with Docker anymore, so it may change things related to Webwolf.

**Introduction** - WebWolf:

3: ```There was an error while sending the e-mail. Is WebWolf running?``` WebWolf is running on localhost.

**(A1) Injection** - SQL Injection (advanced):

5: Lesson number does not turn green on validation.

**(A1) Injection** - SQL Injection (mitigation):

10: Broken ?  A request to /servers get a 404 error in response, and no more servers are displayed in the list of servers.

**(A2) Broken Authentification** - Password reset:

2: Same as **Introduction** - WebWolf - 3.: cannot send an email.
6: Lesson number does not turn green on validation.

**(A2) Broken Authentification** - JWT tokens:

4: ```io.jsonwebtoken.MalformedJwtException: JWT strings must contain exactly 2 period characters. Found: 0``` I used to be able to validate this lesson before, but I keep getting this error now.
7: This challenge does not provide enough information to be solved. See #575.
8: I Don't know how to solve this one the intended way, but before the update we could do something similar to 4. which, given the hints, should be forbidden. I don't know how it is after the update.

**(A3) Sensitive Data Exposure** - Insecure Login:

2: Lesson number does not turn green on validation.

**(A5) Broken Access Control** - Insecure Direct Object references:

3: Lesson number does not turn green on validation.


**(A7) Cross-Site Scripting (XSS)** - Cross Site Scripting / Cross Site Scripting (stored) / Cross Site Scripting (mitigation):

All: No green checkbox on the leftside panel after all lessons have been completed.

**(A8) Insecure Deserialization** - Insecure Deserialization

5. No hints are provided I found this a tough one.

I did not test the last lessons, I will edit his message if I find anything else.

**Comment by zubcevic** [comment]
I should also mention that the H2 database ‘lives’ in ~/webg... 
so before you start you could delete this or at least press the reset lesson. 
Seems to me that you have a connectivity issue with webwolf. it is important that webgoat is fully started first, before starting webwolf. as the latter one needs to connect to the in memory database of webgoat

**Comment by PiAil** [comment]
I should have mentionned I run everything on Windows. It was a fresh install, because before that, I was running everything with Docker. 

I did not found the database, but I tried the reset button and to restart both WebGoat and WebWolf (with WebGoat first) and it did not work either.

 Both seems 'connected' because my WebGoat user/password works in WebWolf (not sure if this is linked to the mentionned database, but whatever).

**Comment by PiAil** [comment]
I just  uploaded a full guide of the VM on the [Wiki](https://github.com/WebGoat/WebGoat/wiki/(Almost)-Fully-Documented-Solution-(en)). 

I put warning for each of the lesson that cannot be completed or that have UI bug.

There are probably lots of typo or misunderstanding, but it's a try.

**Comment by nbaars** [comment]
@PiAil thanks!! 💯

**Comment by zubcevic** [comment]
The latest development effort is focussed on getting the lesson completion fully tested. This has been done for sql, xss, xxe, jwt and others. So even though some problems could still exist, I recommend to issue concerns per lesson.
