### ISSUE TITLE
Spelling errors in: webgoat_developer_bootstrap.sh

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#63]
in: webgoat_developer_bootstrap.sh

You might want to fix the 3 spelling / grammar errors in this:

 Starting WebGoat using the embbebed Tomcat ___________________
###################################################################################
### Open a web broser an navigate to http://localhost:8080/WebGoat/

Embedded, browser, and 'and navigate to...'

**Comment by mayhew64** [comment]
Fixed and pushed to master
