### ISSUE TITLE
[Low] Redirect from / to /WebGoat/

### ISSUE THREAD

**Issue by AntonKuzminRussia** [WebGoat/WebGoat#635]
Hello. Please, add redirect  from / to /WebGoat/. Response 404 in / confusing because you don`t wait it. For example: i new guy, got docker image, start it and see 404. Wtf?
I seen issue 173, but there is no solution, only added text to stdout about /WebGoat/. Fix it please for more comfort. Thanks.

**Comment by nbaars** [comment]
In Spring we set the context path to WebGoat, so it's not as straightforward as it seems ('/' will no longer be served by Spring). I agree it would be a nice improvement but we need to support two context path which is doable but takes some work.

**Comment by zubcevic** [comment]
Did you checkout the WebGoat and WebWolf with the build in NGINX reverse proxy: 
sudo docker run --name webgoat -d -p 80:8888 -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam --restart unless-stopped webgoat/goatandwolf

Is that a good enough solution?

**Comment by zubcevic** [comment]
As I did not receive a reply, I guess the proposed solution is good enough
