### ISSUE TITLE
webwolf project can't start

### ISSUE THREAD

**Issue by QuietAn** [WebGoat/WebGoat#637]
The instructions read:

command:    java -jar webwolf-v8.0.0-SNAPSHOT.jar

error msg:
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to obtain JDBC Connection;

Caused by: org.hsqldb.HsqlException: java.net.ConnectException: Connection refused (Connection refused);

What should I do?

**Comment by nbaars** [comment]
Hi @QuietAn,

Did you start WebGoat first? As WebWolf shares the DB with WebGoat this one needs to be started first. Let us know if this solves the issue

Kind regards,
Nanne

**Comment by QuietAn** [comment]
> Hi @QuietAn,
> 
> Did you start WebGoat first? As WebWolf shares the DB with WebGoat this one needs to be started first. Let us know if this solves the issue
> 
> Kind regards,
> Nanne

Dear Nanne,

Thank you very much. 
When I started it, it worked fine.
