### ISSUE TITLE
When run the code i am getting build error issue

### ISSUE THREAD

**Issue by Karthikn123** [WebGoat/WebGoat#640]
After executing this command mvn -pl webgoat-server spring-boot:run , i am getting build error. Please help me to resolve this issue

![image](https://user-images.githubusercontent.com/24472347/63038994-fcd03a00-bedf-11e9-9dd8-5e67898e328a.png)

**Comment by nbaars** [comment]
@Karthikn123 Thanks for trying WebGoat, can you try to first run `mvn clean install` in the `WebGoat` directory? Seems like the dependent projects were not build yet

Let us know if this solves the issue. 

Thanks,
Nanne

**Comment by zubcevic** [comment]
There is no issue in building and running. Just make sure you do it at the right level.
mvn clean install
then
java -jar webgoat-server/target/webgoat-server-v8.0.0-SNAPSHOT.jar
not just build webgoat-server
