### ISSUE TITLE
Exclude From Proxy does not work

### ISSUE THREAD

**Issue by TJ-C** [WebGoat/WebGoat#641]
The instructions shown on this page do not work. WebGoat/start.mvc#lesson/HttpProxies.lesson/4

http://localhost:8080/WebGoat/services/.*
http://localhost:8080/WebGoat/.*.lesson.lesson

The history view continues to show all traffic and it's not possible to trap the POSt request.

**Comment by ankitparashar12** [comment]
Just replace localhost with 127.0.0.1 and it will work.

**Comment by TJ-C** [comment]
It makes no difference. The exclude proxy dialog box is looking for a regex, do you know what the correct regex format it's looking for?

**Comment by zubcevic** [comment]
The following works on ZAP 2.8.0:
.*/WebGoat/service/.*.mvc

I will update the documentation. However with other fully qualified server names it seems to work fine.
