### ISSUE TITLE
Reflected XSS Attacks error message error

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#65]
The error message is supposed to say something like:

'Whoops you entered an invalid 3 digit code CODE.'  Or something like that. 

Instead it displays: * ReflectedXSSWhoops1111testReflectedXSSWhoops2

where 111test is what I entered in the last field of the lesson.

**Comment by mayhew64** [comment]
Looks like the check for the successful attack could be a bit better as well.  We need to tighten that up.  The following attack string cleared the lesson: 111<script?alert("xss")</script>  The success criteria is checking for "script".  Is there a way to check on the client if an actual script was fired?

**Comment by misfir3** [comment]
Will look at this next ... but not tonight.

**Comment by misfir3** [comment]
Think I know what's going on here ... looking to see if I can integrate better detection without having too many disparate chunks of code to manage it.

**Comment by misfir3** [comment]
was looking at this yesterday and was no longer able to reproduce. @davewichers, are you still seeing it with latest updates?

**Comment by misfir3** [comment]
Finally getting back to this. Error message should be sorted. Dealing with the alert not firing twice now. Pull request to WebGoat-Lessons to follow.

**Comment by misfir3** [comment]
Pull request completed, closing
