### ISSUE TITLE
Disable "register of new users"

### ISSUE THREAD

**Issue by pmvr** [WebGoat/WebGoat#652]
How is it possible to disable user registration in WebGoat 8?

It would be nice to disable this functionality if class is complete.

Thanks!

**Comment by zubcevic** [comment]
The best thing would be to set up a reverse proxy and control the access to WebGoat and WebWolf specific url's and then at some point block the register link. Depends on your classroom set up.

Example Nginx reverse proxy config. (Without blocking the register page). 
https://github.com/zubcevic/webgoat-training/blob/master/nginx/nginx.conf
This will only work correctly for WebGoat and WebWolf from latest develop
