### ISSUE TITLE
WebGoat 8 access logs on ubuntu 18.04

### ISSUE THREAD

**Issue by cjmharris** [WebGoat/WebGoat#653]
Hi all,

I am new to using WebGoat and running it on Ubuntu 18.04 using the jar file. 

Is it possible to view the access logs for this, I basically I want to learn how to attack and then how to spot those attacks from looking at the logs.

Any help or advice appreciated, thanks

**Comment by zubcevic** [comment]
Maybe something like:
/bin/nohup java -jar webgoat.jar > output.log &
tail -300f output.log

It is not really a WebGoat related issue, but more some ubuntu/linux specific question, right?

Actually, you should not need the log to learn how to attack. And indeed it depends on the lesson if there is something in the log. The log is useful for you to check if WebGoat started correctly.

With this answer, can we close the issue?

**Comment by cjmharris** [comment]
Hi Zubcevic,

Thanks for your reply. 

My query was in regards to the access logs. For example if the device was running Tomcat, we would be able to look at the access logs, but as its all contained and run from the jar, I am unsure if we would be able to see such logs. This would be for defense purposes, so we could attack, then using the logs we could analyse and learn how to defend against them. 

Hope this make sense.

**Comment by zubcevic** [comment]
then my above answer about redirecting the application output of java -jar is sufficient. Good luck!
