### ISSUE TITLE
In High concurrency, the response is strange.

### ISSUE THREAD

**Issue by yywing** [WebGoat/WebGoat#654]
I use scanner to scan it in high concurrency, and I found this,(Phishing with XSS)
![图片](https://user-images.githubusercontent.com/22928185/64670897-3f624380-d499-11e9-8224-725a5b22cd67.png)
repate it, then
![图片](https://user-images.githubusercontent.com/22928185/64670904-42f5ca80-d499-11e9-84dd-05c3c59f1165.png)

Version: 7.0.1, Build: build

**Comment by zubcevic** [comment]
Well WebGoat is meant as an insecure environment where you can learn about vulnerabilities. It is not meant as a production ready high volume  website. It could be that there are concurrency issues. But for the normal assignments by yourself or in some class of a few people, this will not likely lead to any issues. So what is you suggestion?

**Comment by nbaars** [comment]
Closing the issue as no input, we are not going to work actively on this issue as @zubcevic indicates this is not really a requirement for the app. Feel free to create a PR to solve the issue
