### ISSUE TITLE
Link(s) do not take non-localhost addresses into account

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#659]
I haven't yet checked for other pages, but on this page: http://example.com:8080/WebGoat/start.mvc#lesson/Challenge.lesson

the link about the scoreboard is http://localhost:8080/WebGoat/scoreboard rather than http://example.com:8080/WebGoat/scoreboard, where `example.com` is based on:

```sh
java -jar webgoat-server.jar --server.port=8080 --server.address=example.com
```

**Comment by zubcevic** [comment]
I will pick this up as part of #731 and close this issue as it would be duplicate otherwise.
