### ISSUE TITLE
Eclipse import error for webgoat-container

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#66]
When I import the webgoat-container project into Eclipse, I get this error:
No marketplace entries found to handle Execution create-jar, in /webgoat-container/pom.xml in Eclipse.  Please see Help for more information.

**Comment by mayhew64** [comment]
We need a wiki page to show how to create a lesson.  The existing in WebGoat lesson in for 6.x legacy.  This should be outside of the running application anyhow.

**Comment by nbaars** [comment]
This issue has been solved. The issue solved by @slavP also solved this issue.
Downloaded Eclipse and imported webgoat-container automatically worked. Closing this issue
