### ISSUE TITLE
Broken link in Password Reset Lesson 1

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#660]
Perhaps related to my previous issue: #659, but I am not sure.

At: http://example.com:8080/WebGoat/start.mvc#lesson/PasswordReset.lesson/1

The text reads as:

> Email functionality with WebWolf
> Let’s first do a simple assignment to make sure you are able to read e-mails with WebWolf, first start WebWolf (see [http://]()) In the reset page below send an e-mail to username@webgoat.org (part behind the @ is not important) Open WebWolf and read the e-mail and login with your username and the password provided in the e-mail.

The link is clearly not what it is supposed to be.

![image](https://user-images.githubusercontent.com/8146593/65315260-0fe9c000-db98-11e9-8f82-08b5a53e0ed2.png)

**Comment by zubcevic** [comment]
Fix in #680

**Comment by John977r** [comment]
http://example.com:8080/WebGoat/start.mvc#lesson/PasswordReset.lesson/1

**Comment by John977r** [comment]
Hello Team
I lose access to my phone number, Recovery email and even password for my Gmail account.wangxiaoqian250@gmail.com. on the recovery process enable to receiving a password kinly help me grant access to my Gmail account

**Comment by John977r** [comment]
![Uploading Screenshot_20230722-013244.jpg…]()
