### ISSUE TITLE
SQL: Cannot use apostrophe/quotes on string literals

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#662]
In SQL Injection lesson 5 (http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/4) and probably some others, apostrophes and quotes are not accepted.

Issue is similar to #661.

**Expected**
```mysql
-- Should be working:
GRANT ALTER TABLE TO UnauthorizedUser;

-- Should also be working:
GRANT ALTER TABLE TO 'UnauthorizedUser';

-- Should also be working:
GRANT ALTER TABLE TO "UnauthorizedUser";
```

**Actual**
```mysql
-- Works:
GRANT ALTER TABLE TO UnauthorizedUser;

-- Does not work (!):
GRANT ALTER TABLE TO 'UnauthorizedUser';

-- Does not work either (!):
GRANT ALTER TABLE TO "UnauthorizedUser";
```

**Comment by nbaars** [comment]
Did not fix the double quotes as it has a different meaning might be part of the table name etc, makes thing way too complicated
