### ISSUE TITLE
SQL Injection lesson 6 minor mistakes in examples

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#663]
In SQL Injection lesson 6 (http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/5), you have examples that do not show correct results: the quotes that are present in the beginning are missing at the end.

![Wrong quotations](https://user-images.githubusercontent.com/8146593/65379736-542aac80-dccd-11e9-8f33-e5c5dedd802e.png)

Trivial things, but it should be fixed.

**Comment by nbaars** [comment]
Fix in v8.0.0.M26
