### ISSUE TITLE
SQL Injection lesson/exercise 9 inconsistent use of casing

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#664]
This is a trivial issue, but it is quite sloppy in my perhaps not-so-humble opinion.
http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/8

In multiple lessons the casing hasn't been consistent, but lesson 9 is quite bad.

![image](https://user-images.githubusercontent.com/8146593/65380006-69eea080-dcd2-11e9-8983-3066e3fda3e6.png)

_Look at the yellow markings._

(I filed the red markings in a separate issue, because it is not the same: #665)

**Comment by nbaars** [comment]
Fix in v8.0.0.M26
