### ISSUE TITLE
SQL Injection lesson/exercise 9 missing 'WHERE'

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#665]
Link: http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/8

The `WHERE` keyword is missing and the table `user_data` is once written as `users_data`.

![image](https://user-images.githubusercontent.com/8146593/65380017-b2a65980-dcd2-11e9-963e-6bc972f68275.png)

_Look at the red markings._

Relates to issue #664 about inconsistencies of yellow markings.

**Comment by nbaars** [comment]
Fix in v8.0.0.M26
