### ISSUE TITLE
Replace my-shop.com with 'shop.example.com'

### ISSUE THREAD

**Issue by pedzed** [WebGoat/WebGoat#666]
Issue relates but is probably not limited to: 
- SQL Injection (Advanced) Lesson 4 — http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjectionAdvanced.lesson/3

Several times a link has been added to `https://my-shop.com`. This should be changed to https://shop.example.com because [example.com](https://example.com) is a reserved domain name (see: [RFC 2606](https://tools.ietf.org/html/rfc2606) and [RFC 6761](https://tools.ietf.org/html/rfc6761)) for such use.

![image](https://user-images.githubusercontent.com/8146593/65389263-a531b380-dd54-11e9-886c-9f359fa00501.png)

**Comment by nbaars** [comment]
Fix in v8.0.0.M26
