### ISSUE TITLE
https://www.owasp.org/index.php/How_to_write_a_new_WebGoat_lesson obsolete

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#67]
I recommend you search around the OWASP Wiki and look for articles like this and either delete them, update them, or point them to where the latest information of this type exists.

**Comment by mayhew64** [comment]
Need to link the OWASP page to the Create a lesson Wiki.

**Comment by nbaars** [comment]
Closing as the page no longer exists
