### ISSUE TITLE
Update lesson information with latest Firefox and ZAP 2.8.0 HUD info

### ISSUE THREAD

**Issue by zubcevic** [WebGoat/WebGoat#678]
Some lessons are outdated:

- Latest Firefox standalone will always ignore proxy setting for localhost and 127.0.0.1
- ZAP 2.8.0 exclude from proxy need some better regular expressions in case of localhost
- Some screenshot updates on HUD and 2.8.0

**Comment by zubcevic** [comment]
If the Firefox browser is started and controlled by ZAP, the proxying is working on localhost, but if started standalone it will always be ignored. In that case you can define your own hostname to be used and map that in your host file to IP 127.0.0.1. Then Firefox will proxy the requests just fine.

**Comment by nbaars** [comment]
See https://github.com/zaproxy/zap-core-help/blob/9b772751e493dec0a1418d216e3cf5d38d15d48f/addOns/help/src/main/javahelp/contents/start/proxies.html#L45 for more information as well and another workaround. 

Think we need to integrate this somehow in the lesson?

**Comment by zubcevic** [comment]
Yes I will update the lesson sometime soon

**Comment by nbaars** [comment]
Did a small update to the lesson, just to get it working in FF again. Did not describe the new ZAP HUD etc.
