### ISSUE TITLE
Need instructions on how to add a new WebGoat Lesson Category

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#68]
Its not hard, but figuring this out yourself with no instructions is a pain.

Showing them how to update the Category class and then update the configuration file(s) to add the new lesson(s) so they show up in the left hand menu would be very helpful.

**Comment by mayhew64** [comment]
Add to the how to create a lesson wiki

**Comment by nbaars** [comment]
Is a lesson in WebGoat 8.0 no need for the wiki
