### ISSUE TITLE
Malicious File Execution SQL Injection

### ISSUE THREAD

**Issue by erichappe** [WebGoat/WebGoat#694]
**What happened?**
We tracked the following data from Multipart File Name:

```
POST /WebGoat/attack?Screen=2027530490&menu=1600

------WebKitFormBoundaryQ2f4k6AzhYN6xBSG
Content-Disposition: form-data; name=&quot;myfile&quot;; filename=&quot;image.jpg&quot;
Content-Type: image/jpeg

Omitted
------WebKitFormBoundaryQ2f4k6AzhYN6xBSG
Content-Disposition: form-data; name=&quot;SUBMIT&quot;

Start Upload
------WebKitFormBoundaryQ2f4k6AzhYN6xBSG--
```
...which was accessed within the following code:
```
org.owasp.webgoat.plugin.MaliciousFileExecution#handleRequest(), line 456
```
...and ended up in this database query:
```
UPDATE mfe_images SET image_relative_url='uploads/image.jpg' WHERE user_name = 'webgoat';
```

This leaves the Malicious File Execution page open to someone altering the structure of the SQL query and perform a SQL Injection attack. Since the purpose of this exercise is to submit a malicious file, it may be valuable to implement some input sanitizing.

**Comment by nbaars** [comment]
This is related to WebGoat 7.1 we do not actively support this version anymore, closing the issue
