### ISSUE TITLE
Build Failure (mvn clean install | webgoat-container)

### ISSUE THREAD

**Issue by erichappe** [WebGoat/WebGoat#695]
**What happened?**
Following the installation instructions; 

- Java 11
- Maven > 3.2.1
- Clone repo via IntelliJ
- Run the command;
```
mvn clean install
```
The following is the output from that command;
```
[INFO] WebGoat Parent Pom ................................. SUCCESS [  0.210 s]
[INFO] webgoat-container .................................. FAILURE [  1.109 s]
[INFO] webgoat-plugins-parent ............................. SKIPPED
...

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project webgoat-container: Fatal error compiling: invalid target release: 11 -> [Help 1]
```

Java SDK 11.0.4, Java Version 1.8.0_191, Maven Version 3.6.2

**Comment by zubcevic** [comment]
This is not really WebGoat related, but more of a IDE/IntelliJ configuration issue. You should use Java 11 for all including the terminal/maven
