### ISSUE TITLE
Discover Clues in HTML lesson doesn't work

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#70]
It displays this: WeakAuthenticationCookiePleaseSignIn - which isn't right. Probably should just say: Please Sign In.

And when you try to sign in, it doesn't anything like invalid login, or whatever when the credentials don't work.

**Comment by nbaars** [comment]
Fixed, waiting for pull-request.

**Comment by mayhew64** [comment]
Added failed login message.  Waiting for PR
