### ISSUE TITLE
Webgoat standalone M25 always runs on TCP6 even if ipv4 address specified for binding.

### ISSUE THREAD

**Issue by ToraNova** [WebGoat/WebGoat#700]
Greetings. Thanks for the work on webgoat. I just wanna report that the following line :

`java -jar webgoat-server-8.0.0.M25.jar --server.port=63001 --server.address=0.0.0.0`

When I run a netstat -ltn command, I get the following :
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:63000           0.0.0.0:*               LISTEN
tcp6       0      0 :::9001                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::63001                :::*                    LISTEN
```

I tried with server.address=localhost

and got the following :
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:63000           0.0.0.0:*               LISTEN
tcp6       0      0 :::9001                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 127.0.0.1:63001         :::*                    LISTEN
```

Why does it always bind to an ipv6 address? Is there a way to specify binding to an ipv4 address instead ?

My Java version :
```
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
```

OS:
`Linux cj-vmach 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux`

**Comment by zubcevic** [comment]
This is operating system specific. Can't really say much about it. I think in most OS both IPv4 and IPv6 routes will be set up. Unless you disable it.

**Comment by nbaars** [comment]
@ToraNova can you try to pass `-Djava.net.preferIPv4Stack=true` to the `java -jar` command? This might bind it to the IPv4 stack
