### ISSUE TITLE
WebWolf jar standalone version does not log in with WebGoat credentials

### ISSUE THREAD

**Issue by jasj23** [WebGoat/WebGoat#709]
I am running WebGoat and WebWolf using the standalone versions. I am correctly logged in WebGoat, but WebWolf does not recognizes the WebGoat credentials. Please, Could you help me? 

PS. I am using last versions of both. 

Many thanks

**Comment by jasj23** [comment]
All right, works perfect with webwolf version M25

**Comment by zubcevic** [comment]
Did you remove all left overs from M25 or older database? rm -rf ~/.webgoat*

**Comment by jasj23** [comment]
No, I have not, I was just using webgoat M26, and realize that I had to use as well webwolf in some exercises, so I installed webwolf version M26 via jar standalone. But did not log in properly. So I used version M25, and runs fine.
