### ISSUE TITLE
Cannot run docker image for WebWolf

### ISSUE THREAD

**Issue by steffyP** [WebGoat/WebGoat#711]
Hi, everytime I try to start the webwolf I get a "ConnectException". 
I tested versions M26 (latest), M25 and M24. Any help appreciated..

Docker image for WebGoat is running perfectly fine.

Here is the entire log output:

`docker run -p 9090:9090 -t webgoat/webwolf:v8.0.0.M24
 Waiting for database to be available...

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.18.RELEASE)

2019-11-18 19:55:34.829  INFO 7 --- [           main] org.owasp.webwolf.WebWolf                : Starting WebWolf v8.0.0.M24 on 4105326b96e5 with PID 7 (/home/webwolf/webwolf.jar started by webwolf in /)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at

**Comment by zubcevic** [comment]
WebWolf depends on a running WebGoat which contains the database for both. You cannot run WebWolf on its own. 

To make things easier, you could use:

https://github.com/zubcevic/webgoat-training/tree/master/docker-swarm and run both together in a docker swarm/stack or:

Use a different image which contains both WebGoat and WebWolf which start in the right order and where you expose both ports:

docker run -d -p 8080:8080 -p 9090:9090 renezubcevic/webgoat:8.0.M26

or with https:
docker run -d -p 8443:8443 -p 9090:9090 -e WEBGOAT_PORT=8443 -e WEBGOAT_SSLENABLED=true -e GOATURL=https://127.0.0.1:8443 renezubcevic/webgoat:8.0.M26

So this last image is build from an adjusted Dockerfile and temporarily available from my Docker Hub location. We are discussing if we want to make this the new default approach
