### ISSUE TITLE
IDOR View Profile URL malformed

### ISSUE THREAD

**Issue by dwmuller** [WebGoat/WebGoat#713]
In step 3 of the Insecure Direct Object Reference lesson, the View Profile button is presumably supposed to show the profile of user "tom" (who you just logged in as in step 2). The URL is supposed to have the form http://127.0.0.1:8080/WebGoat/IDOR/profile/{userid}, but the userid is not being appended to /WebGoat/IDOR/profile, possibly due to a mistake in WebGoat/lesson_js/idor.js, resulting in a 404. This makes it hard for the user to see the correct form of the URL so that they can manipulate it.

The problem could be worked around by intuition and context, but this seeming error makes the lesson much harder to complete.

WebGoat 8.0 running via Docker Desktop on Windows 10. Firefox browser.

**Comment by zubcevic** [comment]
fixed in #720
