### ISSUE TITLE
Reset lesson doesn't reset SQL Injection lesson's database

### ISSUE THREAD

**Issue by FrancoisCapon** [WebGoat/WebGoat#714]
Version M25

For example : http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjection.lesson/11
SQL Injection (introduction) > **Compromising Integrity with Query chaining**

- **I update the salary of Smith to $100000** : Well done! ...
- (12) is green
- **I reset the lesson**
- (12) is red
- I go to (1) because (12) is inactive
- I go back to (12) : Well done! ...
- F5 no more Well done! ...
- I type Smith and 3SL99A : Well done! ... 

**The Smith's salary is still of $100000**

**Comment by nbaars** [comment]
@FrancoisCapon correct, we implemented cleaning the database in version M26, can you try this version?

**Comment by FrancoisCapon** [comment]
Yes, in M26 the database is reset!
