### ISSUE TITLE
On M26 @project.version@ is not "interpreted"

### ISSUE THREAD

**Issue by FrancoisCapon** [WebGoat/WebGoat#716]
I saw it on the About WebGoat page :

> From the entire WebGoat team, we appreciate your interest and efforts in making applications not just better, but safer and more secure for everyone. We, as well as our sacrificial goat, thank you.
> 
> Version: **@project.version@**
> 
> Contact us:

and I think it's nothing.

But I just see that my data are stored in :
* **` ~/.webgoat-@project.version@`** 
* not  in `~/.webgoat-8.0.0.M26` (M25 is stored in `~/.webgoat-8.0.0.M25`)

So, the next release will use the same folder.

**Comment by nbaars** [comment]
@FrancoisCapon correct, this was a left over from the Spring Boot 1 to 2 migration, we fixed in release M27 which we will release after some more testing.
