### ISSUE TITLE
WebGoat: 'Contact Us' email link in header is not correctly set

### ISSUE THREAD

**Issue by fenik** [WebGoat/WebGoat#719]
The 'Contact Us' email link in the WebGoat header is not correctly set. It seems that the `mailto:` link is missing the necessary info to replace the `${contactEmail}` placeholder. See screenshot below:

![ContactEmail](https://user-images.githubusercontent.com/32820057/69891045-e4065b80-12f9-11ea-8d8a-a9c4058e5806.png)

Issue was found on the M26 docker image.

**Comment by nbaars** [comment]
Fixed, PR awaits
