### ISSUE TITLE
Wouldn't be able to run CSRF lesson 3: Receive Whitelabel Error Page

### ISSUE THREAD

**Issue by purplehat8** [WebGoat/WebGoat#721]
I  tried submitting the answer both via URL and from local page, yet keep receiving the following error every time. Note: Have seen WebWolf icon on the assignment but not sure whether usage is mandatory for this assignment. 
![image](https://user-images.githubusercontent.com/58505287/70501999-08073f80-1b39-11ea-8882-a852ab0849dc.png)

**Comment by nbaars** [comment]
@purplehat8 thanks for the report, fixed the issue waiting on next release

**Comment by aakmonk12** [comment]
this issue still persists, is there a fix available ??

**Comment by nbaars** [comment]
@aakmonk12 it is only on the `develop` branch it is waiting for the next release
