### ISSUE TITLE
SQL Injection (Mitigation) #6 - error

### ISSUE THREAD

**Issue by lucassapao** [WebGoat/WebGoat#723]
Hello,
I am having trouble in making exercise #6 from "SQL Injection (mitigation)" work. I am getting the error:

> Could not compile code:
> error while writing TestClass: /TestClass.class

I have tried my own solution, the example code and the solution provided in the wiki page here on github. I all cases I get the same error message.

I am running the docker compose version using the yml at: https://raw.githubusercontent.com/WebGoat/WebGoat/develop/docker-compose.yml

> version: '2.1'
> 
> services:
>   webgoat:
>     image: webgoat/webgoat-8.0
>     environment:
>       - WEBWOLF_HOST=webwolf
>       - WEBWOLF_PORT=9090
>     ports:
>       - "8080:8080"
>       - "9001:9001"
>     volumes:
>       - .:/home/webgoat/.webgoat
>   webwolf:
>     image: webgoat/webwolf
>     ports:
>       - "9090:9090"
>     command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
> 

I was unable to check the correct version of Webgoat because the about window only shows:
>Version: @project.version@

**Comment by zubcevic** [comment]
I was working on a new version of the docker compose file where i also add a reverse proxy. I noticed this same error also. It did not fail on a docker image that i created using a different dockerfile. So it could be related to the base image. I have a way to easily test this, so I will look into this as well and hope to make a fix

**Comment by zubcevic** [comment]
The current docker image does not specify a working directory and therefore cannot create the file.

We probably need to add WORKDIR in the docker file or use a start script that sets a working dir, like the one I mentioned: https://github.com/zubcevic/webgoat-training/tree/master/docker

**Comment by zubcevic** [comment]
A quick test would be to add the working dir through a yaml option of the compose file:

working_dir: /home/webgoat

**Comment by zubcevic** [comment]
#737 shows in the readme a fix for this:

docker run -d -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf
