### ISSUE TITLE
Vulnerable Components lesson 12 broken due to too new dependency

### ISSUE THREAD

**Issue by thegoodcrumpets** [WebGoat/WebGoat#725]
Lesson doesnt work, like suggested in the wiki guide.
When ran in debug mode, this seems to be because of an exception that gives:
Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: No converter specified for class java.beans.EventHandler

When researching, this is because from version 1.4.7 this vulnerability was fixed in xstream. When manually changing to version 1.4.5 in Maven, a known vulnerable version, this lesson works as intended again. Also in Maven, the 1.4.7 version is commented with:
        
So I guess this was left in after some debugging efforts or something?  Or maybe 1.4.7 was the latest version back when this lesson was created, and it recently may have gotten fixed. It completely nullifies the point of the lesson however.

**Comment by zubcevic** [comment]
I am not very familiar with this lesson, but using the latest released docker images, the lesson still works as described in the wiki guide.

**Comment by thegoodcrumpets** [comment]
Interesting.  Could something have happened between the build date of the docker image and today? As I built it from source it should've been the most fresh iteration possible. A long shot, but could it somehow be browser dependent? Ran this on firefox 71 for windows.

**Comment by nbaars** [comment]
Probably because the development already contains the 1.4.5 (vulnerable version)
