### ISSUE TITLE
Login after building

### ISSUE THREAD

**Issue by JStyle21** [WebGoat/WebGoat#745]
Hi,

Just wanted to ask, after i built the project, the login using guest credintials didn't work, does that mean when building the user list is empty?

**Comment by zubcevic** [comment]
When you use WebGoat for the first time there are no users and you have to register a new user. Or do you mean somerthing else? If you run from a local build, the database will be somewhere in you users home directory under .webgoat...

**Comment by JStyle21** [comment]
That is exactly what i mean, all the guides and docker point to guest (even the tests) so i wondered if i made a mistake or now.
Now since were on the topic where is the actual DB file? the home\webgoat\data directory only has logs and property files.

**Comment by zubcevic** [comment]
I do not understand which guides you are referring to. Just register a user and proceed to the exercises.

**Comment by JStyle21** [comment]
I did, where is the DB file tho?

As for the guides i just googled webgoat login credentials and got these:
https://www.owasp.org/index.php/WebGoat_Getting_Started
https://github.com/OWASP/WebGoat/blob/master/webgoat/doc/attic/readme.txt

**Comment by nbaars** [comment]
The last references at the top version WebGoat **5.2**
The first one is an old version one as this page should be removed

**Comment by JStyle21** [comment]
Not to be picky but does the new version mention that you need to create a user somewhere? the build instructions or the wiki?

**Comment by nbaars** [comment]
@JStyle21 We are under the impression that would be self explained, as it mentions `Register new user` in the UI. Not different then for example registering at a new website like Slack. It this link not clear enough?

**Comment by JStyle21** [comment]
@nbaars Honestly no it's not, if you look at it from a User POV with the example you shared then yes that is clear since it's the first time i'm using the system but from a Dev POV i.e. initial setup i would defiantly mention that, if i just built it from scratch i basically follow steps i have no idea where the setup is complete and the usage begins.
I feel the same way about the rest btw from a user POV it's pretty easy to figure out how to use it but from a Dev POV there's lots of missing useful info that one needs to figure out for example application structure and initial state.

**Comment by nbaars** [comment]
@JStyle21 yes that I can relate to the documentation is from a user perspective. We haven't had much users from the dev perspective. It is all there in the CI pipeline but that is not enough from the point of getting started with development. 

So we will add more from the developer point of view some instructions. We used to have a Vagrant image which sets up all the tools for you.

**Comment by JStyle21** [comment]
@nbaars 
Thank you!
Can i close this issue or do you want to keep it for tracking?

**Comment by zubcevic** [comment]
[Developer Getting Started Guide](https://github.com/WebGoat/WebGoat/wiki/Developer-Getting-Started)
