### ISSUE TITLE
JWT Cracking : exercice 5 problem 

### ISSUE THREAD

**Issue by mobius98** [WebGoat/WebGoat#747]
Hi Everyone,

I have some difficulties to solve the exercice. I think that i did something wrong or is there something wrong in the header of the token ? I tried a lot of thinks to solve it, but I'm stuck on this exercice since a long time. For example, today I started with this token : 

**eyJhbGciOiJIUzI1NiJ9**.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IlRvbSIsIkVtYWlsIjoidG9tQHdlYmdvYXQub3JnIiwiUm9sZSI6WyJNYW5hZ2VyIiwiUHJvamVjdCBBZG1pbmlzdHJhdG9yIl19.ujpcKVOfXsNiXqlk5lP29LZxoGOlPU2YOIWsPFh1qr4

First of all, when I convert the header on Base 64, I found that : 

{"alg": "HS256"}, but "typ":"JWT" is not a missing part ? Because on the page with the solutions (https://github.com/WebGoat/WebGoat/wiki/(Almost)-Fully-Documented-Solution-(en)), they started with this header : **eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9**

Is it normal ? despite this, I tried to solve the exercice : 

I found « victory » as a secret key.

Then, with Burp Suite, I modified the username in the payload. At the end, with  makeSigofjwt.py I obtained a new signature. I pasted it on WebGoat and I have this answer : « Not a valid token, please try again. JWT expired at 2020-01-10T14:58:19Z ».

Here, you will find how I tried to solve the exercice : 

1° : I convert the token for jtr with jwt2jtr.py : 

root@kali:~/Documents# python jwt2jtr.py eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IlRvbSIsIkVtYWlsIjoidG9tQHdlYmdvYXQub3JnIiwiUm9sZSI6WyJNYW5hZ2VyIiwiUHJvamVjdCBBZG1pbmlzdHJhdG9yIl19.ujpcKVOfXsNiXqlk5lP29LZxoGOlPU2YOIWsPFh1qr4

eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IlRvbSIsIkVtYWlsIjoidG9tQHdlYmdvYXQub3JnIiwiUm9sZSI6WyJNYW5hZ2VyIiwiUHJvamVjdCBBZG1pbmlzdHJhdG9yIl19#ba3a5c29539f5ec3625ea964e653f6f4b671a063a53d4d983885ac3c5875aabe

2° : With JTR, I obtained the secret key : victory

3° : I modify the payload with « Tom » to « WebGoat » : 

eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IldlYkdvYXQiLCJFbWFpbCI6InRvbUB3ZWJnb2F0Lm9yZyIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ==

4° With the python file makeSigofJWT.py, I obtained a new signature :

root@kali:~/Documents# python makeSigofJWT.py eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IldlYkdvYXQiLCJFbWFpbCI6InRvbUB3ZWJnb2F0Lm9yZyIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ== victory

[Result]
FD-VD0EmH_oRYZyTm30EZTBbpGfgRtke45gn723TSfY

5° When a validate this new token : 

eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IldlYkdvYXQiLCJFbWFpbCI6InRvbUB3ZWJnb2F0Lm9yZyIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ==.FD-VD0EmH_oRYZyTm30EZTBbpGfgRtke45gn723TSfY

I got this answer : JWT expired at 2020-01-14T15:51:42Z. Current time: 2020-01-14T15:56:34Z, a difference of 292762 milliseconds. Allowed clock skew: 0 milliseconds

It’s the same answer when I used JWT.IO.

When I used this header : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

root@kali:~/Documents# python makeSigofJWT.py eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJXZWJHb2F0IFRva2VuIEJ1aWxkZXIiLCJhdWQiOiJ3ZWJnb2F0Lm9yZyIsImlhdCI6MTU3OTAzNTA0MiwiZXhwIjoxNTc5MDM1MTAyLCJzdWIiOiJ0b21Ad2ViZ29hdC5vcmciLCJ1c2VybmFtZSI6IldlYkdvYXQiLCJFbWFpbCI6InRvbUB3ZWJnb2F0Lm9yZyIsIlJvbGUiOlsiTWFuYWdlciIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ== victory

[Result]
tI69Ka2GXsn4cZ6hi6gkEB33xZWxEMizpe9YWMdMuZg

It’s the same answer.

Thank you in advance for your help

**Comment by zubcevic** [comment]
so i see you got a normal reply which indicates that your token is expired. So first focus on creating a token that is not expired at the time you send it in.

**Comment by zubcevic** [comment]
also be aware that next time you do the exercise, the secret could be different

**Comment by mobius98** [comment]
Thank you very much ! It finally works ! I'm so happy :) I had just to change the "exp" in the payload

**Comment by zubcevic** [comment]
yes in this case the sender already indicates that the token is expired. another exercise also does the check based on the server side to make sure you cannot get solutions from the internet and immediately use it without some effort. Here at least we made the secret change a bit from time to time. Try out the basic crypto lesson and let me know what you think of that.

**Comment by mobius98** [comment]
Yes I gonna try ! Thank you very much again
