### ISSUE TITLE
Can't tell when WebGoat has actually started when using: webgoat_developer_bootstrap.sh

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#75]
Towards the end of the launch it eventually displays the following message. But its still 'starting'. Can you add a line that indicates: WebGoat 'started' when its actually up and running?

-----------------------------------------------------------------------------------
____________________ Starting WebGoat using the embedded Tomcat ___________________
###################################################################################
##################################### HAPPY HACKING! ##############################
-----------------------------------------------------------------------------------

**Comment by nbaars** [comment]
See #215 in which we fixed this issue. The standalone Tomcat replaces the embedded one, this one reports the url after the fact.
