### ISSUE TITLE
Lessons Intermittently showing up in WebGoat

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#76]
I've written 2 new custom lessons (really just test cases, not lessons), and put them in a brand new category.

And sometimes when I start WebGoat, 1 shows up, and other times both show up. And then I added a 3rd lesson, and I have the config file set up like this:

category.MYNEW.ranking=7
lesson.MYNEW_Lesson1.ranking=10
lesson.MYNEW_Lesson2.ranking=15
lesson.MYNEW_File_Lesson.ranking=20

and this time 2 out of the 3 showed up. (The 1st and 3rd one).
And when I restarted and tried again, I only got 1. (The 2nd one) :-)

**Comment by davewichers** [comment]
After looking at the lessons in WebGoat, I'm getting the feeling that the webgoat-class.properties file I referred to earlier has nothing to do with the ordering of the menu entries in WebGoat anymore. So maybe I'm just not configuring it right, and if so, can you tell me what I'm doing wrong?

**Comment by mayhew64** [comment]
Could be related to 49.  Doesn't seem like it though

**Comment by nbaars** [comment]
Created three new lessons within a new category, see https://github.com/nbaars/WebGoat-Lessons/tree/new_lessons 

All the lessons appear in the new category tested on Linux and Windows platform.

@davewichers can you take a look at the branch to see if the implementation of the lessons matches yours? 

Thanks, 
--Nanne

**Comment by davewichers** [comment]
My lessons look the same as yours. I pulled in all the latest changes and
the issue seems to have gone away .

Not sure what¹s going on, but I¹m 3 for 3 today on all the lessons showing
up as they are supposed to.

I¹ll let you know if I see any failures in the future.

-Dave

From:  Nanne <notifications@github.com>
Reply-To:  WebGoat/WebGoat
<reply+004c5b05ec06547052865a0401ccf97ad23d7935843ac68992cf0000000112136cec9
2a169ce065eb7a0@reply.github.com>
Date:  Friday, September 18, 2015 at 2:10 AM
To:  WebGoat/WebGoat <WebGoat@noreply.github.com>
Cc:  Dave Wichers <dwichers@gmail.com>
Subject:  Re: [WebGoat] Lessons Intermittently showing up in WebGoat (#76)


Created three new lessons within a new category, see
https://github.com/nbaars/WebGoat-Lessons/tree/new_lessons

All the lessons appear in the new category tested on Linux and Windows
platform.

@davewichers <https://github.com/davewichers>  can you take a look at the
branch to see if the implementation of the lessons matches yours?

Thanks, 
--Nanne


Reply to this email directly or view it on GitHub
<https://github.com/WebGoat/WebGoat/issues/76#issuecomment-141354584> .

**Comment by mayhew64** [comment]
Confirmed by multiple folks, all the lessons are showing up.
