### ISSUE TITLE
Execution of standalone jar fails (Flyway migration step)

### ISSUE THREAD

**Issue by Grid-LTS** [WebGoat/WebGoat#760]
Executed:
`docker-compose -f docker-compose-postgres.yml up`

Docker image version: webgoat/webgoat-8.0 (v8.0.0.M26)
OS: MacOS 10.15.3
Docker: 19.03.5 

Console output of webgoat_1:
```
ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyWayContainer' defined in class path resource [org/owasp/webgoat/DatabaseInitialization.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
webgoat_1     | Migration V1__init.sql failed
webgoat_1     | -----------------------------
webgoat_1     | SQL State  : 42P06
webgoat_1     | Error Code : 0
webgoat_1     | Message    : ERROR: schema "container" already exists
webgoat_1     | Location   : db/container/V1__init.sql (/home/webgoat/file:/home/webgoat/webgoat.jar!/BOOT-INF/lib/webgoat-container-v8.0.0-SNAPSHOT.jar!/db/container/V1__init.sql)
webgoat_1     | Line       : 1
webgoat_1     | Statement  : CREATE SCHEMA CONTAINER
```

**Comment by zubcevic** [comment]
The only compose yaml that definitely works now is:
docker stack init
docker stack deploy --compose-file goat-with-reverseproxy.yaml webgoatdemo

where docker-compose is also no longer used.

If you want to use a separate progresdb container this yaml might need some updates. I would at least also put in some depends_on so the database is started first, then webgoat and finally webwolf. If you get it to work please create a pull requests.

**Comment by Grid-LTS** [comment]
I also tested without Docker. The same errors appears when using a native Postgres daemon and executing the jar. So this is not Docker related at all. For the moment I am reverting to v8.0.0.M25.
