### ISSUE TITLE
Can't run webgoat and ZAP 

### ISSUE THREAD

**Issue by wmrrssy92** [WebGoat/WebGoat#770]
hello,

I am extremely new to this and frustrated

I downloaded java development kit to run webgoat. i started running it and it worked fine. 
then i needed to download ZAP to use it. then i needed java runtime environment for zap. then opened zap just fine. attempted to reopen webgoat and it wouldnt open because it wouldnt use the jdk. i have spent 2 hours reading and googling and youtubing and im stuck. 

i have uninstalled both java jdk and jre. i have weboat and ZAP still and just wanted to start fresh. 

how can I use jre for ZAP and jdk for webgoat at the same time. or is there another way to go about this

using Windows 10. wanted to use docker but i dont have pro or enterprise

**Comment by zubcevic** [comment]
Sorry to hear that you are frustrated using the Java versions of OWASP WebGoat and ZAP.
But you are not the only one ;-). 
So on Windows 10 on x86/64 bit, I would say that the following steps should be enough:

- Install Java 11 HotSpot SDK For Windows as ZIP file. E.g. from https://adoptopenjdk.net/
- Configure Windows and set JAVA_HOME to what you just installed
- Configure PATH to start with %JAVA_HOME%\bin

Then both WebGoat and ZAP should just be fine.

**Comment by wmrrssy92** [comment]
ZAP is still saying i need jre. I followed your instructions. tbh i feel like im too ignorant in all of this not knowing the fundamentals :/

**Comment by zubcevic** [comment]
How do you start Zap? Using the .bat file? If JAVA_HOME and PATH are configured in the windows environment variables this should be enough. Or are you clicking on the Jar?

**Comment by zubcevic** [comment]
If you have virtualbox and vagrant, you could use this ready-to-go virtual machine.
https://github.com/zubcevic/vagrant/tree/master/owasptools-virtualbox
It requires understanding of virtualbox and vagrant. If you do not have virtualbox but have hyperv you can use this one: https://github.com/zubcevic/vagrant/tree/master/owasptools-hyperv
But then you also need some hyperv understanding.
But perhaps the install options in: https://github.com/zubcevic/vagrant/tree/master/webgoat-training/virtualbox/provision.sh does give you some tips and hints on how to set things up for your own

**Comment by zubcevic** [comment]
If there are no real issues with WebGoat, please close the issue or clarify the issue further

**Comment by zubcevic** [comment]
As I no longer see a response, I guess that the proposed solution is good enough. Feel free to reopen it with more clear information
