### ISSUE TITLE
strange copy in constructor 

### ISSUE THREAD

**Issue by zubcevic** [WebGoat/WebGoat#788]
In ProfileUploadRetrieval there is a @PostConstruct with a copy command.

for (int i = 1; i <= 10; i++) {
            try {
                copy(getFile(getClass().getResource("/images/cats/" + i + ".jpg")), new File(catPicturesDirectory, i + ".jpg"));
            } catch (Exception e) {
                log.error("Unable to copy pictures" + e.getMessage());
            }
        }

This seems to always fail, but it does not impact the lesson at all. So maybe remove this code? Now you will see error message during startup of WebGoat.

**Comment by nbaars** [comment]
Fix the copying (with the Spring Boot embedded jar it failed due to not using the classpath resource). The copying is necessary as the paths are returned. The UI reads them from using Thymeleaf.
