### ISSUE TITLE
ACE code editor removed, but still used

### ISSUE THREAD

**Issue by schmonz** [WebGoat/WebGoat#791]
In [6b7678f](https://github.com/WebGoat/WebGoat/commit/6b7678f), the bundled JavaScript source code editor component [ACE](https://ace.c9.io) was removed.

It is still referenced from <http://localhost:8080/WebGoat/start.mvc#lesson/SqlInjectionMitigations.lesson/5>, under the text

> (if you cannot type there it might help to adjust the size of your browser window once, then it should work):

Resizing the window doesn't make the textarea editable, but reverting the removal of ACE does.

If the intent was to fully remove ACE, please also remove all references to it. Otherwise, please re-add it.

**Comment by zubcevic** [comment]
fixed
