### ISSUE TITLE
CommandInjectionExecute.java No Command Injection

### ISSUE THREAD

**Issue by thewb** [WebGoat/WebGoat#792]
The source that's supposed to have command injection is a proxy.

**Comment by zubcevic** [comment]
What code/class/exercise are you referring to and is it still in latest develop?

**Comment by thewb** [comment]
I’m referring to that specific file.

**Comment by zubcevic** [comment]
I think the class and the entire commandinjectiin section has been removed from the develop branch and the 8.1.0 release

**Comment by thewb** [comment]
No worries, I used this for a fun and games code review and just wanted to let y’all know. Cheers!
