### ISSUE TITLE
Facing issue in deserialization vulnerability.

### ISSUE THREAD

**Issue by faizzaidi** [WebGoat/WebGoat#803]
Dear team,

I am try to solve deserialization vulnerability in webgoat version 8.0.0 M21. I am trying payload to solve the issue with base64 encoding. Everytime I am facing "sorry the solution is not correct, please try again." issue with multiple payloads. Even I had tried the webgoat solution with is available on the webgoat solution but still facing the same issue.Also tried on the latest build but facing same issue.

Reference URL:
https://github.com/WebGoat/WebGoat/wiki/(Almost)-Fully-Documented-Solution-(en)#insecure-deserialization

Thanks and regards,
Faiz

**Comment by zubcevic** [comment]
This lesson has been broken for quite a while, it is fixed in the current development branch, the latest docker images and the M26 standalone

**Comment by zubcevic** [comment]
I’ll close the issue as I believe the suggestions are enough
