### ISSUE TITLE
WEBGOAT 

### ISSUE THREAD

**Issue by Divyashivakumar10** [WebGoat/WebGoat#804]
hey this is regarding webgoat logs , i saw the last issue where they said , webgoat doesnt log, 
and this command was given "/bin/nohup java -jar webgoat.jar>output.log & tail -300f output.log" to acess the logs which is not webgoat specific. 
I wanted to know whether i can any get  attack details from webgoat .
i am using Zed attack proxy to perform attack on webgoat .
How do i collect logs from webgoat side . 
like on which link what payload was sent , what command was run to perform that specific attack.
The defender ( Webgoat)  should also collect attack information right? 
I am using this command to collect sql payload , but it is not sufficicent to perfrom data analytics - 
tcpdump -i lo -l -s 0 -w - dst port 9001 | stdbuf -o0 strings| stdbuf -o0 grep "SELECT\|INSERT\|UPDATE|\FROM\|WHERE\|ORDER\|AND\|LIMIT\|FROM\|SET\|COMMIT\|ROLLBACK"

**Comment by zubcevic** [comment]
What you want to do makes more sense for an application like JuiceShop. WebGoat acts with lessons and assignments where vulnerabilities are controlled vulnerabilities inside the scope of the assignment.It also depends on the creator of the lesson how it is logged or not logged
