### ISSUE TITLE
Webgoat doesnt connect on ZAP browser when launched through VM 

### ISSUE THREAD

**Issue by Divyashivakumar10** [WebGoat/WebGoat#805]
webgoat is in port 8080 listens on port 9001 .
ZAP is on port 8090. ( both application are on 2 different VM's)
when I manually launch the firefox through ZAP , and give the webgoat URL 
i.e http://149.165.157.203:8080/WebGoat/login
it shows the following error message 
![2](https://user-images.githubusercontent.com/64250511/80646692-d2ed8200-8a32-11ea-9163-24c01c794380.PNG)

I increased the read out time connection from 20s to 45s , still no response .
whats the issue?

**Comment by zubcevic** [comment]
is it listening on that IP?

**Comment by Divyashivakumar10** [comment]
Heyy thank you so much issue got resolved.
The Zap was listening to local host , and not my IP . Previsouly when i tried to add my IP inside the local proxy of ZAP , it rejected  . 
Now I tried it again . Its working . thanks a ton

**Comment by Divyashivakumar10** [comment]
One more issue, Webgoat works smooth and fast  when I host it through normal firefox browser.
But when i launch it through ZAP browser, its very slow , like when i click on something it takes some time before it does anything. Whats the issue?

**Comment by zubcevic** [comment]
I think the ZAP heads on display HUD with the websockets makes it slow, but never really investigated. I keep the HUD disabled
