### ISSUE TITLE
Failed to load picturess in wiki 

### ISSUE THREAD

**Issue by Soowin** [WebGoat/WebGoat#816]
In this page:
https://github.com/WebGoat/WebGoat/wiki/(Almost)-Fully-Documented-Solution-(en)

ALL pictures are failed to load, and return code 404.

**Comment by zubcevic** [comment]
It seems that the person who added the pictures was referring to its own repository that is removed  or moved now. The wiki part is a very open part where everybody can add content. There is not much we can do about it.
