### ISSUE TITLE
ZAP log files

### ISSUE THREAD

**Issue by Divyashivakumar10** [WebGoat/WebGoat#818]
Hey from the previous issue, you told me webgoat doesnt create log files to perform data analytics.
I am using ZAP tool to perfrom attacks on webgoat. , 
ZAP UI log files doesnt generate enough data to perfrom the data  analytics.
 how do I acess the full request and response of ZAP database  from its API ( I went through the documentation of api cant seem to find the method to access database)

**Comment by nbaars** [comment]
@Divyashivakumar10 I'm not sure what you are looking for I think these are more related ZAP question?

- https://www.zaproxy.org/docs/desktop/ui/tlmenu/report/ you can export the responses etc
- https://www.zaproxy.org/faq/how-do-you-configure-zap-logging/ increase log levels

Feel free to reopen this issues if I misunderstood your question
