### ISSUE TITLE
SQL injection (intro)

### ISSUE THREAD

**Issue by Bidon46** [WebGoat/WebGoat#831]
In last lesson of SQL injection(intro), if you use payload with truncate, there is a problem with granting task credit. The "employees" table gets empty, but task is still not marked as completed.

![blad](https://user-images.githubusercontent.com/58447513/84282936-5f966000-ab08-11ea-9487-b0ec888868d2.PNG)

**Comment by zubcevic** [comment]
See the red line. You need to do more. The lesson will get green in the end.
