### ISSUE TITLE
Update OWASP Link in Cryptography Chaper 4 Hashing

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [WebGoat/WebGoat#833]
OWASP Password Storage Cheat Sheet  is moved to: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

Since OWASP has moved a lot of links recently I think it'll be helpful to update all the OWASP links.

**Comment by multiwebinc** [comment]
This whole page is extremely poorly written and should be completely redone in my opinion.

First of all, hashing is a one-way function that maps data of an arbitrary size to a bit string of a fixed size. It is not a type of cryptography, it is a function.

> Plain hashing

What's "plain hashing"? https://en.wikipedia.org/wiki/List_of_hash_functions

> If the original data is changed by even one byte, the resulting hash is also different.

This is not true for all hashing functions

> So in a way it looks like a secure technique. However, it is NOT and even NEVER a good solution when using it for passwords

Besides the poor grammar here, this section leads me to believe that we shouldn't be hashing our passwords, which is, of course, untrue. As well, we shouldn't be (manually) salting our passwords, but instead using algorithms (or libraries that use these algorithms) that do this for us automatically.

> Some hashing algorithms should no longer be used: MD5, SHA-1

Both of these functions are widely used. 

I recommend adding information about:

- Hash tables
- Hashes vs checksums
- Cryptographic hash functions vs non-cryptographic
- What makes a good and bad password hashing algorithm and which one(s) we should be using.

**Comment by Ashutosh-Kukreti** [comment]
@multiwebinc  Thank you very much this information is very useful. It'll help me a lot in my research and learning.

**Comment by zubcevic** [comment]
Yes always nice when links get moved around. I'll look into making a validation for that. @multiwebinc please create a pull request with suggestions to improve the page. Goals is to keep it simple but correct.
