### ISSUE TITLE
SQL mitigation (filtering) can only be passed by updating table

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#838]
Edit: If you read this issue and still beg me for a solution to the referenced exercise, then I'm afraid you probably shouldn't be left outside unsupervised. I feel sorry for you.

It looks like the controller for the filtering lesson (currently number 9) assumes that the underlying table contains "dave" and "passW0rD'. The one used doesn't, and will only let you pass if you first insert those into the table.

Or to put it differently, the following input should pass you:

    '/**/or/**/'1'='1

But it will print the entire table (which presumably is the objective (even though the objective isn't actually stated on the page!), after saying that the solution isn't correct:

![image](https://user-images.githubusercontent.com/16987409/85083849-0631cf00-b1a1-11ea-926e-e125797f8607.png)

After digging through the lesson code (which I would normally consider cheating, but my life is too short for broken courses), it dawned on me that the creator of this question assumes that the underlying table is the same as in a previous exercise, where we found that `dave`'s password is `passW0rD`, so I ran this:

    '/**/;update/**/user_data/**/set/**/cookie='davepassW0rD';--

After this, the previous solution will work:

![image](https://user-images.githubusercontent.com/16987409/85083975-63c61b80-b1a1-11ea-8422-7f1419ab1dec.png)

I thought this app was supposed to teach you Web security flaws, not how not to fail at abstraction between code modules...

**Comment by jamesoso007** [comment]
hello can i get solution of level 10(Input validation alone is not enough) ?

**Comment by jamesoso007** [comment]
please Give me solution of level 10 (Input validation alone is not enough). i tried everything but it didn't works.

**Comment by jamessoso2** [comment]
Please give solution of level 10 (Input validation alone is not enough)?

**Comment by jamescorlo** [comment]
Please give solution of level 10 (Input validation alone is not enough)? i think you don't know that is why you ignoring my question!. If you are also noob then tell clearly you don't know.

**Comment by jamescorlo** [comment]
@dovecode 
Please give solution of level 10 (Input validation alone is not enough)?

**Comment by milanmadani** [comment]
Hello Dear dovecode,

If you don't know this answer tell clearly, ignoring is never give you anything in your life.

Please give solution of level 10 (Input validation alone is not enough)? i think you don't know that is why you ignoring my question!. If you are also noob then tell clearly you don't know.

**Comment by milanmadani** [comment]
**please give solution of level 10**

**Comment by lionadopolp** [comment]
Dear Asshole Give me please give solution of level 10

**Comment by lionadopolp** [comment]
please give solution of level 10

**Comment by nbaars** [comment]
Solved add a link to the correct assignment to read about the lesson goal
