### ISSUE TITLE
SQL Injection (mitigation) Order by clause confusing

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#839]
I think this lesson is trying to say not to inject parameters into the `ORDER BY` clause. However, it doesn't:

![image](https://user-images.githubusercontent.com/16987409/85084254-48a7db80-b1a2-11ea-9607-f8a7d34a1efb.png)

I mean, that's perfectly fine. `lastname` isn't a parameter, it's a literal.

I *think* what the author meant was that something like this is bad:

    query = "SELECT * FROM users ORDER BY "+sortColumName+";";

if `sortColumnName` is user input.

**Comment by nbaars** [comment]
Thanks for the input, fixed the code was wrong
