### ISSUE TITLE
./webgoat_developer_bootstrap.sh script continues to try to launch WebGoat after compilation errors

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#84]
If there is an error like the following, it keeps chugging along and tries to run WebGoat anyway. Can you add some kind of error handling to detect Maven errors at each stage and stop if there was an error?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project FOO: Compilation failure

Whatever the error was

[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :FOO

---

____________________ Starting WebGoat using the embedded Tomcat ___________________
######

**Comment by dougmorato** [comment]
Sure thing... I will work on that over the weekend to add some sanity checks and also to address your other request, to inform the user that Tomcat/WebGoat has started.

I also want to create the "project"  for eclipse and intellij, so a developer only has to import the project on their IDE.

Thanks for reporting the issues.

**Comment by dougmorato** [comment]
related to #75

**Comment by davewichers** [comment]
Related to an Eclipse project, I'm not sure I'd bother. You can easily import a Maven project into Eclipse so I'm not sure of the point exactly. I don't use IntelliJ but imagine it has a similar feature.  I think just documenting how to import it into those IDEs would be good enough.

**Comment by nbaars** [comment]
Done, with release 8 the script is no longer necessary only 3 commands to start when you checkout to start developing with WebGoat
