### ISSUE TITLE
XSS intro exercise answer key is not really working

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#840]
I mean...

![image](https://user-images.githubusercontent.com/16987409/85144765-9d3a6d80-b219-11ea-960a-548180887b61.png)

**Comment by zubcevic** [comment]
You mean that it would be nice if y is and Y and maybe Yeah are also considered yes? Yes?

**Comment by dovecode** [comment]
No, I mean it would be nice if there would be no chance of having to guess what you want me to answer. Unless of course you want to build a dictionary of all possible positive acknowledgements for all the languages you want to support. By my guess, I suppose...

Most Web developers recognize this and implement some sort of unambiguous input, say a radio button or a checkbox.

But this exercise is so out of character for the rest of WebGoat. Usually you have to find a secret number or produce a particular situation server-side. This time, you have to answer "yes" or ... not "yes"?

Also, the "hint" in the answer is so weird. What would "using a tab from a different site" have to do with testing if two tabs share session, which is really what this is testing....
