### ISSUE TITLE
Bypass front-end restrictions: Field restrictions - confusing text in form

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#843]
I'm not sure if this is meant to be there, but it looks like a remnant of an attempt to include a disabled input field:

![image](https://user-images.githubusercontent.com/16987409/85149566-6e26fa80-b21f-11ea-8b7b-741c425cf0fd.png)

There is no Disabled input field in the form...

**Comment by nbaars** [comment]
Fixed
