### ISSUE TITLE
Suggestion: Update navigation

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#844]
The navigation in Webgoat is quite ... odd

The main issue is with the "tabs" in a given ... "lesson"? They are tiny and the color-coding is unintuitive and downright hostile to people with color vision impairments.

For the tabs, I would suggest an actual tabbed interface. This would allow for naming the ... "exercises"? "tasks"? and also make it clear when an exercise is just that, as opposed to the lesson-type exercises? tasks? lessons? (I'm sorry, but I don't really get the nomenclature here).

The whole flashing-the-current-task is just disturbing. There's a reason they removed the `<blink>` tag.

I would also suggest getting rid of the collapsing left-nav. There aren't really that many options there. They'd all fit in most modern monitors as an expanded list. Also, most groups have just 1-2 lessons anyway.

**Comment by nbaars** [comment]
Solved the blinking part and the hide menu button is gone now, see https://github.com/WebGoat/WebGoat/pull/884

**Comment by nbaars** [comment]
With: https://github.com/WebGoat/WebGoat/pull/890 it also solves:

- Underline link is now gone (a href was underlining the icons)
- Outline the buttons
- Improve size of buttons
- Removed shading when page is selected and replaced it with a complete border around the icon
