### ISSUE TITLE
Can't complete login CSRF attack

### ISSUE THREAD

**Issue by dovecode** [WebGoat/WebGoat#846]
There are several issues with this. One being that you have to log out to create the csrf user, which automatically logs you out of the original tab.

But it looks like the logic for marking the task complete doesn't work. I manage to get a "Solved" message, but it never marks as complete under my original user.

**Comment by zubcevic** [comment]
<img width="830" alt="Schermafbeelding 2020-06-20 om 09 53 40" src="https://user-images.githubusercontent.com/7931455/85196764-a93b3380-b2dc-11ea-9728-37b4a304efd4.png">

The v8.1.0 should show the following result in the end. There could be slight differences in the moment that this is shown based on different kinds of browsers.

**Comment by zubcevic** [comment]
In the end the green checkmark appears when all exercises are completed

**Comment by dovecode** [comment]
OK, so putting aside the issue with being logged out during user creation, I've created by csrf-dovecode account. I now log into to WebGoat in a separate tab as that user and click the button in the original tab:

![image](https://user-images.githubusercontent.com/16987409/85207019-f24ab200-b2f3-11ea-9f34-0ae6944d58b3.png)

I then follow the instructions, log out, then back in again and navigate to the exercise page:

![image](https://user-images.githubusercontent.com/16987409/85207065-405fb580-b2f4-11ea-9788-aa2c2e09cccb.png)

As you can see, the "8" doesn't get a green background. Neither do I get a checkmark on the lesson, even though I've now completed all the exercises in the lesson.

**Comment by nbaars** [comment]
Added test, tested in browser as well assignment is marked as solved
