### ISSUE TITLE
Ajax Security: LAB: Client Side Filtering

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#86]
Some wonky rendering is occurring when loading this lesson.  The web goat financials portion of the screen does not get rendered until the "select user" is clicked.  Tested on Safari and Firefox

Initial render:
![screen shot 2015-09-18 at 5 45 16 pm](https://cloud.githubusercontent.com/assets/3689202/9971843/0d8a404c-5e2d-11e5-96d5-96c50d89fa96.png)

After clicking on the select user:
![screen shot 2015-09-18 at 5 46 03 pm](https://cloud.githubusercontent.com/assets/3689202/9971863/34a08ba0-5e2d-11e5-8a4d-ec1afbd4406b.png)

**Comment by nbaars** [comment]
Looking into this one: the style is not included from the beginning in the Java code. After including the style the images cannot be found. PluginLoader needs to rewrite the paths.

**Comment by nbaars** [comment]
The lesson consists of 2 stages, the first one use ECS to build the content the second one uses a jsp with scriplet code inside. 

The first stage did not include a reference to the style sheet when it first got loaded, the javascript kicked in when selecting something from the list box. Not quite sure why the css did work after that but adding the reference in the Java code fixed the issue.

**Comment by nbaars** [comment]
Pull request is available
