### ISSUE TITLE
COMPOSE not working in webwolf standalone

### ISSUE THREAD

**Issue by mwithi** [WebGoat/WebGoat#871]
The Proxy Lesson n.7 ask to intercept a Mail request from WebWolf standalone, but he COMPOSE button in the is doing nothing, nor showing any error in js console or terminal, it just add a # to the URL.

Am I doing something wrong or maybe I misunderstood what the lesson is asking?

```
Using:
webgoat-server-8.1.0.jar standalone
webwolf-8.1.0.jar standalone
ZAP_2_9_0_windows.exe
Firefox within ZAP
```
```
> java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment 18.9 (build 11.0.4+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11, mixed mode)
```

**Comment by zubcevic** [comment]
Please read the assignment again in WebGoat. WebWolf does not support composing mails. However actions in WebGoat cause emails to arrive in WebWolf. So in that part of the lesson you should do something in WebGoat. Please read the Wiki or the hints in the lesson
