### ISSUE TITLE
WebWolf Standalone Redirects to localhost:9090

### ISSUE THREAD

**Issue by mire3212** [WebGoat/WebGoat#874]
I am trying to host WebGoat and WebWolf in an AWS EC2 image (with IP white-list) behind an Nginx proxy. WebGoat works without issue with Nginx proxying the connections to `http://127.0.0.1:8080/WebGoat`, but WebWolf redirects the request back to `http://127.0.0.1:9090/login` which doesn't work since my system doesn't have WebGoat running (it's in the AWS EC2 Instance).

Adding `server.address` won't do since I need to keep WebWolf on localhost to leverage Nginx to proxy all connections.

**Comment by zubcevic** [comment]
In the docker image there is already an nginx server for both webwolf and WebGoat on port 80

https://github.com/WebGoat/WebGoat/tree/develop/docker
docker run -d -p 80:80 -e TZ=Europe/Amsterdam webgoat/goatandwolf:latest

Be aware that it can only run as single instance.
Look at some other cloud examples: https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-on-google-cloud/ and other pages

**Comment by mire3212** [comment]
The issue with Docker is that it is ephemeral. Once the instance is shut down or rebooted, any progress was lost. I haven't seen any instructions on how to keep the progress within the image permanent. The EC2 instance is powered off at night and on weekends to avoid extra cost, but this would result in the data from the Docker instance being destroyed every time.

**Comment by zubcevic** [comment]
Then look at the example nginx configuration which does the reverse proxy thing for both WebGoat and WebWolf. https://github.com/WebGoat/WebGoat/blob/develop/docker/nginx.conf 
You might need some small adjustments, but you will get it to work fine.
