### ISSUE TITLE
Update the OWASP website with the new all-in-one Docker container

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#891]
Think we should reverse the order, first the Docker image explanation and then using Java. Also we should include which Java version and how to download it etc. Look at https://github.com/nbaars/webgoat_workshop/blob/master/README.md

This also holds for the README.md inside the project

**Comment by zubcevic** [comment]
Yes in most cases that would be the simplest deployment

**Comment by zubcevic** [comment]
Also how do we handle the new delete policy from Docker Hub. It might delete the image used in the docker container exercise if it is not used frequently

**Comment by krol3** [comment]
Hi! @nbaars and @zubcevic, maybe this PR is related to improve how download the jars and build the image docker from the source code. https://github.com/WebGoat/WebGoat/pull/939

**Comment by nbaars** [comment]
Website update also done, see https://github.com/OWASP/www-project-webgoat/pull/6 
After the release this branch should be merged
