### ISSUE TITLE
Crypto Basic Lesson 8

### ISSUE THREAD

**Issue by jmonp** [WebGoat/WebGoat#902]
Hello!!
I'm trying to do this lesson, but I can't quite understand how to do it.
According to the instructions, the file that contains the key is located in the / root directory. So first I have to find out the root password. I am going on the right way?

Thank you

**Comment by zubcevic** [comment]
That is correct. You have to find ways to get to that location. Finding the password is unlikely. I just discovered another way. So there are multiple options from very simple to a bit harder

**Comment by jmonp** [comment]
Ok¡! Thanks. I'm new in this world. I will keep trying!!
