### ISSUE TITLE
Installation Guide for Raspberry Pi

### ISSUE THREAD

**Issue by jaymz212** [WebGoat/WebGoat#911]
***Never mind - I finally got it to to work.  I am going to try and either remove or close this issue.***

Hello all - I am newbie, learning as I go.  Does anyone know of a good installation guide for installing WebGoat onto a Raspberry Pi?  I have founds disparate instructions but they are either older or simply don't work.

Thanks!

**Comment by zubcevic** [comment]
You could do it with ansible, see my blog: https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-using-ansible/
