### ISSUE TITLE
Bug in SQL Injection Intro Lesson 11

### ISSUE THREAD

**Issue by ashishpatel-git** [WebGoat/WebGoat#914]
Hi there, seem that for some reason I do not get a response when placing "Smith" as the name and ' OR '1' = '1 as the TAN. Is this expected behavior? I checked the source code and it seems there may be a different query being used by the code than what it shown on the lesson page.

**Comment by zubcevic** [comment]
It is not a bug, this lesson can be solved

**Comment by ashishpatel-git** [comment]
https://github.com/WebGoat/WebGoat/blob/60c7fdd0dbcbc09aaa22f5c772666c716344f8cf/webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/sql_injection/introduction/SqlInjectionLesson8.java#L59

On this particular line it seems like there is one additional quote in the injection string compared to what it shown on that page to the user. Would that have an impact @zubcevic?

**Comment by ashishpatel-git** [comment]
Something was wrong with my docker image, after running it again this worked fine. Apologies for the confusion!

**Comment by zubcevic** [comment]
no problem, feel free to ask questions or add lesson ideas or improvements
