### ISSUE TITLE
Docker run failed to start:  standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by HKMV** [WebGoat/WebGoat#917]
Docker run failed to start, The log information is as follows:
`standard_init_linux.go:211: exec user process caused "exec format error"`
 How do you solve this problem？

**Comment by zubcevic** [comment]
can you provide some more detail? like which os, which docker, what startup arguments were used?

**Comment by HKMV** [comment]
> can you provide some more detail? like which os, which docker, what startup arguments were used?

system: armbian 5.77
docker: Docker version 19.03.12, build 48a6621
startup arguments: docker run -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam webgoat/goatandwolf

The reason why the arm architecture is not compatible is that some of my data should not be queried.
May I ask if there will be any support in the future?

**Comment by zubcevic** [comment]
I think this environment is not really commonly used for WebGoat. So don’t expect any support unless you are providing the support through some pull request. https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-using-ansible/
In this blog you can see what it takes to run webgoat on an arm based raspberry pi

**Comment by HKMV** [comment]
> I think this environment is not really commonly used for WebGoat. So don’t expect any support unless you are providing the support through some pull request. https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-using-ansible/
> In this blog you can see what it takes to run webgoat on an arm based raspberry pi

thinks!

**Comment by avivmu** [comment]
@HKMV Did you manage to solve the problem? If so please close this issue
