### ISSUE TITLE
Upgrade to Java 15

### ISSUE THREAD

**Issue by avivmu** [WebGoat/WebGoat#923]
What is your opinion? The feature I'm interested in is [records](https://openjdk.java.net/jeps/395) which is in _second preview_ in Java 15, and will be final in Java 16

**Comment by zubcevic** [comment]
The java language level is still 11 in the releases of the jars and the docker images, but the builds are tested at level 15 as well, just to see that nothing breaks. I think we need to keep the dev level still on Java 11. What kind of lesson would you not be able to develop with Java 11. large enterprises are still using lots of Java 8 and Java 11 is now at least more familiar to developer. @nbaars what do you think?

**Comment by avivmu** [comment]
I don't see harm in upgrading. I don't strictly _need_ it for development, but if it's released, we don't want to stay behind
