### ISSUE TITLE
Migrating from travis to github actions

### ISSUE THREAD

**Issue by avivmu** [WebGoat/WebGoat#924]
Travis is soon going to limit OSS projects to [1000 min / month](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only) (but you can ask for more if you qualify).
See [here](https://github.com/TeamNewPipe/NewPipe/pull/5132) an example of a project that did it recently

**Comment by zubcevic** [comment]
Good to know, what is most irritating is the wait time nowadays. The macos builds are picked up quite fast, bur the linux ones take a lot of wait time, I expect that is not counted in the 1000mins

**Comment by zubcevic** [comment]
I did a small experiment on my own not so up to date fork: https://github.com/zubcevic/WebGoat/blob/develop/.github/workflows/main.yml
https://github.com/zubcevic/WebGoat/runs/1708705263?check_suite_focus=true
looks promising

**Comment by zubcevic** [comment]
I added the file to a separate branch in this repo as well to see the effects:
https://github.com/WebGoat/WebGoat/actions/runs/629396653

**Comment by nbaars** [comment]
Nice, seems like we only have to set the passwords for uploading the artifacts

**Comment by zubcevic** [comment]
Probably we need some changes to the organizational checks as well, is @dougmorato the only one that can do this?

**Comment by zubcevic** [comment]
Nice that it also does a windows build

**Comment by nbaars** [comment]
> Probably we need some changes to the organizational checks as well, is @dougmorato the only one that can do this?

No, we have all those passwords just a matter of recreating them in Github
