### ISSUE TITLE
Button to force plugin reloading

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#93]
As a developer, I would like a button to force the reloading of all plugins.

**Comment by nbaars** [comment]
Working on this, created a new endpoint for reloading plugins. We need to decide how we integrate this within the GUI:

- Button?
- Do we want to reload all the lessons or reload a specific lesson?

**Comment by nbaars** [comment]
As discussed on the slack channel: we will reload all plugins, and make it available with reload=true url parameter or just a WebGoat/…/reload.  We can wire it up later.

**Comment by nbaars** [comment]
You can now reload plugins with a call to a separate endpoint this endpoint. We can integrate this in the UI with a button in a later version

**Comment by span** [comment]
I am not aware of any "developer controls" where such a button would be suitable in webgoat at the moment, is there one? If not, perhaps it could be useful to have some kind of "Developer Controls/Dashboard" that could be toggled on/off.

Such controls could be buttons/links to performing actions like reloading plugins and details about what is going on in the system. Here is a quick mock of what it could look like:

<img width="357" alt="screen shot 2015-10-24 at 01 51 23" src="https://cloud.githubusercontent.com/assets/502136/10707390/3a4794a0-79f2-11e5-9f48-32da7c9cf2e4.png">

The concept can easily be extended to allow more controls like selecting which plugin to reload or any other system action the developer might want to perform (clearing cookies, checking state, etc.).

**Comment by nbaars** [comment]
@span: you can also add https://github.com/WebGoat/WebGoat/issues/96 which was added to highlight the text on a page in order to show which one is already in the i18n bundle

**Comment by span** [comment]
Sounds good to me. I can put something together unless @mayhew64 has already started on this or has other ideas?

**Comment by mayhew64** [comment]
I have not started anything on the highlighting.  Feel free to put something together.

**Comment by span** [comment]
Just wanted to let you know I have picked up work on this again and hope to have something after this week (which is way to busy).

**Comment by span** [comment]
So I have most of the wiring in place now but I would like #218 to be fixed so see if re-routing to `start.mvc` is a good alternetive to refresing the tab after reloading plugins and labels.

Ideally I suppose re-routing to whatever page the user was on when clicking `reload` would be great but that requires #194 to be in place.

**Comment by span** [comment]
Started to review this oldie again to try and improve the plugin reload. I am currently struggling to get the reload of the lessons to actually work. The output from the tomcat is claiming everything is reloaded but I don't see any GUI updates nor updates on for example cookie name in the "spoof auth cookie" lesson.

Will keep investigating what is going on here.

**Comment by nbaars** [comment]
Closing, since the release of version 8.0 we no longer actively support version 7.1.
