### ISSUE TITLE
Challenge: Admin password reset always solvable

### ISSUE THREAD

**Issue by ytehran** [WebGoat/WebGoat#949]
I started the WebGoat Challenges tonight and used docker-compose to start it.

When I try the Challenge: Admin password reset, it is always solvable, regardless of what email I type in, and as lovely as that sound I didn't do/try anything yet.

Here are the Request and Response through ZAP

![Screenshot 2021-03-12 013931](https://user-images.githubusercontent.com/73143535/110875916-d0a4b700-82d6-11eb-9d08-71f20ac4bf1f.png)
________________________
![Screenshot 2021-03-12 013851](https://user-images.githubusercontent.com/73143535/110875924-d69a9800-82d6-11eb-9203-660c7cf03d24.png)

Would love to understand what happened

**Comment by zubcevic** [comment]
what version of webgoat?

**Comment by ytehran** [comment]
Current version. I used docker-compose to start it

curl https://raw.githubusercontent.com/WebGoat/WebGoat/develop/docker-compose.yml | docker-compose -f - up

**Comment by zubcevic** [comment]
ok thanks, actually this way you are using a much older version of webgoat. But it means we should update these compose files. And check if this challenge is still broken in the latest webgoat/goatandwolf docker image. See the readme for the all-in-one image

**Comment by ytehran** [comment]
Ahh okay, thank you very much. Should I keep this issue open?  So that the compose files get updated

**Comment by zubcevic** [comment]
sure keep it open, by the way the challenge is only solved when you have captured and submitted the flag. it is just a kind of bug that by triggering the email, the lesson appears as it is solved.

**Comment by nbaars** [comment]
Fixed with: https://github.com/WebGoat/WebGoat/issues/891
