### ISSUE TITLE
SQl-Injection lesson 4 not deleting created row

### ISSUE THREAD

**Issue by SturmCamper** [WebGoat/WebGoat#961]
In the 4th lesson the goal is to alter a table by adding new Row ('phone').
While it works for the first time, the added row never is deleted.

____
![image](https://user-images.githubusercontent.com/66077206/111913696-94f4b480-8a6f-11eb-8530-a5e500345b57.png)
____

The main problem accrues when u want to retry the lesson. U are able to create custom rows and still get an approval.
Also if WebGoat is used by multiple people it may lead to confusions, since they aren't able to complete the task properly.
____
![image](https://user-images.githubusercontent.com/66077206/111913868-10eefc80-8a70-11eb-81a9-130afbe42b8b.png)
____

https://github.com/WebGoat/WebGoat/blob/e40a26f1934bdac9c2275821fa4a0bef576393fc/webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/sql_injection/introduction/SqlInjectionLesson4.java#L56-L75

**Comment by nbaars** [comment]
We can solve that one for now by making the column name random, but we need to have each user have their own schema in the database. This way we solve it once and for all other solution will be "hacky" in a way we need to let the user do create a random column name etc.

Until now we have already split the database user administration from the lesson but the lessons need a different schema for each user. 

We would probably have to create a specific DataSource bean which will before it creates a statements alters the current schema. This way it is transparent while building a lesson.
