### ISSUE TITLE
Lesson not passed

### ISSUE THREAD

**Issue by martynanna** [WebGoat/WebGoat#964]
I completed all of the tasks of the lesson "Path traversal" (A1), but there is no badge. It also shows that I either completed tasks from the page 2 and 3 or 4 and 5.
![chrome_fFcQvLW4aB](https://user-images.githubusercontent.com/73000945/112396119-e61ad780-8cff-11eb-8d64-9f982c0a3a3a.png)
![chrome_QVqOKMdPgU](https://user-images.githubusercontent.com/73000945/112396124-e87d3180-8cff-11eb-9a29-68eba334def5.png)

**Comment by zubcevic** [comment]
Very strange and I cannot reproduce it. Perhaps you clicked on reset lesson in between?

**Comment by zubcevic** [comment]
Or an intercepting proxy is still blocking requests?

**Comment by martynanna** [comment]
Neither nor... I do nothing but reload the page and it just switches...
I tried the local version and everything works fine there. This problem occurs by using docker

**Comment by zubcevic** [comment]
I would need more details about the setup and the steps. Can you replay this? 
Are you using multiple instances of WebGoat? Because it can only run as a single instance.
