### ISSUE TITLE
Guest Login with webgoat 8.1 / java 11

### ISSUE THREAD

**Issue by rnasterofmysea** [WebGoat/WebGoat#965]
![image](https://user-images.githubusercontent.com/75101935/112423929-de4a4a00-8d76-11eb-9424-1e73c4dbffae.png)

when I tried to login with guest account .
I got a issues that said " invalid username and passwd"
when I'd tried the guest login with webgoat 7.1 version, it'd been worked.

in course I wanna study SQL injection with guest account.

**Comment by nbaars** [comment]
Hi @rnasterofmysea, the guest login is no longer present in WebGoat 8, you have to register a new user using the link "Register new user" under the "Sign in" button. You can of course use guest/guest again as username. 

The rationale behind is that in WebGoat 8 multiple users can use the same instance of WebGoat.

**Comment by rnasterofmysea** [comment]
thank you for replying :)
 
Then if I use old version i can use guest account and using stable service?
My college course only instruct us to use guest account. 
compared to old version , I think 8.1v course is quite different,
I'd like to follow SQL injection course.
I attached a screenshot above.( this is my course) :(
-----Original Message-----

**Comment by nbaars** [comment]
> Then if I use old version i can use guest account and using stable service?
You need to register a random user indeed, WG 8 & 7.1 do not share settings, after you create the user it can be used all the time, it is stored.

>I'd like to follow SQL injection course.
In WebGoat 8 the same SQL injection lessons are available and we extended the topic as well with new lessons.
If you solve the SQL injections in WG 8 you can certainly solve all the lessons in WG 7.1

**Comment by rnasterofmysea** [comment]
Thank you a lot.
I resolve the problems with 8.1 version.
I can thrill the steps easily with well explained description. 
I appreciate your service :)
Have a good day.
 
Ps. I attached Powerpoint that proceed SQL injection intro course 
-----Original Message-----

**Comment by rnasterofmysea** [comment]
Sorry to send a mail agian,
 
In this week I should proceed CSRF hacking course.
 
On WB 8.1 I can't find course about CSRF.
 
I'm wondering I miss something about this
-----Original Message-----

**Comment by zubcevic** [comment]
It is the category A8:2013 Request Forgeries and contains CSRF and SSRF lessons
