### ISSUE TITLE
Crypto Basics Lesson 8

### ISSUE THREAD

**Issue by SirBlob** [WebGoat/WebGoat#966]
This lesson doesn't work for the Standalone version as if you try to run the command requested to initialize the docker container image it cannot find that file.

**Command**
`docker run -d webgoat/assignments:findthesecret`
**Result**
`Unable to find image 'webgoat/assignments:findthesecret' locally`

I tried to find if anyone else has encounter this problem and didn't look like it.
Please let me know if I need to download additional files on top of the webgoat and webwolf jar.

Thank You

**Comment by zubcevic** [comment]
You need an internet connection or connection to a registry that has the image. The image is still there on docker hub. (could have been removed by one of the new policies, but luckily still there)

Trying to pull docker.io/webgoat/assignments:findthesecret...
Getting image source signatures
Copying blob e6d9d96381c8 done  
Copying blob 5d9d21aca480 done  
Copying blob 0a126fb8ec28 done  
Copying blob 1904df324545 done  
Copying blob 1cf4e4a3f534 done  
Copying blob 5e6ec7f28fb7 done  
Copying blob d6419a981ec6 done  
Copying blob ff2e10214d79 done  
Copying blob 4cf180de4a1f done  
Copying config 4b07f81e83 done  
Writing manifest to image destination
Storing signatures
d063170967d1a5facd77777b26cf30874070dc4145ab09c1cb984842b6510eb8

**Comment by SirBlob** [comment]
Ah, I see I have it set up on a VM with the network set as Host Only.

I'm wondering if it is possible to include this tip that Internet Access might be required to download docker image for this lesson?

Otherwise great work learned a couple new things already.

Thanks
