### ISSUE TITLE
re-enable challenge handling in LessonInfoModel

### ISSUE THREAD

**Issue by misfir3** [WebGoat/WebGoat#97]
Challenge needs hints turned off. This special case needs to be moved from LessonMenuService to the LessonInfoModel/Service.

See comments in https://github.com/WebGoat/WebGoat/pull/94

**Comment by mayhew64** [comment]
@misfir3 @nbaars We need to make this one a priority.  We need a RBAC mechanism that is checked for presentation and server side access control.

**Comment by misfir3** [comment]
presentation side is covered (commit/push/pull  pending) ... looking at backing it up on server-side. No hints should be pulled at all on a challenge, correct?

**Comment by misfir3** [comment]
@nbaars @mayhew64  ... give it a once over. If it passes muster, go ahead and import.

**Comment by mayhew64** [comment]
@misfir3 I think we want to perform the check on a role versus a category.  I could see other lessons want to disable presentation layer access checks.  If it is easy to change to a role, lets do that.  If not, we can go with checking the category.  I can also see other lessons being in the challenge category and not wanting to have these features disabled.

**Comment by misfir3** [comment]
Good point. I'll take another look later today (~ 4 PM ET). Should be able to look at your other PR then as well.

**Comment by misfir3** [comment]
Closing since PR has been completed.

**Comment by sreejithbk** [comment]
How to disable lesson hints
