### ISSUE TITLE
[Lesson] SQL injection Intro 5 not solvable

### ISSUE THREAD

**Issue by schwzr** [WebGoat/WebGoat#974]
Version used: 8.2.1-SNAPSHOT

Lesson description: "Try to grant the user group "UnauthorizedUser" the right to alter tables"

The lesson can't be solved because the "grant alter table" without the specification of an object (like a table, sequence, ...) is not possible in HSQLDB.

Documentation (http://hsqldb.org/doc/2.0/guide/guide.html#acc_access_rights):

```
GRANT

grant privilege statement

<grant privilege statement> ::= GRANT <privileges> TO <grantee> [ { <comma> <grantee> }... ] [ WITH GRANT OPTION ] [ GRANTED BY <grantor> ]

Assign privileges on schema objects to roles or users. Each <grantee> is a role or a user. If [ WITH GRANT OPTION ] is specified, then the <grantee> can assign the privileges to other <grantee> objects.

<privileges> ::= <object privileges> ON <object name>

<object privileges> ::= ALL PRIVILEGES | <action> [ <filter clause> ] [ { <comma> <action> }... ]

<action> ::= SELECT | SELECT <left paren> <privilege column list> <right paren> | DELETE | INSERT [ <left paren> <privilege column list> <right paren> ] | UPDATE [ <left paren> <privilege column list> <right paren> ] | REFERENCES [ <left paren> <privilege column list> <right paren> ] | TRIGGER | USAGE | EXECUTE

<object name> ::= [ TABLE ] <table name> | DOMAIN <domain name> | COLLATION <collation name> | CHARACTER SET <character set name> | TRANSLATION <transliteration name> | TYPE <user-defined type name> | SEQUENCE <sequence generator name> | <specific routine designator> | ROUTINE <routine name> | FUNCTION <function name> | PROCEDURE <procedure name>
```

Solving the challenge was possible before the rewrite of the solution checker (https://github.com/WebGoat/WebGoat/commit/d4da2d0efa2245f007a78911280bb8d27c101da6). Maybe just the lesson description is not updated yet?

**Comment by nbaars** [comment]
Thanks for reporting indeed this is an issue. This has been reported through the WebGoat mailing list as well, I forgot to make a Github issue for it. It has been fixed but waiting on a release:

https://github.com/WebGoat/WebGoat/commit/d4da2d0efa2245f007a78911280bb8d27c101da6

**Comment by nbaars** [comment]
@schwzr thanks you for checking! I will check the lesson description think I indeed forgot to update the text

**Comment by nbaars** [comment]
@schwzr updated the lesson text https://github.com/WebGoat/WebGoat/pull/981
