### ISSUE TITLE
Cannot Compile - Java16.1 and MVN 3.8.1

### ISSUE THREAD

**Issue by soumyamaity** [WebGoat/WebGoat#993]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WebGoat Parent Pom 8.2.0-SNAPSHOT:
[INFO]
[INFO] WebGoat Parent Pom ................................. SUCCESS [  1.338 s]
[INFO] webgoat-container .................................. FAILURE [  8.332 s]
[INFO] webgoat-plugins-parent ............................. SKIPPED
[INFO] bypass-restrictions ................................ SKIPPED
[INFO] challenge .......................................... SKIPPED
[INFO] client-side-filtering .............................. SKIPPED
[INFO] cross-site-scripting ............................... SKIPPED
[INFO] html-tampering ..................................... SKIPPED
[INFO] http-basics ........................................ SKIPPED
[INFO] cia ................................................ SKIPPED
[INFO] chrome-dev-tools ................................... SKIPPED
[INFO] http-proxies ....................................... SKIPPED
[INFO] insecure-login ..................................... SKIPPED
[INFO] insecure-deserialization ........................... SKIPPED
[INFO] jwt ................................................ SKIPPED
[INFO] sql-injection ...................................... SKIPPED
[INFO] xxe ................................................ SKIPPED
[INFO] idor ............................................... SKIPPED
[INFO] vulnerable-components .............................. SKIPPED
[INFO] webgoat-introduction ............................... SKIPPED
[INFO] webwolf-introduction ............................... SKIPPED
[INFO] auth-bypass ........................................ SKIPPED
[INFO] missing-function-ac ................................ SKIPPED
[INFO] csrf ............................................... SKIPPED
[INFO] password-reset ..................................... SKIPPED
[INFO] ssrf ............................................... SKIPPED
[INFO] secure-passwords ................................... SKIPPED
[INFO] webgoat-lesson-template ............................ SKIPPED
[INFO] crypto ............................................. SKIPPED
[INFO] webwolf ............................................ SKIPPED
[INFO] webgoat-integration-tests .......................... SKIPPED
[INFO] webgoat-all-in-one-docker .......................... SKIPPED
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.297 s
[INFO] Finished at: 2021-04-23T19:26:42+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project webgoat-container: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @64245ca9 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :webgoat-container

**Comment by nbaars** [comment]
@soumyamaity indeed at the moment we only support Java 15. For the next release we will support Java 16

**Comment by soumyamaity** [comment]
is there any known compatibility issue with Java16 ?

**Comment by nbaars** [comment]
Looking at the error it might be related to Lombok think we need to update to the latest version (https://projectlombok.org/changelog)

**Comment by soumyamaity** [comment]
I downgraded my JDK and it works perfectly now. 
Works perfectly with : maven:3.8.1-openjdk-15
Closing the issue. Thank you.
