### ISSUE TITLE
webgoat dosen't run

### ISSUE THREAD

**Issue by boar9** [WebGoat/WebGoat#994]
hi guys!
first of all, thanks toread me.
i started to use webgoat a few days ago but today it dosen't run.
when i put http://127.0.0.1:8080/WebGoat i recieve this message from firefox "**firefox cannot establish a connection with the server http://127.0.0.1:8080/"** .  i don't know why and i don't know how to solve it.
can someone help me?
p.s. i use Ubuntu (virtualmachine)

thanks:)

**Comment by coolman669** [comment]
> ``hhkgy`uu`

**Comment by zubcevic** [comment]
did you stop the application? Can you provide more details?
